import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    search: "Search in folder",
    searching: "Search in folder…",
    noFolder: "No folder.",
    emptyFolder: "Empty folder.",
    noMatch: "Nothing matches.",
    noneOpen: "No file open",
    code: "Code",
    view: "Preview",
    choose: "Choose a file.",
    enlarge: "View larger",
    unreadable: "Couldn’t show the picture",
    unreadableSaid: (size: string) => `Its content isn’t a picture the viewer can read (${size}).`,
    openFailed: "Couldn’t open it",
    tooBig: "Too big",
    tooBigSaid: (size: string, cap: string) => `It’s ${size}, and the viewer shows files up to ${cap}.`,
    noPreview: "No preview",
    noPreviewSaid: (size: string) => `It’s neither UTF-8 text nor a picture (${size}).`,
  },
  es: {
    search: "Buscar en la carpeta",
    searching: "Buscar en la carpeta…",
    noFolder: "Sin carpeta.",
    emptyFolder: "Carpeta vacía.",
    noMatch: "Nada coincide.",
    noneOpen: "Ningún fichero abierto",
    code: "Código",
    view: "Vista",
    choose: "Elige un fichero.",
    enlarge: "Ver en grande",
    unreadable: "No pude dibujar la imagen",
    unreadableSaid: (size: string) => `Su contenido no es una imagen que el visor sepa leer (${size}).`,
    openFailed: "Error al abrir",
    tooBig: "Demasiado grande",
    tooBigSaid: (size: string, cap: string) => `Pesa ${size} y el visor muestra hasta ${cap}.`,
    noPreview: "Sin vista previa",
    noPreviewSaid: (size: string) => `No es texto UTF-8 ni una imagen (${size}).`,
  },
  fr: {
    search: "Rechercher dans le dossier",
    searching: "Rechercher dans le dossier…",
    noFolder: "Aucun dossier.",
    emptyFolder: "Dossier vide.",
    noMatch: "Aucun résultat.",
    noneOpen: "Aucun fichier ouvert",
    code: "Code",
    view: "Aperçu",
    choose: "Choisissez un fichier.",
    enlarge: "Agrandir",
    unreadable: "Impossible d’afficher l’image",
    unreadableSaid: (size: string) => `Son contenu n’est pas une image que la visionneuse sait lire (${size}).`,
    openFailed: "Impossible d’ouvrir le fichier",
    tooBig: "Trop volumineux",
    tooBigSaid: (size: string, cap: string) => `Il pèse ${size} et la visionneuse affiche jusqu’à ${cap}.`,
    noPreview: "Pas d’aperçu",
    noPreviewSaid: (size: string) => `Ce n’est ni du texte UTF-8 ni une image (${size}).`,
  },
  de: {
    search: "Im Ordner suchen",
    searching: "Im Ordner suchen…",
    noFolder: "Kein Ordner.",
    emptyFolder: "Leerer Ordner.",
    noMatch: "Keine Treffer.",
    noneOpen: "Keine Datei geöffnet",
    code: "Code",
    view: "Vorschau",
    choose: "Wähle eine Datei.",
    enlarge: "Groß anzeigen",
    unreadable: "Das Bild lässt sich nicht anzeigen",
    unreadableSaid: (size: string) => `Der Inhalt ist kein Bild, das die Vorschau lesen kann (${size}).`,
    openFailed: "Fehler beim Öffnen",
    tooBig: "Zu groß",
    tooBigSaid: (size: string, cap: string) => `Die Datei ist ${size} groß; die Vorschau zeigt Dateien bis ${cap}.`,
    noPreview: "Keine Vorschau",
    noPreviewSaid: (size: string) => `Weder UTF-8-Text noch ein Bild (${size}).`,
  },
  ja: {
    search: "フォルダー内を検索",
    searching: "フォルダー内を検索…",
    noFolder: "フォルダーがありません。",
    emptyFolder: "空のフォルダーです。",
    noMatch: "一致するものはありません。",
    noneOpen: "開いているファイルはありません",
    code: "コード",
    view: "プレビュー",
    choose: "ファイルを選んでください。",
    enlarge: "拡大表示",
    unreadable: "画像を表示できませんでした",
    unreadableSaid: (size: string) => `ビューアーで読み取れる画像ではありません（${size}）。`,
    openFailed: "開けませんでした",
    tooBig: "サイズが大きすぎます",
    tooBigSaid: (size: string, cap: string) => `サイズは ${size} です。ビューアーで表示できるのは ${cap} までです。`,
    noPreview: "プレビューなし",
    noPreviewSaid: (size: string) => `UTF-8 テキストでも画像でもありません（${size}）。`,
  },
  zh: {
    search: "在文件夹中搜索",
    searching: "在文件夹中搜索…",
    noFolder: "没有文件夹。",
    emptyFolder: "文件夹为空。",
    noMatch: "没有匹配项。",
    noneOpen: "未打开文件",
    code: "代码",
    view: "预览",
    choose: "请选择一个文件。",
    enlarge: "查看大图",
    unreadable: "无法显示图片",
    unreadableSaid: (size: string) => `其内容不是查看器能读取的图片（${size}）。`,
    openFailed: "打开失败",
    tooBig: "文件过大",
    tooBigSaid: (size: string, cap: string) => `文件大小为 ${size}，查看器最多显示 ${cap}。`,
    noPreview: "无法预览",
    noPreviewSaid: (size: string) => `既不是 UTF-8 文本，也不是图片（${size}）。`,
  },
});
