import { copy } from "../../shared/i18n";

const listEn = (parts: string[]) => (parts.length > 1 ? `${parts.slice(0, -1).join(", ")} and ${parts.at(-1)}` : parts[0]);
const listEs = (parts: string[]) => (parts.length > 1 ? `${parts.slice(0, -1).join(", ")} y ${parts.at(-1)}` : parts[0]);
const listFr = (parts: string[]) => (parts.length > 1 ? `${parts.slice(0, -1).join(", ")} et ${parts.at(-1)}` : parts[0]);
const listDe = (parts: string[]) => (parts.length > 1 ? `${parts.slice(0, -1).join(", ")} und ${parts.at(-1)}` : parts[0]);
const plural = (count: number, one: string, many: string) => `${count} ${count === 1 ? one : many}`;

export const t = copy({
  en: {
    title: "Capabilities",
    lede: "Plugins, skills and connectors Sens can use in your sessions.",
    modes: "What to show",
    installedMode: "Installed",
    exploreMode: "Explore",
    add: "Add",
    addMenu: "Add a capability",
    createSkill: "Create skill",
    importFolder: "Import folder",
    addServer: "Add MCP server",
    unopened: "Open a project to enable capabilities.",
    loadsNote: "The agent loads them from your next message in this project.",
    kindTabs: "Capability kinds",
    tabAll: "All",
    tabPlugins: "Plugins",
    tabSkills: "Skills",
    tabServers: "MCP",
    emptyAll: "No capabilities",
    emptyAllSaid: "Explore the catalog, create or import a skill, or add an MCP server.",
    emptyPlugins: "No plugins",
    emptyPluginsSaid: "Explore the catalog to install one.",
    emptySkills: "No skills",
    emptySkillsSaid: "Add a skill to give the agent reusable instructions.",
    emptyServers: "No MCP servers",
    emptyServersSaid: "Add an MCP server to give the agent new tools.",
    seekInstalled: "Search skills, plugins and servers",
    seekInstalledHint: "Search skills, plugins and servers…",
    nothingMatches: "Nothing matches.",
    enabledIn: (project: string) => `Enabled in ${project}`,
    groupOn: (project: string) => `Enabled in ${project}`,
    groupOff: (project: string) => `Not enabled in ${project}`,
    installedGroup: "Installed",
    yourChoice: "You decide what is enabled in each project.",
    enableIn: (name: string, project: string) => `Enable ${name} in ${project}`,
    enable: (name: string) => `Enable ${name}`,
    actionsOf: (name: string) => `Actions for ${name}`,
    remove: "Remove",
    uninstall: "Uninstall",
    update: "Update",
    details: "View details",
    openSkill: "Open SKILL.md",
    updateReady: "Update available",
    local: "Local",
    nothingOn: "Nothing enabled in this project",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && plural(plugins, "plugin", "plugins"),
        skills && plural(skills, "skill", "skills"),
        servers && plural(servers, "MCP server", "MCP servers"),
      ].filter((part): part is string => Boolean(part));
      return `${listEn(parts)} enabled in this project`;
    },
    plugin: "Plugin",
    skill: "Skill",
    connector: "Connector",
    mcp: "MCP",
    gonePlugin: "Its folder is deleted, along with the values you saved for it.",
    goneSkill: "Its folder is deleted with everything in it.",
    goneServer: "Its settings are deleted, environment variables included.",
    envLine: (line: number) => `Environment variables, line ${line}: write KEY=value.`,
    envTwice: (key: string) => `Environment variables: ${key} is repeated.`,
    hook: (event: string) => `Hook · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "Executable",
    badgeAnthropic: "Anthropic",
    badgePartner: "Official",
    badgeCommunity: "Community",
    badgeSkillsSh: "skills.sh",
    kindAll: "All",
    kindPlugins: "Plugins",
    kindSkills: "Skills",
    kindConnectors: "Connectors",
    sourceAll: "All",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "Community",
    sourceSkillsSh: "skills.sh",
    seekMarket: "Search the catalog",
    seekMarketHint: (count: string) => `Search ${count} plugins, skills and connectors…`,
    seekMarketHintPlain: "Search the catalog…",
    sections: "Sections",
    discover: "Discover",
    everything: "All",
    kind: "Kind",
    source: "Source",
    couldNotUpdate: (list: string) => `Couldn’t update ${list}`,
    loadingCatalogue: "Loading the catalog…",
    seekingSkillsSh: "Searching skills.sh too…",
    catalogueOf: (when: string) => `Catalog from ${when}`,
    refreshing: "Refreshing…",
    refresh: "Refresh catalog",
    showMore: (left: string) => `Show more · ${left} left`,
    results: (count: number, shown: string, query: string) => `${count === 1 ? "1 result" : `${shown} results`} for “${query}”`,
    listed: (count: number, shown: string) => (count === 1 ? "1 listing" : `${shown} listings`),
    steps: "How capabilities work",
    stepInstall: "Install once",
    stepInstallSaid: "Downloaded and pinned to a version.",
    stepEnable: "Enable per project",
    stepEnableSaid: "Each project gets only what you enable.",
    stepUse: "Use it in sessions",
    stepUseSaid: "Loaded from your next message.",
    startHere: "Start here",
    startHereSaid: "Picked from Anthropic’s own plugins and skills.",
    connectTools: "Connect your tools",
    connectToolsSaid: "Connectors that work without signing in.",
    seeAll: "See all",
    seeAllOf: (name: string) => `See all in ${name}`,
    addCard: "Add",
    adding: "Adding…",
    installCard: "Install",
    addTo: (title: string, project: string) => `Add ${title} to ${project}`,
    installNamed: (title: string) => `Install ${title}`,
    addHere: (project: string) => `Add to ${project}`,
    addsTo: (project: string) => `Adds to ${project}`,
    noProject: "No project open: installing only",
    installedTag: "Installed",
    enabledTag: "Enabled here",
    tools: (count: number) => (count === 1 ? "1 tool" : `${count} tools`),
    installs: (shown: string) => `${shown} installs`,
    signIn: "Sign-in required",
    notInstallable: "Not installable from Sens",
    by: (author: string) => `by ${author}`,
    addFailed: (title: string, reason: string) => `Couldn’t add ${title}: ${reason}`,
    downloading: "Downloading to show you everything…",
    installing: "Installing…",
    install: "Install",
    whyLogin: "It asks you to sign in to the service; Sens can’t do that for you yet.",
    whyOrigin: "This source can’t be installed from Sens.",
    viewSource: "View source",
    openToEnable: "Open a project to enable it",
    detailTabs: "Parts of the listing",
    summary: "Overview",
    contents: "Contents",
    runs: "What it runs",
    toolsTitle: (count: number) => `Tools · ${count}`,
    skillsGroup: "Skills",
    commandsGroup: "Commands",
    agentsGroup: "Agents",
    filesNav: "Files",
    filesGroup: (count: number) => `Files · ${count}`,
    andMore: (count: number) => `and ${count} more`,
    pickFile: "Choose a file to read it.",
    reading: "Reading…",
    hooks: "Hooks",
    servers: "MCP servers",
    executables: "Executables",
    lsp: "LSP",
    asks: "What it will ask you",
    signingIn: "Signing in",
    asksSignIn: "Asks you to sign in to the service",
    optional: "optional",
    noCode: "Runs no code: instructions only.",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && plural(hooks, "hook", "hooks"),
        servers && plural(servers, "MCP server", "MCP servers"),
        bins && plural(bins, "executable", "executables"),
        lsp && plural(lsp, "language server", "language servers"),
      ].filter((part): part is string => Boolean(part));
      return `Runs code on your computer: ${listEn(parts)}.`;
    },
    runsRemote: "Runs on the provider’s servers.",
    runsRemoteAt: (host: string) => `Runs on the provider’s servers: ${host}.`,
    seeRuns: "See what it runs",
    journey: "How it connects",
    jInstall: "Install",
    jInstalled: (version: string) => (version ? `Installed · v${version}` : "Installed"),
    jNotInstalled: "Downloads once, pinned to this version",
    jEnable: (project: string) => `Enable in ${project}`,
    jEnableAny: "Enable in a project",
    jEnabled: "Enabled",
    jOff: "Off",
    jNoProject: "Open a project first",
    jUse: "Use in sessions",
    jUsing: "From your next message",
    jWaiting: "Once enabled",
    create: "Create",
    name: "Name",
    skillNameNote: "Lowercase letters, numbers and hyphens, not starting with a hyphen. Up to 64 characters.",
    description: "Description",
    instructions: "Instructions",
    serverNameNote: "Letters, numbers, hyphens and underscores. Up to 64 characters.",
    command: "Command",
    args: "Arguments",
    argsNote: "One per line.",
    env: "Environment variables",
    envNote: "KEY=value, one per line. Values aren’t shown again.",
    runsWarning: "This runs code on your computer when the agent uses it:",
    optionalNote: "Optional.",
    installTitle: (title: string) => `Install ${title}`,
    chooseSkillFolder: "Choose the skill’s folder",
    sectionNames: {
      code: "Code & dev tools",
      agents: "Agents & AI",
      data: "Data & databases",
      cloud: "Cloud & DevOps",
      security: "Security",
      design: "Design & media",
      productivity: "Productivity & docs",
      communication: "Communication",
      business: "Business & sales",
      finance: "Finance",
      science: "Science & health",
      learning: "Learning",
      lifestyle: "Travel & lifestyle",
      other: "Other",
    },
    sectionAbouts: {
      code: "Languages, tests, reviews, Git and the tools around your code.",
      agents: "Agents, memory, prompts and ways to shape how Claude works.",
      data: "Databases, analytics, dashboards and data pipelines.",
      cloud: "Deploying, hosting, monitoring and running infrastructure.",
      security: "Scanning, compliance, secrets and access.",
      design: "Interfaces, images, video, diagrams and websites.",
      productivity: "Notes, documents, calendars and project tracking.",
      communication: "Email, chat, meetings and messages.",
      business: "Marketing, sales, support, legal and hiring.",
      finance: "Payments, accounting, investing and crypto.",
      science: "Research, life sciences, medicine and math.",
      learning: "Courses, tutoring and explained code.",
      lifestyle: "Trips, food, entertainment and everyday services.",
      other: "What fits no section above.",
    },
    sourceNames: {
      official: "Anthropic’s official plugins",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "Community plugins reviewed by Anthropic",
      skills: "Anthropic’s skills",
      connectors: "Anthropic’s connectors",
    },
  },
  es: {
    title: "Capacidades",
    lede: "Plugins, skills y conectores que Sens puede usar en tus sesiones.",
    modes: "Qué ver",
    installedMode: "Instaladas",
    exploreMode: "Explorar",
    add: "Añadir",
    addMenu: "Añadir capacidad",
    createSkill: "Crear skill",
    importFolder: "Importar carpeta",
    addServer: "Añadir servidor MCP",
    unopened: "Abre un proyecto para activar capacidades.",
    loadsNote: "El agente las carga a partir de tu próximo mensaje en este proyecto.",
    kindTabs: "Tipos de capacidad",
    tabAll: "Todas",
    tabPlugins: "Plugins",
    tabSkills: "Skills",
    tabServers: "MCP",
    emptyAll: "No hay capacidades",
    emptyAllSaid: "Explora el mercado, o crea o importa una skill, o añade un servidor MCP.",
    emptyPlugins: "No hay plugins",
    emptyPluginsSaid: "Explora el mercado para instalar uno.",
    emptySkills: "No hay skills",
    emptySkillsSaid: "Añade una skill para darle instrucciones reutilizables al agente.",
    emptyServers: "No hay servidores MCP",
    emptyServersSaid: "Añade un servidor MCP para darle herramientas nuevas al agente.",
    seekInstalled: "Buscar una skill, plugin o servidor",
    seekInstalledHint: "Buscar una skill, plugin o servidor…",
    nothingMatches: "Nada coincide.",
    enabledIn: (project: string) => `Activa en ${project}`,
    groupOn: (project: string) => `Activas en ${project}`,
    groupOff: (project: string) => `Sin activar en ${project}`,
    installedGroup: "Instaladas",
    yourChoice: "Tú decides qué se activa en cada proyecto.",
    enableIn: (name: string, project: string) => `Activar ${name} en ${project}`,
    enable: (name: string) => `Activar ${name}`,
    actionsOf: (name: string) => `Acciones de ${name}`,
    remove: "Quitar",
    uninstall: "Desinstalar",
    update: "Actualizar",
    details: "Ver ficha",
    openSkill: "Abrir SKILL.md",
    updateReady: "Actualización disponible",
    local: "Local",
    nothingOn: "Nada activo en este proyecto",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && plural(plugins, "plugin", "plugins"),
        skills && plural(skills, "skill", "skills"),
        servers && `${servers} MCP`,
      ].filter((part): part is string => Boolean(part));
      const one = plugins + skills + servers === 1;
      const said = servers || plugins ? (one ? "activo" : "activos") : one ? "activa" : "activas";
      return `${listEs(parts)} ${said} en este proyecto`;
    },
    plugin: "Plugin",
    skill: "Skill",
    connector: "Conector",
    mcp: "MCP",
    gonePlugin: "Se borra su carpeta y las variables que guardaste para él.",
    goneSkill: "Se borra su carpeta con todo lo que contiene.",
    goneServer: "Se borra su configuración, variables de entorno incluidas.",
    envLine: (line: number) => `Variables de entorno, línea ${line}: escribe CLAVE=valor.`,
    envTwice: (key: string) => `Variables de entorno: ${key} está repetida.`,
    hook: (event: string) => `Hook · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "Ejecutable",
    badgeAnthropic: "Anthropic",
    badgePartner: "Oficial",
    badgeCommunity: "Comunidad",
    badgeSkillsSh: "skills.sh",
    kindAll: "Todo",
    kindPlugins: "Plugins",
    kindSkills: "Skills",
    kindConnectors: "Conectores",
    sourceAll: "Todas",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "Comunidad",
    sourceSkillsSh: "skills.sh",
    seekMarket: "Buscar en el mercado",
    seekMarketHint: (count: string) => `Busca entre ${count} plugins, skills y conectores…`,
    seekMarketHintPlain: "Buscar en el mercado…",
    sections: "Secciones",
    discover: "Descubrir",
    everything: "Todo",
    kind: "Tipo",
    source: "Fuente",
    couldNotUpdate: (list: string) => `No pude actualizar ${list}`,
    loadingCatalogue: "Cargando el catálogo…",
    seekingSkillsSh: "Buscando también en skills.sh…",
    catalogueOf: (when: string) => `Catálogo del ${when}`,
    refreshing: "Actualizando…",
    refresh: "Actualizar catálogo",
    showMore: (left: string) => `Ver más · quedan ${left}`,
    results: (count: number, shown: string, query: string) => `${count === 1 ? "1 resultado" : `${shown} resultados`} para «${query}»`,
    listed: (count: number, shown: string) => (count === 1 ? "1 ficha" : `${shown} fichas`),
    steps: "Cómo funcionan las capacidades",
    stepInstall: "Instala una vez",
    stepInstallSaid: "Se descarga y queda fijada a una versión.",
    stepEnable: "Actívala por proyecto",
    stepEnableSaid: "Cada proyecto usa solo lo que actives.",
    stepUse: "Úsala en tus sesiones",
    stepUseSaid: "Se carga desde tu próximo mensaje.",
    startHere: "Para empezar",
    startHereSaid: "Una selección de los plugins y skills de Anthropic.",
    connectTools: "Conecta tus herramientas",
    connectToolsSaid: "Conectores que funcionan sin iniciar sesión.",
    seeAll: "Ver todo",
    seeAllOf: (name: string) => `Ver todo en ${name}`,
    addCard: "Añadir",
    adding: "Añadiendo…",
    installCard: "Instalar",
    addTo: (title: string, project: string) => `Añadir ${title} a ${project}`,
    installNamed: (title: string) => `Instalar ${title}`,
    addHere: (project: string) => `Añadir a ${project}`,
    addsTo: (project: string) => `Se añade a ${project}`,
    noProject: "Sin proyecto abierto: solo se instala",
    installedTag: "Instalada",
    enabledTag: "Activa aquí",
    tools: (count: number) => (count === 1 ? "1 herramienta" : `${count} herramientas`),
    installs: (shown: string) => `${shown} instalaciones`,
    signIn: "Pide iniciar sesión",
    notInstallable: "No se instala desde Sens",
    by: (author: string) => `de ${author}`,
    addFailed: (title: string, reason: string) => `No pude añadir ${title}: ${reason}`,
    downloading: "Descargando para mostrártelo…",
    installing: "Instalando…",
    install: "Instalar",
    whyLogin: "Pide iniciar sesión en el servicio; Sens aún no puede hacerlo por ti.",
    whyOrigin: "Este origen no se puede instalar desde Sens.",
    viewSource: "Ver fuente",
    openToEnable: "Abre un proyecto para activarla",
    detailTabs: "Partes de la ficha",
    summary: "Resumen",
    contents: "Contenido",
    runs: "Qué ejecuta",
    toolsTitle: (count: number) => `Herramientas · ${count}`,
    skillsGroup: "Skills",
    commandsGroup: "Comandos",
    agentsGroup: "Agentes",
    filesNav: "Ficheros",
    filesGroup: (count: number) => `Ficheros · ${count}`,
    andMore: (count: number) => `y ${count} más`,
    pickFile: "Elige un fichero para leerlo.",
    reading: "Leyendo…",
    hooks: "Hooks",
    servers: "Servidores MCP",
    executables: "Ejecutables",
    lsp: "LSP",
    asks: "Lo que te pedirá",
    signingIn: "Inicio de sesión",
    asksSignIn: "Pide iniciar sesión en el servicio",
    optional: "opcional",
    noCode: "No ejecuta código: solo instrucciones.",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && plural(hooks, "hook", "hooks"),
        servers && plural(servers, "servidor MCP", "servidores MCP"),
        bins && plural(bins, "ejecutable", "ejecutables"),
        lsp && plural(lsp, "servidor de lenguaje", "servidores de lenguaje"),
      ].filter((part): part is string => Boolean(part));
      return `Ejecuta código en tu equipo: ${listEs(parts)}.`;
    },
    runsRemote: "Se ejecuta en los servidores del proveedor.",
    runsRemoteAt: (host: string) => `Se ejecuta en los servidores del proveedor: ${host}.`,
    seeRuns: "Ver qué ejecuta",
    journey: "Cómo se conecta",
    jInstall: "Instalar",
    jInstalled: (version: string) => (version ? `Instalada · v${version}` : "Instalada"),
    jNotInstalled: "Se descarga una vez, fijada a esta versión",
    jEnable: (project: string) => `Activar en ${project}`,
    jEnableAny: "Activar en un proyecto",
    jEnabled: "Activada",
    jOff: "Desactivada",
    jNoProject: "Abre antes un proyecto",
    jUse: "Usar en sesiones",
    jUsing: "Desde tu próximo mensaje",
    jWaiting: "Cuando esté activada",
    create: "Crear",
    name: "Nombre",
    skillNameNote: "Minúsculas, números y guiones, sin empezar por guion. Hasta 64 caracteres.",
    description: "Descripción",
    instructions: "Instrucciones",
    serverNameNote: "Letras, números, guiones y guiones bajos. Hasta 64 caracteres.",
    command: "Comando",
    args: "Argumentos",
    argsNote: "Uno por línea.",
    env: "Variables de entorno",
    envNote: "CLAVE=valor, una por línea. Los valores no se vuelven a mostrar.",
    runsWarning: "Esto ejecuta código en tu equipo cuando el agente lo usa:",
    optionalNote: "Opcional.",
    installTitle: (title: string) => `Instalar ${title}`,
    chooseSkillFolder: "Elige la carpeta de la skill",
    sectionNames: {
      code: "Código y desarrollo",
      agents: "Agentes e IA",
      data: "Datos y bases de datos",
      cloud: "Nube y DevOps",
      security: "Seguridad",
      design: "Diseño y medios",
      productivity: "Productividad y documentos",
      communication: "Comunicación",
      business: "Negocio y ventas",
      finance: "Finanzas",
      science: "Ciencia y salud",
      learning: "Aprendizaje",
      lifestyle: "Viajes y ocio",
      other: "Otros",
    },
    sectionAbouts: {
      code: "Lenguajes, tests, revisiones, Git y las herramientas de tu código.",
      agents: "Agentes, memoria, prompts y formas de ajustar cómo trabaja Claude.",
      data: "Bases de datos, analítica, paneles y flujos de datos.",
      cloud: "Despliegue, alojamiento, monitorización e infraestructura.",
      security: "Análisis, cumplimiento, secretos y accesos.",
      design: "Interfaces, imágenes, vídeo, diagramas y webs.",
      productivity: "Notas, documentos, calendarios y seguimiento de proyectos.",
      communication: "Correo, chat, reuniones y mensajes.",
      business: "Marketing, ventas, soporte, legal y selección de personal.",
      finance: "Pagos, contabilidad, inversión y cripto.",
      science: "Investigación, ciencias de la vida, medicina y matemáticas.",
      learning: "Cursos, tutorías y código explicado.",
      lifestyle: "Viajes, comida, entretenimiento y servicios del día a día.",
      other: "Lo que no encaja en ninguna sección.",
    },
    sourceNames: {
      official: "Plugins oficiales de Anthropic",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "Comunidad revisada por Anthropic",
      skills: "Skills de Anthropic",
      connectors: "Conectores de Anthropic",
    },
  },
  fr: {
    title: "Capacités",
    lede: "Plugins, skills et connecteurs que Sens peut utiliser dans vos sessions.",
    modes: "Affichage",
    installedMode: "Installées",
    exploreMode: "Explorer",
    add: "Ajouter",
    addMenu: "Ajouter une capacité",
    createSkill: "Créer une skill",
    importFolder: "Importer un dossier",
    addServer: "Ajouter un serveur MCP",
    unopened: "Ouvrez un projet pour activer des capacités.",
    loadsNote: "L’agent les charge à partir de votre prochain message dans ce projet.",
    kindTabs: "Types de capacité",
    tabAll: "Toutes",
    tabPlugins: "Plugins",
    tabSkills: "Skills",
    tabServers: "MCP",
    emptyAll: "Aucune capacité",
    emptyAllSaid: "Explorez le catalogue, créez ou importez une skill, ou ajoutez un serveur MCP.",
    emptyPlugins: "Aucun plugin",
    emptyPluginsSaid: "Explorez le catalogue pour en installer un.",
    emptySkills: "Aucune skill",
    emptySkillsSaid: "Ajoutez une skill pour donner à l’agent des instructions réutilisables.",
    emptyServers: "Aucun serveur MCP",
    emptyServersSaid: "Ajoutez un serveur MCP pour donner de nouveaux outils à l’agent.",
    seekInstalled: "Rechercher une skill, un plugin ou un serveur",
    seekInstalledHint: "Rechercher une skill, un plugin ou un serveur…",
    nothingMatches: "Aucun résultat.",
    enabledIn: (project: string) => `Activée dans ${project}`,
    groupOn: (project: string) => `Activées dans ${project}`,
    groupOff: (project: string) => `Non activées dans ${project}`,
    installedGroup: "Installées",
    yourChoice: "Vous décidez de ce qui est activé dans chaque projet.",
    enableIn: (name: string, project: string) => `Activer ${name} dans ${project}`,
    enable: (name: string) => `Activer ${name}`,
    actionsOf: (name: string) => `Actions pour ${name}`,
    remove: "Retirer",
    uninstall: "Désinstaller",
    update: "Mettre à jour",
    details: "Voir la fiche",
    openSkill: "Ouvrir SKILL.md",
    updateReady: "Mise à jour disponible",
    local: "Local",
    nothingOn: "Rien d’activé dans ce projet",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && plural(plugins, "plugin", "plugins"),
        skills && plural(skills, "skill", "skills"),
        servers && plural(servers, "serveur MCP", "serveurs MCP"),
      ].filter((part): part is string => Boolean(part));
      const one = plugins + skills + servers === 1;
      const said = servers || plugins ? (one ? "activé" : "activés") : one ? "activée" : "activées";
      return `${listFr(parts)} ${said} dans ce projet`;
    },
    plugin: "Plugin",
    skill: "Skill",
    connector: "Connecteur",
    mcp: "MCP",
    gonePlugin: "Son dossier est supprimé, ainsi que les valeurs enregistrées pour lui.",
    goneSkill: "Son dossier est supprimé avec tout son contenu.",
    goneServer: "Sa configuration est supprimée, variables d’environnement comprises.",
    envLine: (line: number) => `Variables d’environnement, ligne ${line} : écrivez CLÉ=valeur.`,
    envTwice: (key: string) => `Variables d’environnement : ${key} apparaît deux fois.`,
    hook: (event: string) => `Hook · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "Exécutable",
    badgeAnthropic: "Anthropic",
    badgePartner: "Officiel",
    badgeCommunity: "Communauté",
    badgeSkillsSh: "skills.sh",
    kindAll: "Tout",
    kindPlugins: "Plugins",
    kindSkills: "Skills",
    kindConnectors: "Connecteurs",
    sourceAll: "Toutes",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "Communauté",
    sourceSkillsSh: "skills.sh",
    seekMarket: "Rechercher dans le catalogue",
    seekMarketHint: (count: string) => `Rechercher parmi ${count} plugins, skills et connecteurs…`,
    seekMarketHintPlain: "Rechercher dans le catalogue…",
    sections: "Rubriques",
    discover: "Découvrir",
    everything: "Tout",
    kind: "Type",
    source: "Source",
    couldNotUpdate: (list: string) => `Impossible de mettre à jour ${list}`,
    loadingCatalogue: "Chargement du catalogue…",
    seekingSkillsSh: "Recherche aussi sur skills.sh…",
    catalogueOf: (when: string) => `Catalogue du ${when}`,
    refreshing: "Actualisation…",
    refresh: "Actualiser le catalogue",
    showMore: (left: string) => `Afficher plus · encore ${left}`,
    results: (count: number, shown: string, query: string) => `${count <= 1 ? `${shown} résultat` : `${shown} résultats`} pour « ${query} »`,
    listed: (count: number, shown: string) => (count <= 1 ? `${shown} fiche` : `${shown} fiches`),
    steps: "Fonctionnement des capacités",
    stepInstall: "Installez une fois",
    stepInstallSaid: "Téléchargée et figée sur une version.",
    stepEnable: "Activez par projet",
    stepEnableSaid: "Chaque projet n’utilise que ce que vous activez.",
    stepUse: "Utilisez-la en session",
    stepUseSaid: "Chargée dès votre prochain message.",
    startHere: "Pour commencer",
    startHereSaid: "Une sélection des plugins et skills d’Anthropic.",
    connectTools: "Connectez vos outils",
    connectToolsSaid: "Des connecteurs qui fonctionnent sans connexion.",
    seeAll: "Tout voir",
    seeAllOf: (name: string) => `Tout voir dans ${name}`,
    addCard: "Ajouter",
    adding: "Ajout…",
    installCard: "Installer",
    addTo: (title: string, project: string) => `Ajouter ${title} à ${project}`,
    installNamed: (title: string) => `Installer ${title}`,
    addHere: (project: string) => `Ajouter à ${project}`,
    addsTo: (project: string) => `S’ajoute à ${project}`,
    noProject: "Aucun projet ouvert : installation seulement",
    installedTag: "Installée",
    enabledTag: "Activée ici",
    tools: (count: number) => (count <= 1 ? `${count} outil` : `${count} outils`),
    installs: (shown: string) => `${shown} installations`,
    signIn: "Connexion requise",
    notInstallable: "Non installable depuis Sens",
    by: (author: string) => `par ${author}`,
    addFailed: (title: string, reason: string) => `Impossible d’ajouter ${title} : ${reason}`,
    downloading: "Téléchargement pour tout vous montrer…",
    installing: "Installation…",
    install: "Installer",
    whyLogin: "Il faut se connecter au service ; Sens ne peut pas encore le faire pour vous.",
    whyOrigin: "Cette source ne peut pas être installée depuis Sens.",
    viewSource: "Voir la source",
    openToEnable: "Ouvrez un projet pour l’activer",
    detailTabs: "Parties de la fiche",
    summary: "Aperçu",
    contents: "Contenu",
    runs: "Ce qu’elle exécute",
    toolsTitle: (count: number) => `Outils · ${count}`,
    skillsGroup: "Skills",
    commandsGroup: "Commandes",
    agentsGroup: "Agents",
    filesNav: "Fichiers",
    filesGroup: (count: number) => `Fichiers · ${count}`,
    andMore: (count: number) => `et ${count} de plus`,
    pickFile: "Choisissez un fichier pour le lire.",
    reading: "Lecture…",
    hooks: "Hooks",
    servers: "Serveurs MCP",
    executables: "Exécutables",
    lsp: "LSP",
    asks: "Ce qui vous sera demandé",
    signingIn: "Connexion",
    asksSignIn: "Demande de se connecter au service",
    optional: "facultatif",
    noCode: "N’exécute aucun code : seulement des instructions.",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && plural(hooks, "hook", "hooks"),
        servers && plural(servers, "serveur MCP", "serveurs MCP"),
        bins && plural(bins, "exécutable", "exécutables"),
        lsp && plural(lsp, "serveur de langage", "serveurs de langage"),
      ].filter((part): part is string => Boolean(part));
      return `Exécute du code sur votre ordinateur : ${listFr(parts)}.`;
    },
    runsRemote: "S’exécute sur les serveurs du fournisseur.",
    runsRemoteAt: (host: string) => `S’exécute sur les serveurs du fournisseur : ${host}.`,
    seeRuns: "Voir ce qu’elle exécute",
    journey: "Comment elle se connecte",
    jInstall: "Installer",
    jInstalled: (version: string) => (version ? `Installée · v${version}` : "Installée"),
    jNotInstalled: "Téléchargée une fois, figée sur cette version",
    jEnable: (project: string) => `Activer dans ${project}`,
    jEnableAny: "Activer dans un projet",
    jEnabled: "Activée",
    jOff: "Désactivée",
    jNoProject: "Ouvrez d’abord un projet",
    jUse: "Utiliser en session",
    jUsing: "Dès votre prochain message",
    jWaiting: "Une fois activée",
    create: "Créer",
    name: "Nom",
    skillNameNote: "Minuscules, chiffres et traits d’union, sans commencer par un trait d’union. 64 caractères au maximum.",
    description: "Description",
    instructions: "Instructions",
    serverNameNote: "Lettres, chiffres, traits d’union et tirets bas. 64 caractères au maximum.",
    command: "Commande",
    args: "Arguments",
    argsNote: "Un par ligne.",
    env: "Variables d’environnement",
    envNote: "CLÉ=valeur, une par ligne. Les valeurs ne sont plus affichées ensuite.",
    runsWarning: "Ceci exécute du code sur votre ordinateur quand l’agent l’utilise :",
    optionalNote: "Facultatif.",
    installTitle: (title: string) => `Installer ${title}`,
    chooseSkillFolder: "Choisissez le dossier de la skill",
    sectionNames: {
      code: "Code et développement",
      agents: "Agents et IA",
      data: "Données et bases de données",
      cloud: "Cloud et DevOps",
      security: "Sécurité",
      design: "Design et médias",
      productivity: "Productivité et documents",
      communication: "Communication",
      business: "Business et ventes",
      finance: "Finance",
      science: "Science et santé",
      learning: "Apprentissage",
      lifestyle: "Voyages et loisirs",
      other: "Autres",
    },
    sectionAbouts: {
      code: "Langages, tests, revues, Git et les outils autour de votre code.",
      agents: "Agents, mémoire, prompts et façons d’ajuster le travail de Claude.",
      data: "Bases de données, analytique, tableaux de bord et pipelines de données.",
      cloud: "Déploiement, hébergement, supervision et infrastructure.",
      security: "Analyse, conformité, secrets et accès.",
      design: "Interfaces, images, vidéo, diagrammes et sites web.",
      productivity: "Notes, documents, agendas et suivi de projets.",
      communication: "E-mail, chat, réunions et messages.",
      business: "Marketing, ventes, support, juridique et recrutement.",
      finance: "Paiements, comptabilité, investissement et crypto.",
      science: "Recherche, sciences de la vie, médecine et mathématiques.",
      learning: "Cours, tutorat et code expliqué.",
      lifestyle: "Voyages, repas, divertissement et services du quotidien.",
      other: "Ce qui n’entre dans aucune rubrique.",
    },
    sourceNames: {
      official: "Plugins officiels d’Anthropic",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "Plugins de la communauté vérifiés par Anthropic",
      skills: "Skills d’Anthropic",
      connectors: "Connecteurs d’Anthropic",
    },
  },
  de: {
    title: "Fähigkeiten",
    lede: "Plugins, Skills und Connectors, die Sens in deinen Sitzungen nutzen kann.",
    modes: "Ansicht",
    installedMode: "Installiert",
    exploreMode: "Entdecken",
    add: "Hinzufügen",
    addMenu: "Fähigkeit hinzufügen",
    createSkill: "Skill erstellen",
    importFolder: "Ordner importieren",
    addServer: "MCP-Server hinzufügen",
    unopened: "Öffne ein Projekt, um Fähigkeiten zu aktivieren.",
    loadsNote: "Der Agent lädt sie ab deiner nächsten Nachricht in diesem Projekt.",
    kindTabs: "Arten von Fähigkeiten",
    tabAll: "Alle",
    tabPlugins: "Plugins",
    tabSkills: "Skills",
    tabServers: "MCP",
    emptyAll: "Keine Fähigkeiten",
    emptyAllSaid: "Entdecke den Katalog, erstelle oder importiere einen Skill oder füge einen MCP-Server hinzu.",
    emptyPlugins: "Keine Plugins",
    emptyPluginsSaid: "Entdecke den Katalog, um eines zu installieren.",
    emptySkills: "Keine Skills",
    emptySkillsSaid: "Füge einen Skill hinzu, um dem Agenten wiederverwendbare Anweisungen zu geben.",
    emptyServers: "Keine MCP-Server",
    emptyServersSaid: "Füge einen MCP-Server hinzu, um dem Agenten neue Werkzeuge zu geben.",
    seekInstalled: "Skill, Plugin oder Server suchen",
    seekInstalledHint: "Skill, Plugin oder Server suchen…",
    nothingMatches: "Keine Treffer.",
    enabledIn: (project: string) => `Aktiv in ${project}`,
    groupOn: (project: string) => `Aktiv in ${project}`,
    groupOff: (project: string) => `Nicht aktiv in ${project}`,
    installedGroup: "Installiert",
    yourChoice: "Du entscheidest, was in jedem Projekt aktiv ist.",
    enableIn: (name: string, project: string) => `${name} in ${project} aktivieren`,
    enable: (name: string) => `${name} aktivieren`,
    actionsOf: (name: string) => `Aktionen für ${name}`,
    remove: "Entfernen",
    uninstall: "Deinstallieren",
    update: "Aktualisieren",
    details: "Details ansehen",
    openSkill: "SKILL.md öffnen",
    updateReady: "Update verfügbar",
    local: "Lokal",
    nothingOn: "In diesem Projekt ist nichts aktiv",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && plural(plugins, "Plugin", "Plugins"),
        skills && plural(skills, "Skill", "Skills"),
        servers && `${servers} MCP-Server`,
      ].filter((part): part is string => Boolean(part));
      return `${listDe(parts)} in diesem Projekt aktiv`;
    },
    plugin: "Plugin",
    skill: "Skill",
    connector: "Connector",
    mcp: "MCP",
    gonePlugin: "Sein Ordner wird gelöscht, samt der Werte, die du dafür gespeichert hast.",
    goneSkill: "Sein Ordner wird mit allem Inhalt gelöscht.",
    goneServer: "Seine Konfiguration wird gelöscht, Umgebungsvariablen eingeschlossen.",
    envLine: (line: number) => `Umgebungsvariablen, Zeile ${line}: schreibe SCHLÜSSEL=Wert.`,
    envTwice: (key: string) => `Umgebungsvariablen: ${key} kommt doppelt vor.`,
    hook: (event: string) => `Hook · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "Programm",
    badgeAnthropic: "Anthropic",
    badgePartner: "Offiziell",
    badgeCommunity: "Community",
    badgeSkillsSh: "skills.sh",
    kindAll: "Alle",
    kindPlugins: "Plugins",
    kindSkills: "Skills",
    kindConnectors: "Connectors",
    sourceAll: "Alle",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "Community",
    sourceSkillsSh: "skills.sh",
    seekMarket: "Katalog durchsuchen",
    seekMarketHint: (count: string) => `${count} Plugins, Skills und Connectors durchsuchen…`,
    seekMarketHintPlain: "Katalog durchsuchen…",
    sections: "Bereiche",
    discover: "Empfehlungen",
    everything: "Alle",
    kind: "Art",
    source: "Quelle",
    couldNotUpdate: (list: string) => `Aktualisierung fehlgeschlagen: ${list}`,
    loadingCatalogue: "Katalog wird geladen…",
    seekingSkillsSh: "Suche auch auf skills.sh…",
    catalogueOf: (when: string) => `Katalog vom ${when}`,
    refreshing: "Wird aktualisiert…",
    refresh: "Katalog aktualisieren",
    showMore: (left: string) => `Mehr anzeigen · noch ${left}`,
    results: (count: number, shown: string, query: string) => `${count === 1 ? "1 Treffer" : `${shown} Treffer`} für „${query}“`,
    listed: (count: number, shown: string) => (count === 1 ? "1 Eintrag" : `${shown} Einträge`),
    steps: "So funktionieren Fähigkeiten",
    stepInstall: "Einmal installieren",
    stepInstallSaid: "Heruntergeladen und auf eine Version festgelegt.",
    stepEnable: "Pro Projekt aktivieren",
    stepEnableSaid: "Jedes Projekt bekommt nur, was du aktivierst.",
    stepUse: "In Sitzungen nutzen",
    stepUseSaid: "Geladen ab deiner nächsten Nachricht.",
    startHere: "Für den Anfang",
    startHereSaid: "Ausgewählt aus den Plugins und Skills von Anthropic.",
    connectTools: "Verbinde deine Werkzeuge",
    connectToolsSaid: "Connectors, die ohne Anmeldung funktionieren.",
    seeAll: "Alle ansehen",
    seeAllOf: (name: string) => `Alle in ${name} ansehen`,
    addCard: "Hinzufügen",
    adding: "Wird hinzugefügt…",
    installCard: "Installieren",
    addTo: (title: string, project: string) => `${title} zu ${project} hinzufügen`,
    installNamed: (title: string) => `${title} installieren`,
    addHere: (project: string) => `Zu ${project} hinzufügen`,
    addsTo: (project: string) => `Wird zu ${project} hinzugefügt`,
    noProject: "Kein Projekt geöffnet: wird nur installiert",
    installedTag: "Installiert",
    enabledTag: "Hier aktiv",
    tools: (count: number) => (count === 1 ? "1 Werkzeug" : `${count} Werkzeuge`),
    installs: (shown: string) => `${shown} Installationen`,
    signIn: "Anmeldung nötig",
    notInstallable: "Nicht über Sens installierbar",
    by: (author: string) => `von ${author}`,
    addFailed: (title: string, reason: string) => `${title} konnte nicht hinzugefügt werden: ${reason}`,
    downloading: "Wird heruntergeladen, um dir alles zu zeigen…",
    installing: "Wird installiert…",
    install: "Installieren",
    whyLogin: "Es verlangt eine Anmeldung beim Dienst; das kann Sens noch nicht für dich erledigen.",
    whyOrigin: "Diese Quelle lässt sich nicht über Sens installieren.",
    viewSource: "Quelle ansehen",
    openToEnable: "Öffne ein Projekt, um es zu aktivieren",
    detailTabs: "Teile des Eintrags",
    summary: "Überblick",
    contents: "Inhalt",
    runs: "Was es ausführt",
    toolsTitle: (count: number) => `Werkzeuge · ${count}`,
    skillsGroup: "Skills",
    commandsGroup: "Befehle",
    agentsGroup: "Agenten",
    filesNav: "Dateien",
    filesGroup: (count: number) => `Dateien · ${count}`,
    andMore: (count: number) => `und ${count} weitere`,
    pickFile: "Wähle eine Datei aus, um sie zu lesen.",
    reading: "Wird gelesen…",
    hooks: "Hooks",
    servers: "MCP-Server",
    executables: "Programme",
    lsp: "LSP",
    asks: "Was es von dir wissen will",
    signingIn: "Anmeldung",
    asksSignIn: "Verlangt eine Anmeldung beim Dienst",
    optional: "optional",
    noCode: "Führt keinen Code aus: nur Anweisungen.",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && plural(hooks, "Hook", "Hooks"),
        servers && `${servers} MCP-Server`,
        bins && plural(bins, "Programm", "Programme"),
        lsp && plural(lsp, "Sprachserver", "Sprachserver"),
      ].filter((part): part is string => Boolean(part));
      return `Führt Code auf deinem Computer aus: ${listDe(parts)}.`;
    },
    runsRemote: "Läuft auf den Servern des Anbieters.",
    runsRemoteAt: (host: string) => `Läuft auf den Servern des Anbieters: ${host}.`,
    seeRuns: "Ansehen, was es ausführt",
    journey: "So wird es verbunden",
    jInstall: "Installieren",
    jInstalled: (version: string) => (version ? `Installiert · v${version}` : "Installiert"),
    jNotInstalled: "Einmal heruntergeladen, auf diese Version festgelegt",
    jEnable: (project: string) => `In ${project} aktivieren`,
    jEnableAny: "In einem Projekt aktivieren",
    jEnabled: "Aktiv",
    jOff: "Inaktiv",
    jNoProject: "Öffne zuerst ein Projekt",
    jUse: "In Sitzungen nutzen",
    jUsing: "Ab deiner nächsten Nachricht",
    jWaiting: "Sobald aktiviert",
    create: "Erstellen",
    name: "Name",
    skillNameNote: "Kleinbuchstaben, Ziffern und Bindestriche, ohne Bindestrich am Anfang. Höchstens 64 Zeichen.",
    description: "Beschreibung",
    instructions: "Anweisungen",
    serverNameNote: "Buchstaben, Ziffern, Binde- und Unterstriche. Höchstens 64 Zeichen.",
    command: "Befehl",
    args: "Argumente",
    argsNote: "Eines pro Zeile.",
    env: "Umgebungsvariablen",
    envNote: "SCHLÜSSEL=Wert, eine pro Zeile. Die Werte werden danach nicht mehr angezeigt.",
    runsWarning: "Das führt Code auf deinem Computer aus, wenn der Agent es nutzt:",
    optionalNote: "Optional.",
    installTitle: (title: string) => `${title} installieren`,
    chooseSkillFolder: "Wähle den Ordner des Skills",
    sectionNames: {
      code: "Code und Entwicklung",
      agents: "Agenten und KI",
      data: "Daten und Datenbanken",
      cloud: "Cloud und DevOps",
      security: "Sicherheit",
      design: "Design und Medien",
      productivity: "Produktivität und Dokumente",
      communication: "Kommunikation",
      business: "Business und Vertrieb",
      finance: "Finanzen",
      science: "Wissenschaft und Gesundheit",
      learning: "Lernen",
      lifestyle: "Reisen und Freizeit",
      other: "Sonstiges",
    },
    sectionAbouts: {
      code: "Sprachen, Tests, Reviews, Git und die Werkzeuge rund um deinen Code.",
      agents: "Agenten, Gedächtnis, Prompts und Einstellungen für Claudes Arbeitsweise.",
      data: "Datenbanken, Analysen, Dashboards und Datenpipelines.",
      cloud: "Deployment, Hosting, Monitoring und Infrastruktur.",
      security: "Scans, Compliance, Secrets und Zugriffe.",
      design: "Oberflächen, Bilder, Video, Diagramme und Websites.",
      productivity: "Notizen, Dokumente, Kalender und Projektverfolgung.",
      communication: "E-Mail, Chat, Meetings und Nachrichten.",
      business: "Marketing, Vertrieb, Support, Recht und Recruiting.",
      finance: "Zahlungen, Buchhaltung, Geldanlage und Krypto.",
      science: "Forschung, Biowissenschaften, Medizin und Mathematik.",
      learning: "Kurse, Nachhilfe und erklärter Code.",
      lifestyle: "Reisen, Essen, Unterhaltung und Alltagsdienste.",
      other: "Was in keinen Bereich passt.",
    },
    sourceNames: {
      official: "Offizielle Plugins von Anthropic",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "Von Anthropic geprüfte Community-Plugins",
      skills: "Skills von Anthropic",
      connectors: "Connectors von Anthropic",
    },
  },
  ja: {
    title: "機能",
    lede: "Sens がセッションで使えるプラグイン、スキル、コネクタです。",
    modes: "表示する内容",
    installedMode: "インストール済み",
    exploreMode: "見つける",
    add: "追加",
    addMenu: "機能を追加",
    createSkill: "スキルを作成",
    importFolder: "フォルダーをインポート",
    addServer: "MCP サーバーを追加",
    unopened: "機能を有効にするにはプロジェクトを開いてください。",
    loadsNote: "このプロジェクトでは、次のメッセージからエージェントが読み込みます。",
    kindTabs: "機能の種類",
    tabAll: "すべて",
    tabPlugins: "プラグイン",
    tabSkills: "スキル",
    tabServers: "MCP",
    emptyAll: "機能はありません",
    emptyAllSaid: "カタログを見るか、スキルを作成・インポートするか、MCP サーバーを追加してください。",
    emptyPlugins: "プラグインはありません",
    emptyPluginsSaid: "カタログからインストールできます。",
    emptySkills: "スキルはありません",
    emptySkillsSaid: "スキルを追加すると、エージェントに繰り返し使える指示を渡せます。",
    emptyServers: "MCP サーバーはありません",
    emptyServersSaid: "MCP サーバーを追加すると、エージェントに新しいツールを渡せます。",
    seekInstalled: "スキル、プラグイン、サーバーを検索",
    seekInstalledHint: "スキル、プラグイン、サーバーを検索…",
    nothingMatches: "一致するものはありません。",
    enabledIn: (project: string) => `${project} で有効`,
    groupOn: (project: string) => `${project} で有効`,
    groupOff: (project: string) => `${project} で無効`,
    installedGroup: "インストール済み",
    yourChoice: "有効にするものはプロジェクトごとに選べます。",
    enableIn: (name: string, project: string) => `${project} で ${name} を有効にする`,
    enable: (name: string) => `${name} を有効にする`,
    actionsOf: (name: string) => `${name} の操作`,
    remove: "削除",
    uninstall: "アンインストール",
    update: "アップデート",
    details: "詳細を表示",
    openSkill: "SKILL.md を開く",
    updateReady: "アップデートあり",
    local: "ローカル",
    nothingOn: "このプロジェクトで有効なものはありません",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && `プラグイン ${plugins} 個`,
        skills && `スキル ${skills} 個`,
        servers && `MCP サーバー ${servers} 個`,
      ].filter((part): part is string => Boolean(part));
      return `このプロジェクトで有効: ${parts.join("、")}`;
    },
    plugin: "プラグイン",
    skill: "スキル",
    connector: "コネクタ",
    mcp: "MCP",
    gonePlugin: "フォルダーと、このプラグイン用に保存した値が削除されます。",
    goneSkill: "フォルダーが中身ごと削除されます。",
    goneServer: "環境変数を含む設定が削除されます。",
    envLine: (line: number) => `環境変数の ${line} 行目は「キー=値」の形式で入力してください。`,
    envTwice: (key: string) => `環境変数: ${key} が重複しています。`,
    hook: (event: string) => `フック · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "実行ファイル",
    badgeAnthropic: "Anthropic",
    badgePartner: "公式",
    badgeCommunity: "コミュニティ",
    badgeSkillsSh: "skills.sh",
    kindAll: "すべて",
    kindPlugins: "プラグイン",
    kindSkills: "スキル",
    kindConnectors: "コネクタ",
    sourceAll: "すべて",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "コミュニティ",
    sourceSkillsSh: "skills.sh",
    seekMarket: "カタログを検索",
    seekMarketHint: (count: string) => `${count} 件のプラグイン、スキル、コネクタから検索…`,
    seekMarketHintPlain: "カタログを検索…",
    sections: "セクション",
    discover: "おすすめ",
    everything: "すべて",
    kind: "種類",
    source: "提供元",
    couldNotUpdate: (list: string) => `アップデートできませんでした: ${list}`,
    loadingCatalogue: "カタログを読み込んでいます…",
    seekingSkillsSh: "skills.sh も検索しています…",
    catalogueOf: (when: string) => `カタログ更新: ${when}`,
    refreshing: "更新中…",
    refresh: "カタログを更新",
    showMore: (left: string) => `さらに表示 · 残り ${left} 件`,
    results: (count: number, shown: string, query: string) => `「${query}」の検索結果 ${count === 1 ? "1" : shown} 件`,
    listed: (count: number, shown: string) => `${count === 1 ? "1" : shown} 件`,
    steps: "機能のしくみ",
    stepInstall: "インストールは一度だけ",
    stepInstallSaid: "ダウンロードしてバージョンを固定します。",
    stepEnable: "プロジェクトごとに有効化",
    stepEnableSaid: "各プロジェクトは有効にしたものだけを使います。",
    stepUse: "セッションで使う",
    stepUseSaid: "次のメッセージから読み込まれます。",
    startHere: "はじめに",
    startHereSaid: "Anthropic のプラグインとスキルから選びました。",
    connectTools: "ツールを接続",
    connectToolsSaid: "サインインなしで使えるコネクタです。",
    seeAll: "すべて見る",
    seeAllOf: (name: string) => `「${name}」をすべて見る`,
    addCard: "追加",
    adding: "追加中…",
    installCard: "インストール",
    addTo: (title: string, project: string) => `${title} を ${project} に追加`,
    installNamed: (title: string) => `${title} をインストール`,
    addHere: (project: string) => `${project} に追加`,
    addsTo: (project: string) => `${project} に追加されます`,
    noProject: "プロジェクトを開いていないため、インストールのみ行います",
    installedTag: "インストール済み",
    enabledTag: "ここで有効",
    tools: (count: number) => `ツール ${count} 個`,
    installs: (shown: string) => `${shown} 回インストール`,
    signIn: "サインインが必要",
    notInstallable: "Sens からはインストール不可",
    by: (author: string) => `提供: ${author}`,
    addFailed: (title: string, reason: string) => `${title} を追加できませんでした: ${reason}`,
    downloading: "すべてを表示するためにダウンロードしています…",
    installing: "インストール中…",
    install: "インストール",
    whyLogin: "サービスへのサインインが必要です。Sens はまだ代わりにサインインできません。",
    whyOrigin: "この提供元は Sens からインストールできません。",
    viewSource: "ソースを見る",
    openToEnable: "有効にするにはプロジェクトを開いてください",
    detailTabs: "掲載内容",
    summary: "概要",
    contents: "内容",
    runs: "実行するもの",
    toolsTitle: (count: number) => `ツール · ${count}`,
    skillsGroup: "スキル",
    commandsGroup: "コマンド",
    agentsGroup: "エージェント",
    filesNav: "ファイル",
    filesGroup: (count: number) => `ファイル · ${count}`,
    andMore: (count: number) => `ほか ${count} 件`,
    pickFile: "表示するファイルを選んでください。",
    reading: "読み込み中…",
    hooks: "フック",
    servers: "MCP サーバー",
    executables: "実行ファイル",
    lsp: "LSP",
    asks: "入力を求められる項目",
    signingIn: "サインイン",
    asksSignIn: "サービスへのサインインを求めます",
    optional: "任意",
    noCode: "コードは実行しません。指示のみです。",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && `フック ${hooks} 個`,
        servers && `MCP サーバー ${servers} 個`,
        bins && `実行ファイル ${bins} 個`,
        lsp && `言語サーバー ${lsp} 個`,
      ].filter((part): part is string => Boolean(part));
      return `このコンピューターでコードを実行します: ${parts.join("、")}。`;
    },
    runsRemote: "提供元のサーバーで実行されます。",
    runsRemoteAt: (host: string) => `提供元のサーバーで実行されます: ${host}。`,
    seeRuns: "実行するものを見る",
    journey: "導入の流れ",
    jInstall: "インストール",
    jInstalled: (version: string) => (version ? `インストール済み · v${version}` : "インストール済み"),
    jNotInstalled: "一度だけダウンロードし、このバージョンに固定します",
    jEnable: (project: string) => `${project} で有効にする`,
    jEnableAny: "プロジェクトで有効にする",
    jEnabled: "有効",
    jOff: "無効",
    jNoProject: "先にプロジェクトを開いてください",
    jUse: "セッションで使う",
    jUsing: "次のメッセージから",
    jWaiting: "有効にしたあと",
    create: "作成",
    name: "名前",
    skillNameNote: "英小文字、数字、ハイフンのみ。先頭にハイフンは使えません。64 文字まで。",
    description: "説明",
    instructions: "指示",
    serverNameNote: "英字、数字、ハイフン、アンダースコアのみ。64 文字まで。",
    command: "コマンド",
    args: "引数",
    argsNote: "1 行に 1 つ。",
    env: "環境変数",
    envNote: "「キー=値」の形式で 1 行に 1 つ。値は保存後に表示されません。",
    runsWarning: "エージェントが使うと、このコンピューターで次のコードが実行されます:",
    optionalNote: "任意。",
    installTitle: (title: string) => `${title} をインストール`,
    chooseSkillFolder: "スキルのフォルダーを選択",
    sectionNames: {
      code: "コードと開発",
      agents: "エージェントと AI",
      data: "データとデータベース",
      cloud: "クラウドと DevOps",
      security: "セキュリティ",
      design: "デザインとメディア",
      productivity: "生産性とドキュメント",
      communication: "コミュニケーション",
      business: "ビジネスと営業",
      finance: "ファイナンス",
      science: "科学と健康",
      learning: "学習",
      lifestyle: "旅行とライフスタイル",
      other: "その他",
    },
    sectionAbouts: {
      code: "言語、テスト、レビュー、Git など、コードまわりのツール。",
      agents: "エージェント、メモリ、プロンプトなど、Claude の動き方を整えるもの。",
      data: "データベース、分析、ダッシュボード、データパイプライン。",
      cloud: "デプロイ、ホスティング、監視、インフラ運用。",
      security: "スキャン、コンプライアンス、シークレット、アクセス管理。",
      design: "UI、画像、動画、図、Web サイト。",
      productivity: "メモ、ドキュメント、カレンダー、プロジェクト管理。",
      communication: "メール、チャット、会議、メッセージ。",
      business: "マーケティング、営業、サポート、法務、採用。",
      finance: "決済、会計、投資、暗号資産。",
      science: "研究、ライフサイエンス、医療、数学。",
      learning: "コース、個別指導、解説付きのコード。",
      lifestyle: "旅行、食事、エンターテインメント、日常のサービス。",
      other: "どのセクションにも当てはまらないもの。",
    },
    sourceNames: {
      official: "Anthropic 公式プラグイン",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "Anthropic が確認したコミュニティのプラグイン",
      skills: "Anthropic のスキル",
      connectors: "Anthropic のコネクタ",
    },
  },
  zh: {
    title: "能力",
    lede: "Sens 可在会话中使用的插件、技能和连接器。",
    modes: "显示内容",
    installedMode: "已安装",
    exploreMode: "探索",
    add: "添加",
    addMenu: "添加能力",
    createSkill: "创建技能",
    importFolder: "导入文件夹",
    addServer: "添加 MCP 服务器",
    unopened: "打开一个项目以启用能力。",
    loadsNote: "在此项目中，代理会从你的下一条消息开始加载它们。",
    kindTabs: "能力类型",
    tabAll: "全部",
    tabPlugins: "插件",
    tabSkills: "技能",
    tabServers: "MCP",
    emptyAll: "没有能力",
    emptyAllSaid: "探索目录，创建或导入技能，或添加 MCP 服务器。",
    emptyPlugins: "没有插件",
    emptyPluginsSaid: "在目录中找一个来安装。",
    emptySkills: "没有技能",
    emptySkillsSaid: "添加技能，为代理提供可复用的指令。",
    emptyServers: "没有 MCP 服务器",
    emptyServersSaid: "添加 MCP 服务器，为代理提供新工具。",
    seekInstalled: "搜索技能、插件或服务器",
    seekInstalledHint: "搜索技能、插件或服务器…",
    nothingMatches: "没有匹配项。",
    enabledIn: (project: string) => `已在 ${project} 中启用`,
    groupOn: (project: string) => `已在 ${project} 中启用`,
    groupOff: (project: string) => `未在 ${project} 中启用`,
    installedGroup: "已安装",
    yourChoice: "每个项目启用什么，由你决定。",
    enableIn: (name: string, project: string) => `在 ${project} 中启用 ${name}`,
    enable: (name: string) => `启用 ${name}`,
    actionsOf: (name: string) => `${name} 的操作`,
    remove: "移除",
    uninstall: "卸载",
    update: "更新",
    details: "查看详情",
    openSkill: "打开 SKILL.md",
    updateReady: "有可用更新",
    local: "本地",
    nothingOn: "此项目中没有已启用的项",
    tally: (plugins: number, skills: number, servers: number) => {
      const parts = [
        plugins && `${plugins} 个插件`,
        skills && `${skills} 个技能`,
        servers && `${servers} 个 MCP 服务器`,
      ].filter((part): part is string => Boolean(part));
      return `此项目中已启用：${parts.join("、")}`;
    },
    plugin: "插件",
    skill: "技能",
    connector: "连接器",
    mcp: "MCP",
    gonePlugin: "将删除它的文件夹，以及你为它保存的值。",
    goneSkill: "将删除它的文件夹及其中的所有内容。",
    goneServer: "将删除它的配置，包括环境变量。",
    envLine: (line: number) => `环境变量第 ${line} 行：请按“键=值”格式填写。`,
    envTwice: (key: string) => `环境变量：${key} 重复了。`,
    hook: (event: string) => `钩子 · ${event}`,
    serverPart: (name: string) => `MCP · ${name}`,
    executable: "可执行文件",
    badgeAnthropic: "Anthropic",
    badgePartner: "官方",
    badgeCommunity: "社区",
    badgeSkillsSh: "skills.sh",
    kindAll: "全部",
    kindPlugins: "插件",
    kindSkills: "技能",
    kindConnectors: "连接器",
    sourceAll: "全部",
    sourceAnthropic: "Anthropic",
    sourceCommunity: "社区",
    sourceSkillsSh: "skills.sh",
    seekMarket: "搜索目录",
    seekMarketHint: (count: string) => `在 ${count} 个插件、技能和连接器中搜索…`,
    seekMarketHintPlain: "搜索目录…",
    sections: "分区",
    discover: "发现",
    everything: "全部",
    kind: "类型",
    source: "来源",
    couldNotUpdate: (list: string) => `无法更新：${list}`,
    loadingCatalogue: "正在加载目录…",
    seekingSkillsSh: "也在 skills.sh 中搜索…",
    catalogueOf: (when: string) => `目录更新于 ${when}`,
    refreshing: "正在刷新…",
    refresh: "刷新目录",
    showMore: (left: string) => `显示更多 · 还有 ${left} 项`,
    results: (count: number, shown: string, query: string) => `“${query}”：${count === 1 ? "1" : shown} 个结果`,
    listed: (count: number, shown: string) => `${count === 1 ? "1" : shown} 项`,
    steps: "能力如何运作",
    stepInstall: "只需安装一次",
    stepInstallSaid: "下载并固定到某个版本。",
    stepEnable: "按项目启用",
    stepEnableSaid: "每个项目只使用你启用的内容。",
    stepUse: "在会话中使用",
    stepUseSaid: "从你的下一条消息开始加载。",
    startHere: "从这里开始",
    startHereSaid: "精选自 Anthropic 官方的插件和技能。",
    connectTools: "连接你的工具",
    connectToolsSaid: "无需登录即可使用的连接器。",
    seeAll: "查看全部",
    seeAllOf: (name: string) => `查看“${name}”中的全部`,
    addCard: "添加",
    adding: "正在添加…",
    installCard: "安装",
    addTo: (title: string, project: string) => `将 ${title} 添加到 ${project}`,
    installNamed: (title: string) => `安装 ${title}`,
    addHere: (project: string) => `添加到 ${project}`,
    addsTo: (project: string) => `将添加到 ${project}`,
    noProject: "未打开项目：仅安装",
    installedTag: "已安装",
    enabledTag: "已在此启用",
    tools: (count: number) => `${count} 个工具`,
    installs: (shown: string) => `${shown} 次安装`,
    signIn: "需要登录",
    notInstallable: "无法从 Sens 安装",
    by: (author: string) => `来自 ${author}`,
    addFailed: (title: string, reason: string) => `无法添加 ${title}：${reason}`,
    downloading: "正在下载，以便向你展示全部内容…",
    installing: "正在安装…",
    install: "安装",
    whyLogin: "它需要登录该服务；Sens 目前还不能替你完成。",
    whyOrigin: "此来源无法从 Sens 安装。",
    viewSource: "查看源代码",
    openToEnable: "打开一个项目以启用它",
    detailTabs: "条目内容",
    summary: "概览",
    contents: "内容",
    runs: "运行的内容",
    toolsTitle: (count: number) => `工具 · ${count}`,
    skillsGroup: "技能",
    commandsGroup: "命令",
    agentsGroup: "代理",
    filesNav: "文件",
    filesGroup: (count: number) => `文件 · ${count}`,
    andMore: (count: number) => `还有 ${count} 个`,
    pickFile: "选择要查看的文件。",
    reading: "正在读取…",
    hooks: "钩子",
    servers: "MCP 服务器",
    executables: "可执行文件",
    lsp: "LSP",
    asks: "需要你提供的信息",
    signingIn: "登录",
    asksSignIn: "需要登录该服务",
    optional: "可选",
    noCode: "不运行代码，仅包含指令。",
    runsLocal: (hooks: number, servers: number, bins: number, lsp: number) => {
      const parts = [
        hooks && `${hooks} 个钩子`,
        servers && `${servers} 个 MCP 服务器`,
        bins && `${bins} 个可执行文件`,
        lsp && `${lsp} 个语言服务器`,
      ].filter((part): part is string => Boolean(part));
      return `会在你的电脑上运行代码：${parts.join("、")}。`;
    },
    runsRemote: "在提供方的服务器上运行。",
    runsRemoteAt: (host: string) => `在提供方的服务器上运行：${host}。`,
    seeRuns: "查看运行的内容",
    journey: "如何接入",
    jInstall: "安装",
    jInstalled: (version: string) => (version ? `已安装 · v${version}` : "已安装"),
    jNotInstalled: "只下载一次，固定在此版本",
    jEnable: (project: string) => `在 ${project} 中启用`,
    jEnableAny: "在项目中启用",
    jEnabled: "已启用",
    jOff: "已停用",
    jNoProject: "请先打开一个项目",
    jUse: "在会话中使用",
    jUsing: "从你的下一条消息开始",
    jWaiting: "启用之后",
    create: "创建",
    name: "名称",
    skillNameNote: "小写字母、数字和连字符，不能以连字符开头。最多 64 个字符。",
    description: "描述",
    instructions: "指令",
    serverNameNote: "字母、数字、连字符和下划线。最多 64 个字符。",
    command: "命令",
    args: "参数",
    argsNote: "每行一个。",
    env: "环境变量",
    envNote: "“键=值”格式，每行一个。保存后不再显示这些值。",
    runsWarning: "代理使用它时，会在你的电脑上运行以下代码：",
    optionalNote: "可选。",
    installTitle: (title: string) => `安装 ${title}`,
    chooseSkillFolder: "选择技能所在的文件夹",
    sectionNames: {
      code: "代码与开发",
      agents: "代理与 AI",
      data: "数据与数据库",
      cloud: "云与 DevOps",
      security: "安全",
      design: "设计与媒体",
      productivity: "效率与文档",
      communication: "沟通",
      business: "商务与销售",
      finance: "金融",
      science: "科学与健康",
      learning: "学习",
      lifestyle: "旅行与生活",
      other: "其他",
    },
    sectionAbouts: {
      code: "语言、测试、评审、Git 以及代码相关的工具。",
      agents: "代理、记忆、提示词，以及调整 Claude 工作方式的工具。",
      data: "数据库、分析、仪表板和数据管道。",
      cloud: "部署、托管、监控和基础设施运维。",
      security: "扫描、合规、密钥和访问控制。",
      design: "界面、图片、视频、图表和网站。",
      productivity: "笔记、文档、日历和项目跟踪。",
      communication: "邮件、聊天、会议和消息。",
      business: "营销、销售、客服、法务和招聘。",
      finance: "支付、会计、投资和加密货币。",
      science: "科研、生命科学、医学和数学。",
      learning: "课程、辅导和讲解式代码。",
      lifestyle: "出行、餐饮、娱乐和日常服务。",
      other: "不属于以上任何分区的内容。",
    },
    sourceNames: {
      official: "Anthropic 官方插件",
      "knowledge-work": "Anthropic · Knowledge Work",
      "financial-services": "Anthropic · Financial Services",
      "life-sciences": "Anthropic · Life Sciences",
      community: "经 Anthropic 审核的社区插件",
      skills: "Anthropic 的技能",
      connectors: "Anthropic 的连接器",
    },
  },
});
