import { copy } from "./i18n";

export const shared = copy({
  en: {
    close: "Close",
    cancel: "Cancel",
    remove: (name: string) => `Remove ${name}`,
    retry: "Try again",
    open: "Open",
    copy: "Copy",
    copied: "Copied",
    yesterday: "yesterday",
    showAll: "Show all",
    noProject: "No project",
    newSession: "New session",
    ctrl: "Ctrl",
  },
  es: {
    close: "Cerrar",
    cancel: "Cancelar",
    remove: (name: string) => `Quitar ${name}`,
    retry: "Reintentar",
    open: "Abrir",
    copy: "Copiar",
    copied: "Copiado",
    yesterday: "ayer",
    showAll: "Mostrar todo",
    noProject: "Sin proyecto",
    newSession: "Sesión nueva",
    ctrl: "Ctrl",
  },
  fr: {
    close: "Fermer",
    cancel: "Annuler",
    remove: (name: string) => `Retirer ${name}`,
    retry: "Réessayer",
    open: "Ouvrir",
    copy: "Copier",
    copied: "Copié",
    yesterday: "hier",
    showAll: "Tout afficher",
    noProject: "Aucun projet",
    newSession: "Nouvelle session",
    ctrl: "Ctrl",
  },
  de: {
    close: "Schließen",
    cancel: "Abbrechen",
    remove: (name: string) => `${name} entfernen`,
    retry: "Erneut versuchen",
    open: "Öffnen",
    copy: "Kopieren",
    copied: "Kopiert",
    yesterday: "gestern",
    showAll: "Alles anzeigen",
    noProject: "Kein Projekt",
    newSession: "Neue Sitzung",
    ctrl: "Strg",
  },
  ja: {
    close: "閉じる",
    cancel: "キャンセル",
    remove: (name: string) => `${name} を削除`,
    retry: "再試行",
    open: "開く",
    copy: "コピー",
    copied: "コピーしました",
    yesterday: "昨日",
    showAll: "すべて表示",
    noProject: "プロジェクトなし",
    newSession: "新しいセッション",
    ctrl: "Ctrl",
  },
  zh: {
    close: "关闭",
    cancel: "取消",
    remove: (name: string) => `移除 ${name}`,
    retry: "重试",
    open: "打开",
    copy: "复制",
    copied: "已复制",
    yesterday: "昨天",
    showAll: "显示全部",
    noProject: "无项目",
    newSession: "新会话",
    ctrl: "Ctrl",
  },
});

export const units = copy({
  en: {
    seconds: (value: string) => `${value} s`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} min ${seconds} s` : `${minutes} min`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} h ${minutes} min` : `${hours} h`),
    bytes: (size: string) => `${size} B`,
    kilobytes: (size: string) => `${size} KB`,
    megabytes: (size: string) => `${size} MB`,
  },
  es: {
    seconds: (value: string) => `${value} s`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} min ${seconds} s` : `${minutes} min`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} h ${minutes} min` : `${hours} h`),
    bytes: (size: string) => `${size} B`,
    kilobytes: (size: string) => `${size} KB`,
    megabytes: (size: string) => `${size} MB`,
  },
  fr: {
    seconds: (value: string) => `${value} s`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} min ${seconds} s` : `${minutes} min`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} h ${minutes} min` : `${hours} h`),
    bytes: (size: string) => `${size} o`,
    kilobytes: (size: string) => `${size} Ko`,
    megabytes: (size: string) => `${size} Mo`,
  },
  de: {
    seconds: (value: string) => `${value} s`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} min ${seconds} s` : `${minutes} min`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} h ${minutes} min` : `${hours} h`),
    bytes: (size: string) => `${size} B`,
    kilobytes: (size: string) => `${size} KB`,
    megabytes: (size: string) => `${size} MB`,
  },
  ja: {
    seconds: (value: string) => `${value} 秒`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} 分 ${seconds} 秒` : `${minutes} 分`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} 時間 ${minutes} 分` : `${hours} 時間`),
    bytes: (size: string) => `${size} B`,
    kilobytes: (size: string) => `${size} KB`,
    megabytes: (size: string) => `${size} MB`,
  },
  zh: {
    seconds: (value: string) => `${value} 秒`,
    minutes: (minutes: number, seconds: number) => (seconds ? `${minutes} 分 ${seconds} 秒` : `${minutes} 分钟`),
    hours: (hours: number, minutes: number) => (minutes ? `${hours} 小时 ${minutes} 分钟` : `${hours} 小时`),
    bytes: (size: string) => `${size} B`,
    kilobytes: (size: string) => `${size} KB`,
    megabytes: (size: string) => `${size} MB`,
  },
});

export const looks = copy({
  en: { mode: "Mode", color: "Color", language: "Language", dark: "Dark", light: "Light", system: "System", signal: "Signal", ice: "Ice", iris: "Iris", rose: "Rose", neutral: "Neutral" },
  es: { mode: "Modo", color: "Color", language: "Idioma", dark: "Oscuro", light: "Claro", system: "Sistema", signal: "Señal", ice: "Hielo", iris: "Iris", rose: "Rosa", neutral: "Neutro" },
  fr: { mode: "Mode", color: "Couleur", language: "Langue", dark: "Sombre", light: "Clair", system: "Système", signal: "Signal", ice: "Glace", iris: "Iris", rose: "Rose", neutral: "Neutre" },
  de: { mode: "Modus", color: "Farbe", language: "Sprache", dark: "Dunkel", light: "Hell", system: "System", signal: "Signal", ice: "Eis", iris: "Iris", rose: "Rosa", neutral: "Neutral" },
  ja: { mode: "モード", color: "カラー", language: "言語", dark: "ダーク", light: "ライト", system: "システム", signal: "シグナル", ice: "アイス", iris: "アイリス", rose: "ローズ", neutral: "ニュートラル" },
  zh: { mode: "模式", color: "颜色", language: "语言", dark: "深色", light: "浅色", system: "跟随系统", signal: "信号", ice: "冰蓝", iris: "鸢尾", rose: "玫瑰", neutral: "中性" },
});

export const code = copy({
  en: {
    code: "code",
    console: "console",
    text: "text",
    allLines: (count: number) => `Show all ${count} lines`,
    moreLines: (count: number) => (count === 1 ? "show 1 more line" : `show ${count} more lines`),
  },
  es: {
    code: "código",
    console: "consola",
    text: "texto",
    allLines: (count: number) => `Mostrar las ${count} líneas`,
    moreLines: (count: number) => (count === 1 ? "mostrar 1 línea más" : `mostrar ${count} líneas más`),
  },
  fr: {
    code: "code",
    console: "console",
    text: "texte",
    allLines: (count: number) => `Afficher les ${count} lignes`,
    moreLines: (count: number) => (count === 1 ? "afficher 1 ligne de plus" : `afficher ${count} lignes de plus`),
  },
  de: {
    code: "Code",
    console: "Konsole",
    text: "Text",
    allLines: (count: number) => `Alle ${count} Zeilen anzeigen`,
    moreLines: (count: number) => (count === 1 ? "1 weitere Zeile anzeigen" : `${count} weitere Zeilen anzeigen`),
  },
  ja: {
    code: "コード",
    console: "コンソール",
    text: "テキスト",
    allLines: (count: number) => `${count} 行すべて表示`,
    moreLines: (count: number) => `さらに ${count} 行を表示`,
  },
  zh: {
    code: "代码",
    console: "控制台",
    text: "文本",
    allLines: (count: number) => `显示全部 ${count} 行`,
    moreLines: (count: number) => `再显示 ${count} 行`,
  },
});
