// Serializes the project dependency graph into standard graph-exchange formats so it can
// be opened in external tools: GEXF (Gephi), GraphML (Gephi/yEd/Cytoscape), DOT (Graphviz),
// JSON (D3/Cytoscape.js) and a CSV edge list (Gephi/Excel). Everything here is pure — no I/O —
// so the serializers are unit-tested directly and stay reusable (e.g. a future CLI command).

import type { ProjectIndex, SymbolInfo } from "../types.js";

export interface GraphNode {
  id: string;
  label: string;
  symbols: number;
  exported: number;
  dead: number;
}
export interface GraphLink {
  source: string;
  target: string;
}
export interface GraphData {
  nodes: GraphNode[];
  links: GraphLink[];
}

// The flat file-level dependency graph: one node per indexed file (with symbol / export /
// dead-code counts) and one edge per import that lands on another indexed file. Takes the
// dead-code list as an argument so callers that already computed it don't pay for it twice.
export function buildGraph(index: ProjectIndex, dead: SymbolInfo[]): GraphData {
  const deadByFile = new Map<string, number>();
  for (const d of dead) deadByFile.set(d.file, (deadByFile.get(d.file) ?? 0) + 1);

  const symByFile = new Map<string, number>();
  const expByFile = new Map<string, number>();
  for (const s of index.symbols) {
    symByFile.set(s.file, (symByFile.get(s.file) ?? 0) + 1);
    if (s.exported) expByFile.set(s.file, (expByFile.get(s.file) ?? 0) + 1);
  }

  const nodes: GraphNode[] = index.files.map((f) => ({
    id: f.path,
    label: f.path.split("/").pop() ?? f.path,
    symbols: symByFile.get(f.path) ?? 0,
    exported: expByFile.get(f.path) ?? 0,
    dead: deadByFile.get(f.path) ?? 0,
  }));

  const fileSet = new Set(index.files.map((f) => f.path));
  const seen = new Set<string>();
  const links: GraphLink[] = [];
  for (const imp of index.imports) {
    if (!fileSet.has(imp.to) || imp.from === imp.to) continue;
    const key = `${imp.from}->${imp.to}`;
    if (seen.has(key)) continue;
    seen.add(key);
    links.push({ source: imp.from, target: imp.to });
  }

  return { nodes, links };
}

export const EXPORT_FORMATS = ["gexf", "graphml", "dot", "json", "csv"] as const;
export type ExportFormat = (typeof EXPORT_FORMATS)[number];

export function isExportFormat(v: string): v is ExportFormat {
  return (EXPORT_FORMATS as readonly string[]).includes(v);
}

export interface SerializedGraph {
  body: string;
  mime: string;
  filename: string;
}

const xmlEscape = (s: string): string =>
  s.replace(/[&<>"']/g, (c) =>
    c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : c === '"' ? "&quot;" : "&apos;",
  );

// Graphviz quoted-id / label: escape backslash and double-quote.
const dotEscape = (s: string): string => s.replace(/["\\]/g, "\\$&");

// RFC-4180: quote fields containing comma, quote or newline; double the inner quotes.
const csvField = (s: string): string =>
  /[",\r\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;

function toGEXF(graph: GraphData, project: string): string {
  const out: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<gexf xmlns="http://gexf.net/1.3" version="1.3">',
    `  <meta><creator>sens</creator><description>${xmlEscape(project)} dependency graph</description></meta>`,
    '  <graph mode="static" defaultedgetype="directed">',
    '    <attributes class="node">',
    '      <attribute id="0" title="path" type="string"/>',
    '      <attribute id="1" title="symbols" type="integer"/>',
    '      <attribute id="2" title="exported" type="integer"/>',
    '      <attribute id="3" title="dead" type="integer"/>',
    "    </attributes>",
    "    <nodes>",
  ];
  for (const n of graph.nodes) {
    out.push(
      `      <node id="${xmlEscape(n.id)}" label="${xmlEscape(n.label)}">` +
        `<attvalues>` +
        `<attvalue for="0" value="${xmlEscape(n.id)}"/>` +
        `<attvalue for="1" value="${n.symbols}"/>` +
        `<attvalue for="2" value="${n.exported}"/>` +
        `<attvalue for="3" value="${n.dead}"/>` +
        `</attvalues></node>`,
    );
  }
  out.push("    </nodes>", "    <edges>");
  graph.links.forEach((l, i) => {
    out.push(`      <edge id="${i}" source="${xmlEscape(l.source)}" target="${xmlEscape(l.target)}"/>`);
  });
  out.push("    </edges>", "  </graph>", "</gexf>");
  return out.join("\n");
}

function toGraphML(graph: GraphData, project: string): string {
  const out: string[] = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<graphml xmlns="http://graphml.graphdrawing.org/xmlns">',
    `  <!-- ${xmlEscape(project)} dependency graph, generated by sens -->`,
    '  <key id="label" for="node" attr.name="label" attr.type="string"/>',
    '  <key id="symbols" for="node" attr.name="symbols" attr.type="int"/>',
    '  <key id="exported" for="node" attr.name="exported" attr.type="int"/>',
    '  <key id="dead" for="node" attr.name="dead" attr.type="int"/>',
    '  <graph edgedefault="directed">',
  ];
  for (const n of graph.nodes) {
    out.push(
      `    <node id="${xmlEscape(n.id)}">` +
        `<data key="label">${xmlEscape(n.label)}</data>` +
        `<data key="symbols">${n.symbols}</data>` +
        `<data key="exported">${n.exported}</data>` +
        `<data key="dead">${n.dead}</data>` +
        `</node>`,
    );
  }
  graph.links.forEach((l, i) => {
    out.push(`    <edge id="e${i}" source="${xmlEscape(l.source)}" target="${xmlEscape(l.target)}"/>`);
  });
  out.push("  </graph>", "</graphml>");
  return out.join("\n");
}

function toDOT(graph: GraphData): string {
  const out: string[] = ["digraph sens {", "  graph [overlap=false];", "  node [shape=ellipse];"];
  for (const n of graph.nodes) {
    out.push(`  "${dotEscape(n.id)}" [label="${dotEscape(n.label)}"];`);
  }
  for (const l of graph.links) {
    out.push(`  "${dotEscape(l.source)}" -> "${dotEscape(l.target)}";`);
  }
  out.push("}");
  return out.join("\n");
}

function toJSON(graph: GraphData, project: string): string {
  return JSON.stringify({ project, nodes: graph.nodes, links: graph.links }, null, 2);
}

// Gephi-importable directed edge list. Isolated nodes (no edges) don't appear here — the
// richer formats above carry every node with its attributes.
function toCSV(graph: GraphData): string {
  const out: string[] = ["Source,Target,Type"];
  for (const l of graph.links) {
    out.push(`${csvField(l.source)},${csvField(l.target)},Directed`);
  }
  return out.join("\n");
}

export function serializeGraph(
  format: ExportFormat,
  graph: GraphData,
  project: string,
): SerializedGraph {
  const stem = `${(project || "project").replace(/[^\w.-]+/g, "-")}-graph`;
  switch (format) {
    case "gexf":
      return { body: toGEXF(graph, project), mime: "application/gexf+xml; charset=utf-8", filename: `${stem}.gexf` };
    case "graphml":
      return { body: toGraphML(graph, project), mime: "application/graphml+xml; charset=utf-8", filename: `${stem}.graphml` };
    case "dot":
      return { body: toDOT(graph), mime: "text/vnd.graphviz; charset=utf-8", filename: `${stem}.dot` };
    case "json":
      return { body: toJSON(graph, project), mime: "application/json; charset=utf-8", filename: `${stem}.json` };
    case "csv":
      return { body: toCSV(graph), mime: "text/csv; charset=utf-8", filename: `${stem}-edges.csv` };
  }
}
