import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    typing: "Search or type an address",
    address: "Address or project page",
    openOutside: "Open in your browser",
    back: "Back",
    forward: "Forward",
    reload: "Reload",
    width: "Width",
    auto: "Auto",
    console: "Console",
    waiting: "Search the web or type an address: a website, your local server (localhost:5173) or a project page (index.html).",
    onlyWeb: "The browser only opens http and https addresses.",
  },
  es: {
    typing: "Busca o escribe una dirección",
    address: "Dirección o página del proyecto",
    openOutside: "Abrir en el navegador",
    back: "Atrás",
    forward: "Adelante",
    reload: "Recargar",
    width: "Ancho",
    auto: "Auto",
    console: "Consola",
    waiting: "Busca en la web o escribe una dirección: una web, tu servidor local (localhost:5173) o una página del proyecto (index.html).",
    onlyWeb: "El navegador solo abre direcciones http y https.",
  },
  fr: {
    typing: "Recherchez ou saisissez une adresse",
    address: "Adresse ou page du projet",
    openOutside: "Ouvrir dans votre navigateur",
    back: "Précédent",
    forward: "Suivant",
    reload: "Actualiser",
    width: "Largeur",
    auto: "Auto",
    console: "Console",
    waiting: "Recherchez sur le Web ou saisissez une adresse : un site, votre serveur local (localhost:5173) ou une page du projet (index.html).",
    onlyWeb: "Le navigateur n’ouvre que les adresses http et https.",
  },
  de: {
    typing: "Suchen oder Adresse eingeben",
    address: "Adresse oder Projektseite",
    openOutside: "Im Standardbrowser öffnen",
    back: "Zurück",
    forward: "Vorwärts",
    reload: "Neu laden",
    width: "Breite",
    auto: "Auto",
    console: "Konsole",
    waiting: "Durchsuche das Web oder gib eine Adresse ein: eine Website, deinen lokalen Server (localhost:5173) oder eine Seite des Projekts (index.html).",
    onlyWeb: "Der Browser öffnet nur http- und https-Adressen.",
  },
  ja: {
    typing: "検索またはアドレスを入力",
    address: "アドレスまたはプロジェクトのページ",
    openOutside: "既定のブラウザーで開く",
    back: "戻る",
    forward: "進む",
    reload: "再読み込み",
    width: "幅",
    auto: "自動",
    console: "コンソール",
    waiting: "Web を検索するか、アドレスを入力してください。Web サイト、ローカルサーバー（localhost:5173）、プロジェクトのページ（index.html）を開けます。",
    onlyWeb: "ブラウザーで開けるのは http と https のアドレスだけです。",
  },
  zh: {
    typing: "搜索或输入地址",
    address: "地址或项目页面",
    openOutside: "在默认浏览器中打开",
    back: "后退",
    forward: "前进",
    reload: "重新加载",
    width: "宽度",
    auto: "自动",
    console: "控制台",
    waiting: "搜索网页或输入地址：网站、本地服务器（localhost:5173）或项目页面（index.html）。",
    onlyWeb: "浏览器只能打开 http 和 https 地址。",
  },
});
