import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    title: "Artifacts",
    lead: "Pictures, files and links your sessions leave behind.",
    unopened: "Open a project to see its artifacts.",
    note: "The list below covers all your projects.",
    kindsLabel: "Artifact types",
    search: "Search artifacts",
    searching: "Search artifacts…",
    foot: "Artifacts are saved in .sens/artifacts, inside your project.",
    emptyLead: "No artifacts",
    emptySaid: "Pictures, files and links will appear here as your sessions make them.",
    noMatch: "Nothing matches.",
    noSession: "no session",
    openSession: (title: string) => `Open the session · ${title}`,
    untitled: "Untitled session",
    tabs: { all: "All", image: "Pictures", file: "Files", link: "Links" },
    kinds: { image: "Picture", file: "File", link: "Link" },
    kept: (count: number) => (count === 1 ? "1 artifact in this project" : `${count} artifacts in this project`),
    keptNone: "No artifacts in this project yet",
  },
  es: {
    title: "Artefactos",
    lead: "Imágenes, ficheros y enlaces que dejan tus sesiones.",
    unopened: "Abre un proyecto para ver los suyos.",
    note: "La lista de abajo incluye los de todos tus proyectos.",
    kindsLabel: "Tipos de artefacto",
    search: "Buscar un artefacto",
    searching: "Buscar un artefacto…",
    foot: "Los artefactos se guardan en .sens/artifacts, dentro de tu proyecto.",
    emptyLead: "No hay artefactos",
    emptySaid: "Las imágenes, ficheros y enlaces aparecerán aquí según los produzcan las sesiones.",
    noMatch: "Nada coincide.",
    noSession: "sin sesión",
    openSession: (title: string) => `Abrir la sesión · ${title}`,
    untitled: "Sesión sin título",
    tabs: { all: "Todo", image: "Imágenes", file: "Ficheros", link: "Enlaces" },
    kinds: { image: "Imagen", file: "Fichero", link: "Enlace" },
    kept: (count: number) => (count === 1 ? "1 artefacto de este proyecto" : `${count} artefactos de este proyecto`),
    keptNone: "Todavía no hay artefactos en este proyecto",
  },
  fr: {
    title: "Artefacts",
    lead: "Les images, fichiers et liens laissés par vos sessions.",
    unopened: "Ouvrez un projet pour voir ses artefacts.",
    note: "La liste ci-dessous couvre tous vos projets.",
    kindsLabel: "Types d’artefact",
    search: "Rechercher un artefact",
    searching: "Rechercher un artefact…",
    foot: "Les artefacts sont enregistrés dans .sens/artifacts, au sein de votre projet.",
    emptyLead: "Aucun artefact",
    emptySaid: "Les images, fichiers et liens apparaîtront ici à mesure que vos sessions les produisent.",
    noMatch: "Aucun résultat.",
    noSession: "sans session",
    openSession: (title: string) => `Ouvrir la session · ${title}`,
    untitled: "Session sans titre",
    tabs: { all: "Tout", image: "Images", file: "Fichiers", link: "Liens" },
    kinds: { image: "Image", file: "Fichier", link: "Lien" },
    kept: (count: number) => (count <= 1 ? `${count} artefact dans ce projet` : `${count} artefacts dans ce projet`),
    keptNone: "Aucun artefact dans ce projet pour l’instant",
  },
  de: {
    title: "Artefakte",
    lead: "Bilder, Dateien und Links, die deine Sitzungen hinterlassen.",
    unopened: "Öffne ein Projekt, um seine Artefakte zu sehen.",
    note: "Die Liste unten umfasst alle deine Projekte.",
    kindsLabel: "Artefaktarten",
    search: "Artefakt suchen",
    searching: "Artefakt suchen…",
    foot: "Artefakte werden in .sens/artifacts in deinem Projekt gespeichert.",
    emptyLead: "Keine Artefakte",
    emptySaid: "Bilder, Dateien und Links erscheinen hier, sobald deine Sitzungen sie erzeugen.",
    noMatch: "Keine Treffer.",
    noSession: "ohne Sitzung",
    openSession: (title: string) => `Sitzung öffnen · ${title}`,
    untitled: "Sitzung ohne Titel",
    tabs: { all: "Alle", image: "Bilder", file: "Dateien", link: "Links" },
    kinds: { image: "Bild", file: "Datei", link: "Link" },
    kept: (count: number) => (count === 1 ? "1 Artefakt in diesem Projekt" : `${count} Artefakte in diesem Projekt`),
    keptNone: "Noch keine Artefakte in diesem Projekt",
  },
  ja: {
    title: "アーティファクト",
    lead: "セッションが残した画像、ファイル、リンクです。",
    unopened: "プロジェクトを開くと、そのアーティファクトが表示されます。",
    note: "下の一覧にはすべてのプロジェクトのものが含まれます。",
    kindsLabel: "アーティファクトの種類",
    search: "アーティファクトを検索",
    searching: "アーティファクトを検索…",
    foot: "アーティファクトはプロジェクト内の .sens/artifacts に保存されます。",
    emptyLead: "アーティファクトはありません",
    emptySaid: "セッションが作成した画像、ファイル、リンクがここに表示されます。",
    noMatch: "一致するものはありません。",
    noSession: "セッションなし",
    openSession: (title: string) => `セッションを開く · ${title}`,
    untitled: "無題のセッション",
    tabs: { all: "すべて", image: "画像", file: "ファイル", link: "リンク" },
    kinds: { image: "画像", file: "ファイル", link: "リンク" },
    kept: (count: number) => `このプロジェクトのアーティファクト ${count} 件`,
    keptNone: "このプロジェクトにはまだアーティファクトがありません",
  },
  zh: {
    title: "工件",
    lead: "你的会话留下的图片、文件和链接。",
    unopened: "打开一个项目即可查看它的工件。",
    note: "下方列表包含你所有项目的工件。",
    kindsLabel: "工件类型",
    search: "搜索工件",
    searching: "搜索工件…",
    foot: "工件保存在项目内的 .sens/artifacts 中。",
    emptyLead: "没有工件",
    emptySaid: "会话生成的图片、文件和链接会显示在这里。",
    noMatch: "没有匹配项。",
    noSession: "无会话",
    openSession: (title: string) => `打开会话 · ${title}`,
    untitled: "无标题会话",
    tabs: { all: "全部", image: "图片", file: "文件", link: "链接" },
    kinds: { image: "图片", file: "文件", link: "链接" },
    kept: (count: number) => `此项目有 ${count} 个工件`,
    keptNone: "此项目还没有工件",
  },
});
