import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    closePane: "Close this pane",
    closeNamed: (title: string) => `Close ${title}`,
    divider: "Split between the two sessions",
    dividerHint: "Drag to resize · double-click to even out",
    dropOpen: "Drop to open it here",
    dropReplace: (leaving: string) => `Drop to replace “${leaving}”`,
    dropSame: "Already open here",
    dropNarrow: "Widen the window to see two sessions at once",
  },
  es: {
    closePane: "Cerrar este panel",
    closeNamed: (title: string) => `Cerrar ${title}`,
    divider: "Reparto entre las dos sesiones",
    dividerHint: "Arrastra para repartir · doble clic para igualar",
    dropOpen: "Suelta para abrirla aquí",
    dropReplace: (leaving: string) => `Suelta para ponerla en lugar de «${leaving}»`,
    dropSame: "Ya está abierta aquí",
    dropNarrow: "Ensancha la ventana para ver dos sesiones a la vez",
  },
  fr: {
    closePane: "Fermer ce panneau",
    closeNamed: (title: string) => `Fermer ${title}`,
    divider: "Répartition entre les deux sessions",
    dividerHint: "Faites glisser pour répartir · double-cliquez pour égaliser",
    dropOpen: "Relâchez pour l’ouvrir ici",
    dropReplace: (leaving: string) => `Relâchez pour remplacer « ${leaving} »`,
    dropSame: "Déjà ouverte ici",
    dropNarrow: "Élargissez la fenêtre pour voir deux sessions à la fois",
  },
  de: {
    closePane: "Diesen Bereich schließen",
    closeNamed: (title: string) => `${title} schließen`,
    divider: "Aufteilung zwischen den beiden Sitzungen",
    dividerHint: "Ziehen zum Aufteilen · Doppelklick zum Angleichen",
    dropOpen: "Loslassen, um sie hier zu öffnen",
    dropReplace: (leaving: string) => `Loslassen, um „${leaving}“ zu ersetzen`,
    dropSame: "Hier bereits geöffnet",
    dropNarrow: "Mach das Fenster breiter, um zwei Sitzungen gleichzeitig zu sehen",
  },
  ja: {
    closePane: "このパネルを閉じる",
    closeNamed: (title: string) => `${title} を閉じる`,
    divider: "2 つのセッションの境界",
    dividerHint: "ドラッグで幅を調整 · ダブルクリックで均等に",
    dropOpen: "ドロップしてここで開く",
    dropReplace: (leaving: string) => `ドロップして「${leaving}」と入れ替え`,
    dropSame: "すでにここで開いています",
    dropNarrow: "2 つのセッションを並べて表示するには、ウィンドウを広げてください",
  },
  zh: {
    closePane: "关闭此面板",
    closeNamed: (title: string) => `关闭 ${title}`,
    divider: "两个会话之间的分隔条",
    dividerHint: "拖动以调整 · 双击以均分",
    dropOpen: "松开以在此打开",
    dropReplace: (leaving: string) => `松开以替换“${leaving}”`,
    dropSame: "已在此处打开",
    dropNarrow: "加宽窗口即可同时查看两个会话",
  },
});
