import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    terminal: "Terminal",
    terminals: "Terminals",
    closeThis: "Close this terminal",
    closeNamed: (name: string) => `Close terminal ${name}`,
    newIn: (folder: string) => `New terminal in ${folder}`,
    newOne: "New terminal",
    shareTitle: "Add the selection to the message, or what is on screen when nothing is selected",
    share: "Add to message",
    opening: "Opening the terminal…",
    none: "No terminal is open.",
    openIn: (folder: string) => `Open one in ${folder}`,
    openOne: "Open one",
    closed: "The terminal closed.",
    exited: (code: number) => `The process exited with code ${code}.`,
    noneHere: "No terminal is open in this session’s folder.",
    noSuch: (id: number, open: string) => `There is no terminal ${id}. Open: ${open}.`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `Terminal ${id} · ${shell} in ${root || "the home folder"}${ended ? " · the process has ended" : ""}`,
    open: (listed: string) => `Open: ${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name} (${shell}${ended ? ", ended" : ""})`,
    empty: "(nothing on screen)",
  },
  es: {
    terminal: "Terminal",
    terminals: "Terminales",
    closeThis: "Cerrar esta terminal",
    closeNamed: (name: string) => `Cerrar la terminal ${name}`,
    newIn: (folder: string) => `Nueva terminal en ${folder}`,
    newOne: "Nueva terminal",
    shareTitle: "Añadir al mensaje lo seleccionado, o lo que se ve si no hay selección",
    share: "Añadir al mensaje",
    opening: "Abriendo la terminal…",
    none: "No hay ninguna terminal abierta.",
    openIn: (folder: string) => `Abrir una en ${folder}`,
    openOne: "Abrir una",
    closed: "La terminal se cerró.",
    exited: (code: number) => `El proceso terminó con el código ${code}.`,
    noneHere: "No hay ninguna terminal abierta en la carpeta de esta sesión.",
    noSuch: (id: number, open: string) => `No hay ninguna terminal ${id}. Abiertas: ${open}.`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `Terminal ${id} · ${shell} en ${root || "la carpeta de usuario"}${ended ? " · el proceso ya terminó" : ""}`,
    open: (listed: string) => `Abiertas: ${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name} (${shell}${ended ? ", terminada" : ""})`,
    empty: "(no hay nada en pantalla)",
  },
  fr: {
    terminal: "Terminal",
    terminals: "Terminaux",
    closeThis: "Fermer ce terminal",
    closeNamed: (name: string) => `Fermer le terminal ${name}`,
    newIn: (folder: string) => `Nouveau terminal dans ${folder}`,
    newOne: "Nouveau terminal",
    shareTitle: "Ajouter la sélection au message, ou ce qui est affiché s’il n’y a pas de sélection",
    share: "Ajouter au message",
    opening: "Ouverture du terminal…",
    none: "Aucun terminal n’est ouvert.",
    openIn: (folder: string) => `En ouvrir un dans ${folder}`,
    openOne: "En ouvrir un",
    closed: "Le terminal s’est fermé.",
    exited: (code: number) => `Le processus s’est terminé avec le code ${code}.`,
    noneHere: "Aucun terminal n’est ouvert dans le dossier de cette session.",
    noSuch: (id: number, open: string) => `Il n’y a pas de terminal ${id}. Ouverts : ${open}.`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `Terminal ${id} · ${shell} dans ${root || "le dossier personnel"}${ended ? " · le processus est terminé" : ""}`,
    open: (listed: string) => `Ouverts : ${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name} (${shell}${ended ? ", terminé" : ""})`,
    empty: "(rien à l’écran)",
  },
  de: {
    terminal: "Terminal",
    terminals: "Terminals",
    closeThis: "Dieses Terminal schließen",
    closeNamed: (name: string) => `Terminal ${name} schließen`,
    newIn: (folder: string) => `Neues Terminal in ${folder}`,
    newOne: "Neues Terminal",
    shareTitle: "Auswahl zur Nachricht hinzufügen oder, ohne Auswahl, den sichtbaren Inhalt",
    share: "Zur Nachricht hinzufügen",
    opening: "Terminal wird geöffnet…",
    none: "Kein Terminal geöffnet.",
    openIn: (folder: string) => `Eines in ${folder} öffnen`,
    openOne: "Eines öffnen",
    closed: "Das Terminal wurde geschlossen.",
    exited: (code: number) => `Der Prozess wurde mit Code ${code} beendet.`,
    noneHere: "Im Ordner dieser Sitzung ist kein Terminal geöffnet.",
    noSuch: (id: number, open: string) => `Es gibt kein Terminal ${id}. Geöffnet: ${open}.`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `Terminal ${id} · ${shell} ${root ? `in ${root}` : "im Benutzerordner"}${ended ? " · der Prozess ist beendet" : ""}`,
    open: (listed: string) => `Geöffnet: ${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name} (${shell}${ended ? ", beendet" : ""})`,
    empty: "(nichts auf dem Bildschirm)",
  },
  ja: {
    terminal: "ターミナル",
    terminals: "ターミナル",
    closeThis: "このターミナルを閉じる",
    closeNamed: (name: string) => `ターミナル ${name} を閉じる`,
    newIn: (folder: string) => `${folder} で新しいターミナル`,
    newOne: "新しいターミナル",
    shareTitle: "選択した部分をメッセージに追加します。選択がなければ表示中の内容を追加します。",
    share: "メッセージに追加",
    opening: "ターミナルを開いています…",
    none: "開いているターミナルはありません。",
    openIn: (folder: string) => `${folder} で開く`,
    openOne: "開く",
    closed: "ターミナルが閉じました。",
    exited: (code: number) => `プロセスは終了コード ${code} で終了しました。`,
    noneHere: "このセッションのフォルダーで開いているターミナルはありません。",
    noSuch: (id: number, open: string) => `ターミナル ${id} はありません。開いているもの: ${open}。`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `ターミナル ${id} · ${shell} · ${root || "ユーザーフォルダー"}${ended ? " · プロセスは終了しています" : ""}`,
    open: (listed: string) => `開いているもの: ${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name}（${shell}${ended ? "、終了" : ""}）`,
    empty: "（画面には何もありません）",
  },
  zh: {
    terminal: "终端",
    terminals: "终端",
    closeThis: "关闭此终端",
    closeNamed: (name: string) => `关闭终端 ${name}`,
    newIn: (folder: string) => `在 ${folder} 中新建终端`,
    newOne: "新建终端",
    shareTitle: "将所选内容添加到消息中；未选择时添加屏幕上显示的内容",
    share: "添加到消息",
    opening: "正在打开终端…",
    none: "没有打开的终端。",
    openIn: (folder: string) => `在 ${folder} 中打开一个`,
    openOne: "打开一个",
    closed: "终端已关闭。",
    exited: (code: number) => `进程已退出，退出码为 ${code}。`,
    noneHere: "此会话的文件夹中没有打开的终端。",
    noSuch: (id: number, open: string) => `没有终端 ${id}。已打开：${open}。`,
    heading: (id: number, shell: string, root: string, ended: boolean) => `终端 ${id} · ${shell} · ${root || "用户文件夹"}${ended ? " · 进程已结束" : ""}`,
    open: (listed: string) => `已打开：${listed}`,
    told: (id: number, name: string, shell: string, ended: boolean) => `${id} · ${name}（${shell}${ended ? "，已结束" : ""}）`,
    empty: "（屏幕上没有内容）",
  },
});
