import { copy } from "../shared/i18n";

export const t = copy({
  en: {
    installTitle: "Install Sens.",
    installLead: "Everything starts with clarity.",
    installGo: "Start",
    updateTitle: "Update Sens.",
    updateLead: (had: string, now: string) => `You have ${had}. This is ${now}.`,
    updateGo: "Update Sens",
    reinstallTitle: "Reinstall Sens.",
    reinstallLead: (now: string) => `You already have ${now}.`,
    reinstallGo: "Reinstall Sens",
    newerTitle: "You already have a newer Sens.",
    newerLead: (had: string, now: string) => `You have ${had}; this is ${now}.`,
    newerGo: "Install this version",
    uninstallTitle: "Uninstall Sens.",
    uninstallLead: "The app is removed. Your projects and their sessions are left untouched.",
    uninstallGo: "Uninstall",
    uninstallPage: "Uninstall Sens",
    install: "Install Sens",
    uninstalling: "Uninstalling Sens",
    updating: "Updating Sens",
    preparing: "Preparing Sens",
    uninstalled: "Sens has been uninstalled.",
    stillThere: "Your projects and their sessions are where they were.",
    upToDate: "Sens is up to date.",
    ready: "Sens is ready.",
    opening: "Opening Sens…",
    canOpen: "You can open it now.",
    pickUp: "Open it and pick up where you left off.",
    tailor: "In a minute we’ll make it yours.",
    broken: "Couldn’t open the installer.",
    minimize: "Minimize",
    removeData: "Also delete my Sens settings, skills and plugins",
    customize: "Customize installation",
    custom: "Customize",
    folder: "Folder",
    change: "Change…",
    needs: (size: string, free: string) => (free ? `Needs ${size} · ${free} free` : `Needs ${size}`),
    desktop: "Desktop shortcut",
    startMenu: "Add to the Start menu",
    next: "Continue",
    back: "Back",
    lookTitle: "Choose how it looks.",
    lookLead: "Sens will open like this. You can change it whenever you like in Settings.",
    languageTitle: "Choose your language.",
    languageLead: "Sens and this installer will use it. You can change it whenever you like in Settings.",
    languageIs: (name: string) => `Language: ${name}`,
    progress: "Progress",
    percent: (value: number) => `${value}%`,
    open: "Sens is open.",
    openLead: "Close it to go on. Sessions that are working will stop.",
    closeSens: "Close Sens",
    force: "Force it to close",
    closing: "Closing Sens…",
    forcing: "Forcing it to close…",
    stillOpen: "Sens hasn’t closed yet.",
    openSens: "Open Sens",
    failed: "Couldn’t finish.",
    copyLog: "Copy log",
    made: (version: string) => `Sens for Windows · v${version}`,
    demo: "demo",
    details: "Show details",
    cancelling: "Canceling…",
    pickDir: "Choose where to install Sens",
    unit: (at: number) => ["B", "KB", "MB", "GB", "TB"][at],
    steps: {
      check: "Checking…",
      close: "Waiting for Sens to close…",
      extract: "Copying files…",
      swap: "Putting the new version in place…",
      register: "Registering Sens with Windows…",
      shortcuts: "Creating shortcuts…",
      done: "Done.",
      remove: "Removing Sens…",
    },
  },
  es: {
    installTitle: "Instala Sens.",
    installLead: "Todo empieza con claridad.",
    installGo: "Empezar",
    updateTitle: "Actualiza Sens.",
    updateLead: (had: string, now: string) => `Tienes la ${had}. Esta es la ${now}.`,
    updateGo: "Actualizar Sens",
    reinstallTitle: "Reinstala Sens.",
    reinstallLead: (now: string) => `Ya tienes la ${now}.`,
    reinstallGo: "Reinstalar Sens",
    newerTitle: "Ya tienes una Sens más nueva.",
    newerLead: (had: string, now: string) => `Tienes la ${had}; esta es la ${now}.`,
    newerGo: "Instalar esta versión",
    uninstallTitle: "Desinstalar Sens.",
    uninstallLead: "Se quita la aplicación. Tus proyectos y sus sesiones no se tocan.",
    uninstallGo: "Desinstalar",
    uninstallPage: "Desinstalar Sens",
    install: "Instalar Sens",
    uninstalling: "Desinstalando Sens",
    updating: "Actualizando Sens",
    preparing: "Preparando Sens",
    uninstalled: "Sens se ha desinstalado.",
    stillThere: "Tus proyectos y sus sesiones siguen donde estaban.",
    upToDate: "Sens está al día.",
    ready: "Sens está lista.",
    opening: "Abriendo Sens…",
    canOpen: "Ya puedes abrirla.",
    pickUp: "Ábrela y sigue donde lo dejaste.",
    tailor: "En un minuto la dejamos a tu gusto.",
    broken: "No se pudo abrir el instalador.",
    minimize: "Minimizar",
    removeData: "Borrar también mis ajustes, skills y plugins de Sens",
    customize: "Personalizar instalación",
    custom: "Personalizar",
    folder: "Carpeta",
    change: "Cambiar…",
    needs: (size: string, free: string) => (free ? `Necesita ${size} · libres ${free}` : `Necesita ${size}`),
    desktop: "Acceso directo en el escritorio",
    startMenu: "Añadir al menú Inicio",
    next: "Continuar",
    back: "Volver",
    lookTitle: "Elige cómo se ve.",
    lookLead: "Sens se abrirá así. Puedes cambiarlo cuando quieras en Ajustes.",
    languageTitle: "Elige tu idioma.",
    languageLead: "Sens y este instalador lo usarán. Puedes cambiarlo cuando quieras en Ajustes.",
    languageIs: (name: string) => `Idioma: ${name}`,
    progress: "Progreso",
    percent: (value: number) => `${value} %`,
    open: "Sens está abierta.",
    openLead: "Ciérrala para seguir. Las sesiones que estén trabajando se detendrán.",
    closeSens: "Cerrar Sens",
    force: "Forzar el cierre",
    closing: "Cerrando Sens…",
    forcing: "Forzando el cierre…",
    stillOpen: "Sens no se ha cerrado todavía.",
    openSens: "Abrir Sens",
    failed: "No se pudo terminar.",
    copyLog: "Copiar registro",
    made: (version: string) => `Sens para Windows · v${version}`,
    demo: "demo",
    details: "Ver detalles",
    cancelling: "Cancelando…",
    pickDir: "Elige dónde instalar Sens",
    unit: (at: number) => ["B", "KB", "MB", "GB", "TB"][at],
    steps: {
      check: "Comprobando…",
      close: "Esperando a que Sens se cierre…",
      extract: "Copiando ficheros…",
      swap: "Colocando la versión nueva…",
      register: "Registrando Sens en Windows…",
      shortcuts: "Creando accesos…",
      done: "Listo.",
      remove: "Quitando Sens…",
    },
  },
  fr: {
    installTitle: "Installez Sens.",
    installLead: "Tout commence par la clarté.",
    installGo: "Commencer",
    updateTitle: "Mettez Sens à jour.",
    updateLead: (had: string, now: string) => `Vous avez la ${had}. Voici la ${now}.`,
    updateGo: "Mettre à jour Sens",
    reinstallTitle: "Réinstallez Sens.",
    reinstallLead: (now: string) => `Vous avez déjà la ${now}.`,
    reinstallGo: "Réinstaller Sens",
    newerTitle: "Vous avez déjà un Sens plus récent.",
    newerLead: (had: string, now: string) => `Vous avez la ${had} ; celle-ci est la ${now}.`,
    newerGo: "Installer cette version",
    uninstallTitle: "Désinstaller Sens.",
    uninstallLead: "L’application est supprimée. Vos projets et leurs sessions restent intacts.",
    uninstallGo: "Désinstaller",
    uninstallPage: "Désinstaller Sens",
    install: "Installer Sens",
    uninstalling: "Désinstallation de Sens",
    updating: "Mise à jour de Sens",
    preparing: "Préparation de Sens",
    uninstalled: "Sens a été désinstallé.",
    stillThere: "Vos projets et leurs sessions sont toujours là où ils étaient.",
    upToDate: "Sens est à jour.",
    ready: "Sens est prêt.",
    opening: "Ouverture de Sens…",
    canOpen: "Vous pouvez l’ouvrir dès maintenant.",
    pickUp: "Ouvrez-le et reprenez là où vous vous étiez arrêté.",
    tailor: "En une minute, il sera à votre goût.",
    broken: "Impossible d’ouvrir le programme d’installation.",
    minimize: "Réduire",
    removeData: "Supprimer aussi mes paramètres, skills et plugins de Sens",
    customize: "Personnaliser l’installation",
    custom: "Personnaliser",
    folder: "Dossier",
    change: "Modifier…",
    needs: (size: string, free: string) => (free ? `Nécessite ${size} · ${free} libres` : `Nécessite ${size}`),
    desktop: "Raccourci sur le Bureau",
    startMenu: "Ajouter au menu Démarrer",
    next: "Continuer",
    back: "Retour",
    lookTitle: "Choisissez son apparence.",
    lookLead: "Sens s’ouvrira ainsi. Vous pourrez la modifier à tout moment dans les Paramètres.",
    languageTitle: "Choisissez votre langue.",
    languageLead: "Sens et ce programme d’installation l’utiliseront. Vous pourrez la modifier à tout moment dans les Paramètres.",
    languageIs: (name: string) => `Langue : ${name}`,
    progress: "Progression",
    percent: (value: number) => `${value} %`,
    open: "Sens est ouvert.",
    openLead: "Fermez-le pour continuer. Les sessions en cours seront arrêtées.",
    closeSens: "Fermer Sens",
    force: "Forcer la fermeture",
    closing: "Fermeture de Sens…",
    forcing: "Fermeture forcée…",
    stillOpen: "Sens n’est pas encore fermé.",
    openSens: "Ouvrir Sens",
    failed: "Impossible de terminer.",
    copyLog: "Copier le journal",
    made: (version: string) => `Sens pour Windows · v${version}`,
    demo: "démo",
    details: "Voir les détails",
    cancelling: "Annulation…",
    pickDir: "Choisissez où installer Sens",
    unit: (at: number) => ["o", "Ko", "Mo", "Go", "To"][at],
    steps: {
      check: "Vérification…",
      close: "En attente de la fermeture de Sens…",
      extract: "Copie des fichiers…",
      swap: "Mise en place de la nouvelle version…",
      register: "Inscription de Sens dans Windows…",
      shortcuts: "Création des raccourcis…",
      done: "Terminé.",
      remove: "Suppression de Sens…",
    },
  },
  de: {
    installTitle: "Installiere Sens.",
    installLead: "Alles beginnt mit Klarheit.",
    installGo: "Los geht’s",
    updateTitle: "Aktualisiere Sens.",
    updateLead: (had: string, now: string) => `Du hast ${had}. Das hier ist ${now}.`,
    updateGo: "Sens aktualisieren",
    reinstallTitle: "Installiere Sens neu.",
    reinstallLead: (now: string) => `Du hast ${now} bereits.`,
    reinstallGo: "Sens neu installieren",
    newerTitle: "Du hast schon ein neueres Sens.",
    newerLead: (had: string, now: string) => `Du hast ${had}; das hier ist ${now}.`,
    newerGo: "Diese Version installieren",
    uninstallTitle: "Sens deinstallieren.",
    uninstallLead: "Die App wird entfernt. Deine Projekte und ihre Sitzungen bleiben unberührt.",
    uninstallGo: "Deinstallieren",
    uninstallPage: "Sens deinstallieren",
    install: "Sens installieren",
    uninstalling: "Sens wird deinstalliert",
    updating: "Sens wird aktualisiert",
    preparing: "Sens wird vorbereitet",
    uninstalled: "Sens wurde deinstalliert.",
    stillThere: "Deine Projekte und ihre Sitzungen sind noch da, wo sie waren.",
    upToDate: "Sens ist auf dem neuesten Stand.",
    ready: "Sens ist bereit.",
    opening: "Sens wird geöffnet…",
    canOpen: "Du kannst es jetzt öffnen.",
    pickUp: "Öffne es und mach dort weiter, wo du aufgehört hast.",
    tailor: "In einer Minute richten wir es für dich ein.",
    broken: "Das Installationsprogramm konnte nicht geöffnet werden.",
    minimize: "Minimieren",
    removeData: "Auch meine Einstellungen, Skills und Plugins von Sens löschen",
    customize: "Installation anpassen",
    custom: "Anpassen",
    folder: "Ordner",
    change: "Ändern…",
    needs: (size: string, free: string) => (free ? `Benötigt ${size} · ${free} frei` : `Benötigt ${size}`),
    desktop: "Verknüpfung auf dem Desktop",
    startMenu: "Zum Startmenü hinzufügen",
    next: "Weiter",
    back: "Zurück",
    lookTitle: "Wähle, wie es aussieht.",
    lookLead: "So öffnet sich Sens. Du kannst es jederzeit in den Einstellungen ändern.",
    languageTitle: "Wähle deine Sprache.",
    languageLead: "Sens und dieses Installationsprogramm verwenden sie. Du kannst sie jederzeit in den Einstellungen ändern.",
    languageIs: (name: string) => `Sprache: ${name}`,
    progress: "Fortschritt",
    percent: (value: number) => `${value} %`,
    open: "Sens ist geöffnet.",
    openLead: "Schließe es, um fortzufahren. Laufende Sitzungen werden gestoppt.",
    closeSens: "Sens schließen",
    force: "Schließen erzwingen",
    closing: "Sens wird geschlossen…",
    forcing: "Schließen wird erzwungen…",
    stillOpen: "Sens ist noch nicht geschlossen.",
    openSens: "Sens öffnen",
    failed: "Konnte nicht abgeschlossen werden.",
    copyLog: "Protokoll kopieren",
    made: (version: string) => `Sens für Windows · v${version}`,
    demo: "Demo",
    details: "Details anzeigen",
    cancelling: "Wird abgebrochen…",
    pickDir: "Wähle, wo Sens installiert wird",
    unit: (at: number) => ["B", "KB", "MB", "GB", "TB"][at],
    steps: {
      check: "Wird geprüft…",
      close: "Warten, bis Sens geschlossen ist…",
      extract: "Dateien werden kopiert…",
      swap: "Neue Version wird eingesetzt…",
      register: "Sens wird in Windows registriert…",
      shortcuts: "Verknüpfungen werden erstellt…",
      done: "Fertig.",
      remove: "Sens wird entfernt…",
    },
  },
  ja: {
    installTitle: "Sens をインストールします。",
    installLead: "すべては明快さから始まります。",
    installGo: "始める",
    updateTitle: "Sens をアップデートします。",
    updateLead: (had: string, now: string) => `現在のバージョンは ${had}、インストールするのは ${now} です。`,
    updateGo: "Sens をアップデート",
    reinstallTitle: "Sens を再インストールします。",
    reinstallLead: (now: string) => `${now} はインストール済みです。`,
    reinstallGo: "Sens を再インストール",
    newerTitle: "より新しい Sens がインストールされています。",
    newerLead: (had: string, now: string) => `現在のバージョンは ${had}、このインストーラーは ${now} です。`,
    newerGo: "このバージョンをインストール",
    uninstallTitle: "Sens をアンインストールします。",
    uninstallLead: "アプリを削除します。プロジェクトとそのセッションはそのまま残ります。",
    uninstallGo: "アンインストール",
    uninstallPage: "Sens をアンインストール",
    install: "Sens をインストール",
    uninstalling: "Sens をアンインストールしています",
    updating: "Sens をアップデートしています",
    preparing: "Sens を準備しています",
    uninstalled: "Sens をアンインストールしました。",
    stillThere: "プロジェクトとそのセッションは元の場所に残っています。",
    upToDate: "Sens は最新です。",
    ready: "Sens の準備ができました。",
    opening: "Sens を開いています…",
    canOpen: "今すぐ開けます。",
    pickUp: "開いて、前回の続きから始めましょう。",
    tailor: "1 分であなた好みに整えます。",
    broken: "インストーラーを開けませんでした。",
    minimize: "最小化",
    removeData: "Sens の設定、スキル、プラグインも削除する",
    customize: "インストールをカスタマイズ",
    custom: "カスタマイズ",
    folder: "フォルダー",
    change: "変更…",
    needs: (size: string, free: string) => (free ? `必要な容量 ${size} · 空き ${free}` : `必要な容量 ${size}`),
    desktop: "デスクトップのショートカット",
    startMenu: "スタートメニューに追加",
    next: "続ける",
    back: "戻る",
    lookTitle: "見た目を選んでください。",
    lookLead: "Sens はこの見た目で開きます。設定からいつでも変更できます。",
    languageTitle: "言語を選んでください。",
    languageLead: "Sens とこのインストーラーがこの言語で表示されます。設定からいつでも変更できます。",
    languageIs: (name: string) => `言語: ${name}`,
    progress: "進行状況",
    percent: (value: number) => `${value}%`,
    open: "Sens が開いています。",
    openLead: "続けるには閉じてください。作業中のセッションは停止します。",
    closeSens: "Sens を閉じる",
    force: "強制終了",
    closing: "Sens を閉じています…",
    forcing: "強制終了中…",
    stillOpen: "Sens はまだ閉じていません。",
    openSens: "Sens を開く",
    failed: "完了できませんでした。",
    copyLog: "ログをコピー",
    made: (version: string) => `Windows 版 Sens · v${version}`,
    demo: "デモ",
    details: "詳細を表示",
    cancelling: "キャンセル中…",
    pickDir: "Sens のインストール先を選択",
    unit: (at: number) => ["B", "KB", "MB", "GB", "TB"][at],
    steps: {
      check: "確認中…",
      close: "Sens が閉じるのを待っています…",
      extract: "ファイルをコピーしています…",
      swap: "新しいバージョンを配置しています…",
      register: "Sens を Windows に登録しています…",
      shortcuts: "ショートカットを作成しています…",
      done: "完了しました。",
      remove: "Sens を削除しています…",
    },
  },
  zh: {
    installTitle: "安装 Sens。",
    installLead: "一切从清晰开始。",
    installGo: "开始",
    updateTitle: "更新 Sens。",
    updateLead: (had: string, now: string) => `你当前使用的是 ${had}，此安装程序为 ${now}。`,
    updateGo: "更新 Sens",
    reinstallTitle: "重新安装 Sens。",
    reinstallLead: (now: string) => `你已安装 ${now}。`,
    reinstallGo: "重新安装 Sens",
    newerTitle: "你已有更新版本的 Sens。",
    newerLead: (had: string, now: string) => `你当前使用的是 ${had}；此安装程序为 ${now}。`,
    newerGo: "安装此版本",
    uninstallTitle: "卸载 Sens。",
    uninstallLead: "将移除应用。你的项目及其会话不会受影响。",
    uninstallGo: "卸载",
    uninstallPage: "卸载 Sens",
    install: "安装 Sens",
    uninstalling: "正在卸载 Sens",
    updating: "正在更新 Sens",
    preparing: "正在准备 Sens",
    uninstalled: "Sens 已卸载。",
    stillThere: "你的项目及其会话仍在原处。",
    upToDate: "Sens 已是最新版本。",
    ready: "Sens 已就绪。",
    opening: "正在打开 Sens…",
    canOpen: "现在可以打开了。",
    pickUp: "打开它，从上次离开的地方继续。",
    tailor: "一分钟就能让它合你心意。",
    broken: "无法打开安装程序。",
    minimize: "最小化",
    removeData: "同时删除我的 Sens 设置、技能和插件",
    customize: "自定义安装",
    custom: "自定义",
    folder: "文件夹",
    change: "更改…",
    needs: (size: string, free: string) => (free ? `需要 ${size} · 可用 ${free}` : `需要 ${size}`),
    desktop: "桌面快捷方式",
    startMenu: "添加到“开始”菜单",
    next: "继续",
    back: "返回",
    lookTitle: "选择外观。",
    lookLead: "Sens 将以此外观打开。你可以随时在设置中更改。",
    languageTitle: "选择你的语言。",
    languageLead: "Sens 和此安装程序都将使用该语言。你可以随时在设置中更改。",
    languageIs: (name: string) => `语言：${name}`,
    progress: "进度",
    percent: (value: number) => `${value}%`,
    open: "Sens 正在运行。",
    openLead: "请关闭它以继续。正在运行的会话将会停止。",
    closeSens: "关闭 Sens",
    force: "强制关闭",
    closing: "正在关闭 Sens…",
    forcing: "正在强制关闭…",
    stillOpen: "Sens 尚未关闭。",
    openSens: "打开 Sens",
    failed: "未能完成。",
    copyLog: "复制日志",
    made: (version: string) => `Sens Windows 版 · v${version}`,
    demo: "演示",
    details: "查看详情",
    cancelling: "正在取消…",
    pickDir: "选择 Sens 的安装位置",
    unit: (at: number) => ["B", "KB", "MB", "GB", "TB"][at],
    steps: {
      check: "正在检查…",
      close: "正在等待 Sens 关闭…",
      extract: "正在复制文件…",
      swap: "正在替换为新版本…",
      register: "正在向 Windows 注册 Sens…",
      shortcuts: "正在创建快捷方式…",
      done: "已完成。",
      remove: "正在移除 Sens…",
    },
  },
});
