import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    read: "Read",
    edit: "Edit",
    write: "Write",
    run: "Run",
    search: "Search",
    list: "List",
    searchWeb: "Search the web",
    todos: "Tasks",
    delegate: "Delegate",
    useSkill: "Use skill",
    readTerminal: "Read the terminal",
    wantsRead: "Claude wants to read",
    wantsEdit: "Claude wants to edit",
    wantsWrite: "Claude wants to write",
    wantsRun: "Claude wants to run",
    wantsSearch: "Claude wants to search",
    wantsList: "Claude wants to list",
    wantsOpen: "Claude wants to open",
    wantsSearchWeb: "Claude wants to search the web",
    wantsTodos: "Claude wants to update the tasks",
    wantsDelegate: "Claude wants to delegate",
    wantsSkill: "Claude wants to use a skill",
    wantsReadTerminal: "Claude wants to read the terminal",
    wantsUse: (name: string) => `Claude wants to use ${name}`,
    inPath: (path: string) => `in ${path}`,
    lines: (count: number) => (count === 1 ? "1 line" : `${count} lines`),
    results: (count: number) => (count === 1 ? "1 result" : `${count} results`),
    showMore: (count: number) => `Show ${count} more`,
    endedWithError: "Ended with an error",
    noOutput: "No output",
    consulting: (host: string) => `Consulting ${host}`,
    reviewing: (count: number) => `Reviewing ${count} sources`,
    allowed: "Allowed",
    denied: "Denied",
    unanswered: "No answer",
    allow: "Allow",
    allowAndAccept: "Allow and accept edits",
    allowSession: "Always allow in this session",
    deny: "Deny",
    planReady: "Plan ready for review",
    approveRun: "Approve and run",
    approveAccept: "Approve and accept edits",
    keepPlanning: "Keep planning",
    keepPlanningSaid: "I don’t approve the plan yet. Keep refining it.",
    answerEach: "Answer each question or type your answer.",
    answer: "Answer",
    letClaude: "Let Claude decide",
    letClaudeSaid: "The user prefers not to answer; decide what is most reasonable and continue.",
    asksMany: "Claude has a few questions",
    asksOne: "Claude asks",
    otherAnswer: "Another answer…",
  },
  es: {
    read: "Leer",
    edit: "Editar",
    write: "Escribir",
    run: "Ejecutar",
    search: "Buscar",
    list: "Listar",
    searchWeb: "Buscar en la web",
    todos: "Tareas",
    delegate: "Delegar",
    useSkill: "Usar skill",
    readTerminal: "Leer la terminal",
    wantsRead: "Claude quiere leer",
    wantsEdit: "Claude quiere editar",
    wantsWrite: "Claude quiere escribir",
    wantsRun: "Claude quiere ejecutar",
    wantsSearch: "Claude quiere buscar",
    wantsList: "Claude quiere listar",
    wantsOpen: "Claude quiere abrir",
    wantsSearchWeb: "Claude quiere buscar en la web",
    wantsTodos: "Claude quiere actualizar las tareas",
    wantsDelegate: "Claude quiere delegar",
    wantsSkill: "Claude quiere usar una skill",
    wantsReadTerminal: "Claude quiere leer la terminal",
    wantsUse: (name: string) => `Claude quiere usar ${name}`,
    inPath: (path: string) => `en ${path}`,
    lines: (count: number) => (count === 1 ? "1 línea" : `${count} líneas`),
    results: (count: number) => (count === 1 ? "1 resultado" : `${count} resultados`),
    showMore: (count: number) => `Mostrar ${count} más`,
    endedWithError: "Terminó con error",
    noOutput: "Sin salida",
    consulting: (host: string) => `Consultando ${host}`,
    reviewing: (count: number) => `Revisando ${count} fuentes`,
    allowed: "Permitido",
    denied: "Rechazado",
    unanswered: "Sin respuesta",
    allow: "Permitir",
    allowAndAccept: "Permitir y aceptar ediciones",
    allowSession: "Permitir siempre en esta sesión",
    deny: "Rechazar",
    planReady: "Plan listo para revisar",
    approveRun: "Aprobar y ejecutar",
    approveAccept: "Aprobar y aceptar ediciones",
    keepPlanning: "Seguir planificando",
    keepPlanningSaid: "Todavía no apruebo el plan. Sigue refinándolo.",
    answerEach: "Responde a cada pregunta o escribe tu respuesta.",
    answer: "Responder",
    letClaude: "Que decida Claude",
    letClaudeSaid: "El usuario prefiere no responder; decide tú lo más razonable y sigue.",
    asksMany: "Claude tiene unas preguntas",
    asksOne: "Claude pregunta",
    otherAnswer: "Otra respuesta…",
  },
  fr: {
    read: "Lire",
    edit: "Modifier",
    write: "Écrire",
    run: "Exécuter",
    search: "Rechercher",
    list: "Lister",
    searchWeb: "Rechercher sur le Web",
    todos: "Tâches",
    delegate: "Déléguer",
    useSkill: "Utiliser une skill",
    readTerminal: "Lire le terminal",
    wantsRead: "Claude souhaite lire",
    wantsEdit: "Claude souhaite modifier",
    wantsWrite: "Claude souhaite écrire",
    wantsRun: "Claude souhaite exécuter",
    wantsSearch: "Claude souhaite rechercher",
    wantsList: "Claude souhaite lister",
    wantsOpen: "Claude souhaite ouvrir",
    wantsSearchWeb: "Claude souhaite rechercher sur le Web",
    wantsTodos: "Claude souhaite mettre à jour les tâches",
    wantsDelegate: "Claude souhaite déléguer",
    wantsSkill: "Claude souhaite utiliser une skill",
    wantsReadTerminal: "Claude souhaite lire le terminal",
    wantsUse: (name: string) => `Claude souhaite utiliser ${name}`,
    inPath: (path: string) => `dans ${path}`,
    lines: (count: number) => (count <= 1 ? `${count} ligne` : `${count} lignes`),
    results: (count: number) => (count <= 1 ? `${count} résultat` : `${count} résultats`),
    showMore: (count: number) => `Afficher ${count} de plus`,
    endedWithError: "Terminé avec une erreur",
    noOutput: "Aucune sortie",
    consulting: (host: string) => `Consultation de ${host}`,
    reviewing: (count: number) => `Examen de ${count} sources`,
    allowed: "Autorisé",
    denied: "Refusé",
    unanswered: "Sans réponse",
    allow: "Autoriser",
    allowAndAccept: "Autoriser et accepter les modifications",
    allowSession: "Toujours autoriser dans cette session",
    deny: "Refuser",
    planReady: "Plan prêt à être relu",
    approveRun: "Approuver et exécuter",
    approveAccept: "Approuver et accepter les modifications",
    keepPlanning: "Continuer à planifier",
    keepPlanningSaid: "Je n’approuve pas encore le plan. Continuez à l’affiner.",
    answerEach: "Répondez à chaque question ou saisissez votre réponse.",
    answer: "Répondre",
    letClaude: "Laisser Claude décider",
    letClaudeSaid: "L’utilisateur préfère ne pas répondre ; décidez de ce qui est le plus raisonnable et continuez.",
    asksMany: "Claude a quelques questions",
    asksOne: "Claude demande",
    otherAnswer: "Autre réponse…",
  },
  de: {
    read: "Lesen",
    edit: "Bearbeiten",
    write: "Schreiben",
    run: "Ausführen",
    search: "Suchen",
    list: "Auflisten",
    searchWeb: "Im Web suchen",
    todos: "Aufgaben",
    delegate: "Delegieren",
    useSkill: "Skill nutzen",
    readTerminal: "Terminal lesen",
    wantsRead: "Claude möchte lesen",
    wantsEdit: "Claude möchte bearbeiten",
    wantsWrite: "Claude möchte schreiben",
    wantsRun: "Claude möchte ausführen",
    wantsSearch: "Claude möchte suchen",
    wantsList: "Claude möchte auflisten",
    wantsOpen: "Claude möchte öffnen",
    wantsSearchWeb: "Claude möchte im Web suchen",
    wantsTodos: "Claude möchte die Aufgaben aktualisieren",
    wantsDelegate: "Claude möchte delegieren",
    wantsSkill: "Claude möchte einen Skill nutzen",
    wantsReadTerminal: "Claude möchte das Terminal lesen",
    wantsUse: (name: string) => `Claude möchte ${name} nutzen`,
    inPath: (path: string) => `in ${path}`,
    lines: (count: number) => (count === 1 ? "1 Zeile" : `${count} Zeilen`),
    results: (count: number) => (count === 1 ? "1 Treffer" : `${count} Treffer`),
    showMore: (count: number) => `${count} weitere anzeigen`,
    endedWithError: "Mit Fehler beendet",
    noOutput: "Keine Ausgabe",
    consulting: (host: string) => `Liest ${host}`,
    reviewing: (count: number) => `Prüft ${count} Quellen`,
    allowed: "Erlaubt",
    denied: "Abgelehnt",
    unanswered: "Keine Antwort",
    allow: "Erlauben",
    allowAndAccept: "Erlauben und Änderungen annehmen",
    allowSession: "In dieser Sitzung immer erlauben",
    deny: "Ablehnen",
    planReady: "Plan bereit zur Prüfung",
    approveRun: "Genehmigen und ausführen",
    approveAccept: "Genehmigen und Änderungen annehmen",
    keepPlanning: "Weiter planen",
    keepPlanningSaid: "Ich genehmige den Plan noch nicht. Arbeite weiter daran.",
    answerEach: "Beantworte jede Frage oder schreib deine Antwort.",
    answer: "Antworten",
    letClaude: "Claude entscheiden lassen",
    letClaudeSaid: "Der Nutzer möchte nicht antworten; entscheide selbst, was am sinnvollsten ist, und mach weiter.",
    asksMany: "Claude hat ein paar Fragen",
    asksOne: "Claude fragt",
    otherAnswer: "Andere Antwort…",
  },
  ja: {
    read: "読み取り",
    edit: "編集",
    write: "書き込み",
    run: "実行",
    search: "検索",
    list: "一覧",
    searchWeb: "Web 検索",
    todos: "タスク",
    delegate: "委任",
    useSkill: "スキルを使用",
    readTerminal: "ターミナルの読み取り",
    wantsRead: "Claude が読み取ろうとしています",
    wantsEdit: "Claude が編集しようとしています",
    wantsWrite: "Claude が書き込もうとしています",
    wantsRun: "Claude が実行しようとしています",
    wantsSearch: "Claude が検索しようとしています",
    wantsList: "Claude が一覧を取得しようとしています",
    wantsOpen: "Claude が開こうとしています",
    wantsSearchWeb: "Claude が Web を検索しようとしています",
    wantsTodos: "Claude がタスクを更新しようとしています",
    wantsDelegate: "Claude が委任しようとしています",
    wantsSkill: "Claude がスキルを使おうとしています",
    wantsReadTerminal: "Claude がターミナルを読み取ろうとしています",
    wantsUse: (name: string) => `Claude が ${name} を使おうとしています`,
    inPath: (path: string) => `${path} 内`,
    lines: (count: number) => `${count} 行`,
    results: (count: number) => `${count} 件`,
    showMore: (count: number) => `さらに ${count} 件を表示`,
    endedWithError: "エラーで終了しました",
    noOutput: "出力なし",
    consulting: (host: string) => `${host} を参照中`,
    reviewing: (count: number) => `${count} 件のソースを確認中`,
    allowed: "許可済み",
    denied: "拒否済み",
    unanswered: "回答なし",
    allow: "許可",
    allowAndAccept: "許可して「編集を許可」にする",
    allowSession: "このセッションでは常に許可",
    deny: "拒否",
    planReady: "確認待ちの計画",
    approveRun: "承認して実行",
    approveAccept: "承認して「編集を許可」にする",
    keepPlanning: "計画を続ける",
    keepPlanningSaid: "まだ計画を承認していません。引き続き改善してください。",
    answerEach: "それぞれの質問に答えるか、回答を入力してください。",
    answer: "回答",
    letClaude: "Claude に任せる",
    letClaudeSaid: "ユーザーは回答しないことを選びました。最も妥当な判断をして続けてください。",
    asksMany: "Claude からいくつか質問があります",
    asksOne: "Claude からの質問",
    otherAnswer: "その他の回答…",
  },
  zh: {
    read: "读取",
    edit: "编辑",
    write: "写入",
    run: "运行",
    search: "搜索",
    list: "列出",
    searchWeb: "搜索网页",
    todos: "任务",
    delegate: "委派",
    useSkill: "使用技能",
    readTerminal: "读取终端",
    wantsRead: "Claude 想要读取",
    wantsEdit: "Claude 想要编辑",
    wantsWrite: "Claude 想要写入",
    wantsRun: "Claude 想要运行",
    wantsSearch: "Claude 想要搜索",
    wantsList: "Claude 想要列出",
    wantsOpen: "Claude 想要打开",
    wantsSearchWeb: "Claude 想要搜索网页",
    wantsTodos: "Claude 想要更新任务",
    wantsDelegate: "Claude 想要委派",
    wantsSkill: "Claude 想要使用技能",
    wantsReadTerminal: "Claude 想要读取终端",
    wantsUse: (name: string) => `Claude 想要使用 ${name}`,
    inPath: (path: string) => `在 ${path} 中`,
    lines: (count: number) => `${count} 行`,
    results: (count: number) => `${count} 个结果`,
    showMore: (count: number) => `再显示 ${count} 项`,
    endedWithError: "因错误结束",
    noOutput: "无输出",
    consulting: (host: string) => `正在查阅 ${host}`,
    reviewing: (count: number) => `正在查看 ${count} 个来源`,
    allowed: "已允许",
    denied: "已拒绝",
    unanswered: "未回答",
    allow: "允许",
    allowAndAccept: "允许并接受编辑",
    allowSession: "在此会话中始终允许",
    deny: "拒绝",
    planReady: "计划已就绪，待审阅",
    approveRun: "批准并运行",
    approveAccept: "批准并接受编辑",
    keepPlanning: "继续规划",
    keepPlanningSaid: "我还没有批准这个计划。请继续完善。",
    answerEach: "请回答每个问题，或输入你的回答。",
    answer: "回答",
    letClaude: "让 Claude 决定",
    letClaudeSaid: "用户选择不回答；请自行做出最合理的决定并继续。",
    asksMany: "Claude 有几个问题",
    asksOne: "Claude 提问",
    otherAnswer: "其他回答…",
  },
});
