import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    thought: "Thought",
    thinking: "Thinking…",
    worked: "Worked",
    commands: (count: number) => (count === 1 ? "1 command" : `${count} commands`),
    reads: (count: number) => (count === 1 ? "1 file read" : `${count} files read`),
    edits: (count: number) => (count === 1 ? "1 edit" : `${count} edits`),
    searches: (count: number) => (count === 1 ? "1 search" : `${count} searches`),
    others: (count: number) => (count === 1 ? "1 other step" : `${count} other steps`),
    failed: (count: number) => `${count} failed`,
    tokens: (count: string) => `${count} tokens`,
    stopped: "stopped",
    compactedByClaude: "Claude Code compacted the conversation",
    compacted: "Conversation compacted",
    before: (count: string) => `was ${count} tokens`,
    noFolder: "Choose a working folder to start.",
    hint: (nth: number) =>
      [
        "Ask anything, paste an error or point me to a file.",
        "Tell me what you want to change and I’ll start by reading the project.",
        "Paste a stack trace and I’ll find where it comes from.",
        "Ask me about a symbol and I’ll tell you who uses it.",
        "Where do we start? Describe the problem and I’ll take a look.",
        "Name a file and I’ll explain it before touching it.",
        "Start with whatever is blocking you right now.",
        "Ask me for a summary of the project and I’ll walk you through how it works.",
      ][nth],
  },
  es: {
    thought: "Razonamiento",
    thinking: "Razonando…",
    worked: "Trabajó",
    commands: (count: number) => (count === 1 ? "1 comando" : `${count} comandos`),
    reads: (count: number) => (count === 1 ? "1 fichero leído" : `${count} ficheros leídos`),
    edits: (count: number) => (count === 1 ? "1 edición" : `${count} ediciones`),
    searches: (count: number) => (count === 1 ? "1 búsqueda" : `${count} búsquedas`),
    others: (count: number) => (count === 1 ? "1 paso más" : `${count} pasos más`),
    failed: (count: number) => `${count} con error`,
    tokens: (count: string) => `${count} tokens`,
    stopped: "detenido",
    compactedByClaude: "Claude Code compactó la conversación",
    compacted: "Conversación compactada",
    before: (count: string) => `tenía ${count} tokens`,
    noFolder: "Elige una carpeta de trabajo para empezar.",
    hint: (nth: number) =>
      [
        "Pregunta lo que necesites, pega un error o señálame un fichero.",
        "Cuéntame qué quieres cambiar y empiezo por leer el proyecto.",
        "Pégame una traza y busco de dónde sale.",
        "Pregúntame por un símbolo y te digo quién lo usa.",
        "¿Por dónde empezamos? Describe el problema y lo miro.",
        "Dime un fichero y te lo explico antes de tocarlo.",
        "Empieza por lo que te esté bloqueando ahora mismo.",
        "Pídeme un resumen del proyecto y te lo cuento por dentro.",
      ][nth],
  },
  fr: {
    thought: "Réflexion",
    thinking: "Réflexion en cours…",
    worked: "Travail",
    commands: (count: number) => (count === 1 ? "1 commande" : `${count} commandes`),
    reads: (count: number) => (count === 1 ? "1 fichier lu" : `${count} fichiers lus`),
    edits: (count: number) => (count === 1 ? "1 modification" : `${count} modifications`),
    searches: (count: number) => (count === 1 ? "1 recherche" : `${count} recherches`),
    others: (count: number) => (count === 1 ? "1 autre étape" : `${count} autres étapes`),
    failed: (count: number) => `${count} en échec`,
    tokens: (count: string) => `${count} tokens`,
    stopped: "arrêté",
    compactedByClaude: "Claude Code a compacté la conversation",
    compacted: "Conversation compactée",
    before: (count: string) => `${count} tokens auparavant`,
    noFolder: "Choisissez un dossier de travail pour commencer.",
    hint: (nth: number) =>
      [
        "Posez votre question, collez une erreur ou indiquez-moi un fichier.",
        "Dites-moi ce que vous voulez changer et je commence par lire le projet.",
        "Collez une trace d’appels et je trouve d’où elle vient.",
        "Interrogez-moi sur un symbole et je vous dis qui l’utilise.",
        "Par où commencer ? Décrivez le problème et j’y jette un œil.",
        "Indiquez-moi un fichier et je vous l’explique avant d’y toucher.",
        "Commencez par ce qui vous bloque en ce moment.",
        "Demandez-moi un résumé du projet et je vous en montre les rouages.",
      ][nth],
  },
  de: {
    thought: "Nachgedacht",
    thinking: "Denkt nach…",
    worked: "Gearbeitet",
    commands: (count: number) => (count === 1 ? "1 Befehl" : `${count} Befehle`),
    reads: (count: number) => (count === 1 ? "1 Datei gelesen" : `${count} Dateien gelesen`),
    edits: (count: number) => (count === 1 ? "1 Änderung" : `${count} Änderungen`),
    searches: (count: number) => (count === 1 ? "1 Suche" : `${count} Suchen`),
    others: (count: number) => (count === 1 ? "1 weiterer Schritt" : `${count} weitere Schritte`),
    failed: (count: number) => `${count} fehlgeschlagen`,
    tokens: (count: string) => `${count} Tokens`,
    stopped: "gestoppt",
    compactedByClaude: "Claude Code hat die Unterhaltung komprimiert",
    compacted: "Unterhaltung komprimiert",
    before: (count: string) => `vorher ${count} Tokens`,
    noFolder: "Wähle einen Arbeitsordner, um loszulegen.",
    hint: (nth: number) =>
      [
        "Frag, was du brauchst, füge einen Fehler ein oder zeig mir eine Datei.",
        "Sag mir, was du ändern willst, und ich lese mir zuerst das Projekt an.",
        "Füge einen Stacktrace ein, und ich finde heraus, woher er kommt.",
        "Frag mich nach einem Symbol, und ich sage dir, wer es verwendet.",
        "Womit fangen wir an? Beschreib das Problem, und ich sehe es mir an.",
        "Nenn mir eine Datei, und ich erkläre sie dir, bevor ich sie anfasse.",
        "Fang mit dem an, was dich gerade blockiert.",
        "Bitte mich um eine Zusammenfassung des Projekts, und ich zeige dir, wie es innen aufgebaut ist.",
      ][nth],
  },
  ja: {
    thought: "思考",
    thinking: "思考中…",
    worked: "作業",
    commands: (count: number) => `コマンド ${count} 件`,
    reads: (count: number) => `ファイル読み取り ${count} 件`,
    edits: (count: number) => `編集 ${count} 件`,
    searches: (count: number) => `検索 ${count} 件`,
    others: (count: number) => `その他 ${count} 件`,
    failed: (count: number) => `失敗 ${count} 件`,
    tokens: (count: string) => `${count} トークン`,
    stopped: "停止",
    compactedByClaude: "Claude Code が会話を圧縮しました",
    compacted: "会話を圧縮しました",
    before: (count: string) => `圧縮前 ${count} トークン`,
    noFolder: "作業フォルダーを選んで始めてください。",
    hint: (nth: number) =>
      [
        "質問、エラーの貼り付け、ファイルの指定など、何でもどうぞ。",
        "変えたいことを教えてください。まずプロジェクトを読みます。",
        "スタックトレースを貼ってください。どこから来ているか調べます。",
        "シンボルについて聞いてください。どこで使われているかお伝えします。",
        "どこから始めましょうか。問題を説明してください。確認します。",
        "ファイルを教えてください。手を加える前に中身を説明します。",
        "いま詰まっているところから始めましょう。",
        "プロジェクトの要約を頼んでください。内部の仕組みを説明します。",
      ][nth],
  },
  zh: {
    thought: "已思考",
    thinking: "思考中…",
    worked: "已处理",
    commands: (count: number) => `${count} 条命令`,
    reads: (count: number) => `读取 ${count} 个文件`,
    edits: (count: number) => `${count} 处编辑`,
    searches: (count: number) => `${count} 次搜索`,
    others: (count: number) => `其他 ${count} 步`,
    failed: (count: number) => `${count} 个失败`,
    tokens: (count: string) => `${count} token`,
    stopped: "已停止",
    compactedByClaude: "Claude Code 已压缩对话",
    compacted: "对话已压缩",
    before: (count: string) => `压缩前 ${count} token`,
    noFolder: "选择一个工作文件夹即可开始。",
    hint: (nth: number) =>
      [
        "有什么需要尽管问，也可以粘贴报错或指给我一个文件。",
        "告诉我你想改什么，我先读一遍项目。",
        "贴一段堆栈跟踪，我来找出它的来源。",
        "问我某个符号，我告诉你哪里在用它。",
        "从哪里开始？描述一下问题，我来看看。",
        "告诉我一个文件，动手之前我先给你讲清楚。",
        "先从眼下卡住你的地方开始。",
        "可以让我总结这个项目，我会带你了解它的内部结构。",
      ][nth],
  },
});

export const HINTS = 8;
