import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    chooseFolderTitle: "Choose a working folder",
    chooseFolder: "Choose folder…",
    uncommitted: (count: number) => (count === 1 ? "1 uncommitted file" : `${count} uncommitted files`),
    detached: (branch: string) => `Detached HEAD at ${branch}`,
    isolateHelp: "Works on a separate copy of the repository, on a new branch: nothing Claude does touches your folder until you merge it.",
    worktreeTitle: (branch: string, base: string, path: string) => `Works in a separate worktree, on branch ${branch} (created from ${base}): ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Search branches…",
    noBranchMatch: "No branch matches.",
    noOtherBranch: "No other branches.",
    branchSwitched: "branch · ",
    send: "Send",
    stop: "Stop",
    stopping: "Stopping…",
    attach: "Attach files",
    attachDialog: "Attach files or pictures",
    dictate: "Dictate",
    noDictation: "This system’s WebView has no dictation",
    placeholder: "Ask for anything · @ for a file, / for a command",
    messageLabel: "Message for Claude",
    projectFiles: "Project files",
    claudeCommands: "Claude Code commands",
    attachments: "Attachments",
    dropHere: "Drop to attach",
    folder: "Folder",
    file: "File",
    items: (count: number) => (count === 1 ? "1 item" : `${count} items`),
    pastedText: "Pasted text",
    lines: (count: number) => (count === 1 ? "1 line" : `${count} lines`),
    asText: "Paste as text",
    seePicture: (name: string) => `View ${name}`,
    openFile: (name: string) => `Open ${name}`,
    pastedPicture: "pasted picture",
    pastedFile: "pasted file",
    converted: (from: string, to: string) => `converted from ${from} to ${to}`,
    reduced: (width: number, height: number) => `reduced to ${width}×${height}`,
    missing: (name: string) => `${name} doesn’t exist`,
    unreadable: (name: string) => `Couldn’t read ${name}`,
    tooBig: (name: string, most: number) => `${name} is over ${most} MB · files from outside the project are attached up to that size`,
    isProject: (name: string) => `${name} is the project folder · Claude already works in it`,
    tooManyPictures: (most: number) => `Up to ${most} pictures per message · the rest were left out`,
    tooManyFiles: (most: number) => `Up to ${most} attachments per message · the rest were left out`,
    stageFailed: (name: string, reason: string) => `Couldn’t attach ${name}: ${reason}`,
  },
  es: {
    chooseFolderTitle: "Elegir carpeta de trabajo",
    chooseFolder: "Elegir carpeta…",
    uncommitted: (count: number) => (count === 1 ? "1 fichero sin confirmar" : `${count} ficheros sin confirmar`),
    detached: (branch: string) => `HEAD suelto en ${branch}`,
    isolateHelp: "Trabaja en una copia aparte del repositorio, en una rama nueva: lo que haga Claude no toca tu carpeta hasta que lo fusiones.",
    worktreeTitle: (branch: string, base: string, path: string) => `Trabaja en un worktree aparte, en la rama ${branch} (creada desde ${base}): ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Buscar ramas…",
    noBranchMatch: "Ninguna rama coincide.",
    noOtherBranch: "No hay más ramas.",
    branchSwitched: "rama · ",
    send: "Enviar",
    stop: "Parar",
    stopping: "Parando…",
    attach: "Adjuntar ficheros",
    attachDialog: "Adjuntar ficheros o imágenes",
    dictate: "Dictar",
    noDictation: "Este sistema no trae dictado en el WebView",
    placeholder: "Pide lo que necesites · @ para un fichero, / para un comando",
    messageLabel: "Mensaje para Claude",
    projectFiles: "Ficheros del proyecto",
    claudeCommands: "Comandos de Claude Code",
    attachments: "Adjuntos",
    dropHere: "Suelta para adjuntar",
    folder: "Carpeta",
    file: "Fichero",
    items: (count: number) => (count === 1 ? "1 elemento" : `${count} elementos`),
    pastedText: "Texto pegado",
    lines: (count: number) => (count === 1 ? "1 línea" : `${count} líneas`),
    asText: "Pegar como texto",
    seePicture: (name: string) => `Ver ${name}`,
    openFile: (name: string) => `Abrir ${name}`,
    pastedPicture: "imagen pegada",
    pastedFile: "fichero pegado",
    converted: (from: string, to: string) => `convertida de ${from} a ${to}`,
    reduced: (width: number, height: number) => `reducida a ${width}×${height}`,
    missing: (name: string) => `${name} no existe`,
    unreadable: (name: string) => `No pude leer ${name}`,
    tooBig: (name: string, most: number) => `${name} pasa de ${most} MB · lo que viene de fuera del proyecto se adjunta hasta ese tamaño`,
    isProject: (name: string) => `${name} es la carpeta del proyecto · Claude ya trabaja en ella`,
    tooManyPictures: (most: number) => `Hasta ${most} imágenes por mensaje · el resto no se adjuntó`,
    tooManyFiles: (most: number) => `Hasta ${most} adjuntos por mensaje · el resto no se adjuntó`,
    stageFailed: (name: string, reason: string) => `No pude adjuntar ${name}: ${reason}`,
  },
  fr: {
    chooseFolderTitle: "Choisir un dossier de travail",
    chooseFolder: "Choisir un dossier…",
    uncommitted: (count: number) => (count === 1 ? "1 fichier non validé" : `${count} fichiers non validés`),
    detached: (branch: string) => `HEAD détaché sur ${branch}`,
    isolateHelp: "Travaille sur une copie séparée du dépôt, dans une nouvelle branche : ce que fait Claude ne touche pas votre dossier tant que vous ne l’avez pas fusionné.",
    worktreeTitle: (branch: string, base: string, path: string) => `Travaille dans un worktree séparé, sur la branche ${branch} (créée depuis ${base}) : ${path}`,
    worktreeChip: "worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Rechercher des branches…",
    noBranchMatch: "Aucune branche ne correspond.",
    noOtherBranch: "Aucune autre branche.",
    branchSwitched: "branche · ",
    send: "Envoyer",
    stop: "Arrêter",
    stopping: "Arrêt…",
    attach: "Joindre des fichiers",
    attachDialog: "Joindre des fichiers ou des images",
    dictate: "Dicter",
    noDictation: "Le WebView de ce système ne propose pas de dictée",
    placeholder: "Demandez ce dont vous avez besoin · @ pour un fichier, / pour une commande",
    messageLabel: "Message pour Claude",
    projectFiles: "Fichiers du projet",
    claudeCommands: "Commandes de Claude Code",
    attachments: "Pièces jointes",
    dropHere: "Déposez pour joindre",
    folder: "Dossier",
    file: "Fichier",
    items: (count: number) => (count <= 1 ? `${count} élément` : `${count} éléments`),
    pastedText: "Texte collé",
    lines: (count: number) => (count <= 1 ? `${count} ligne` : `${count} lignes`),
    asText: "Coller comme texte",
    seePicture: (name: string) => `Afficher ${name}`,
    openFile: (name: string) => `Ouvrir ${name}`,
    pastedPicture: "image collée",
    pastedFile: "fichier collé",
    converted: (from: string, to: string) => `convertie de ${from} en ${to}`,
    reduced: (width: number, height: number) => `réduite à ${width}×${height}`,
    missing: (name: string) => `${name} n’existe pas`,
    unreadable: (name: string) => `Impossible de lire ${name}`,
    tooBig: (name: string, most: number) => `${name} dépasse ${most} Mo · les fichiers extérieurs au projet sont joints jusqu’à cette taille`,
    isProject: (name: string) => `${name} est le dossier du projet · Claude y travaille déjà`,
    tooManyPictures: (most: number) => `Jusqu’à ${most} images par message · les autres n’ont pas été jointes`,
    tooManyFiles: (most: number) => `Jusqu’à ${most} pièces jointes par message · les autres n’ont pas été jointes`,
    stageFailed: (name: string, reason: string) => `Impossible de joindre ${name} : ${reason}`,
  },
  de: {
    chooseFolderTitle: "Arbeitsordner wählen",
    chooseFolder: "Ordner wählen…",
    uncommitted: (count: number) => (count === 1 ? "1 nicht committete Datei" : `${count} nicht committete Dateien`),
    detached: (branch: string) => `Losgelöster HEAD bei ${branch}`,
    isolateHelp: "Arbeitet in einer separaten Kopie des Repositorys, auf einem neuen Branch: Was Claude tut, berührt deinen Ordner erst, wenn du es zusammenführst.",
    worktreeTitle: (branch: string, base: string, path: string) => `Arbeitet in einem separaten Worktree, auf dem Branch ${branch} (erstellt aus ${base}): ${path}`,
    worktreeChip: "Worktree",
    worktreeToggle: "Worktree",
    searchBranches: "Branches suchen…",
    noBranchMatch: "Kein passender Branch.",
    noOtherBranch: "Keine weiteren Branches.",
    branchSwitched: "Branch · ",
    send: "Senden",
    stop: "Stoppen",
    stopping: "Wird gestoppt…",
    attach: "Dateien anhängen",
    attachDialog: "Dateien oder Bilder anhängen",
    dictate: "Diktieren",
    noDictation: "Das WebView dieses Systems bietet kein Diktat",
    placeholder: "Frag, was du brauchst · @ für eine Datei, / für einen Befehl",
    messageLabel: "Nachricht an Claude",
    projectFiles: "Projektdateien",
    claudeCommands: "Befehle von Claude Code",
    attachments: "Anhänge",
    dropHere: "Zum Anhängen ablegen",
    folder: "Ordner",
    file: "Datei",
    items: (count: number) => (count === 1 ? "1 Element" : `${count} Elemente`),
    pastedText: "Eingefügter Text",
    lines: (count: number) => (count === 1 ? "1 Zeile" : `${count} Zeilen`),
    asText: "Als Text einfügen",
    seePicture: (name: string) => `${name} ansehen`,
    openFile: (name: string) => `${name} öffnen`,
    pastedPicture: "eingefügtes Bild",
    pastedFile: "eingefügte Datei",
    converted: (from: string, to: string) => `von ${from} in ${to} umgewandelt`,
    reduced: (width: number, height: number) => `auf ${width}×${height} verkleinert`,
    missing: (name: string) => `${name} existiert nicht`,
    unreadable: (name: string) => `${name} konnte nicht gelesen werden`,
    tooBig: (name: string, most: number) => `${name} ist größer als ${most} MB · Dateien von außerhalb des Projekts werden bis zu dieser Größe angehängt`,
    isProject: (name: string) => `${name} ist der Projektordner · Claude arbeitet bereits darin`,
    tooManyPictures: (most: number) => `Bis zu ${most} Bilder pro Nachricht · der Rest wurde nicht angehängt`,
    tooManyFiles: (most: number) => `Bis zu ${most} Anhänge pro Nachricht · der Rest wurde nicht angehängt`,
    stageFailed: (name: string, reason: string) => `${name} konnte nicht angehängt werden: ${reason}`,
  },
  ja: {
    chooseFolderTitle: "作業フォルダーを選択",
    chooseFolder: "フォルダーを選択…",
    uncommitted: (count: number) => `未コミットのファイル ${count} 個`,
    detached: (branch: string) => `${branch} で HEAD が切り離されています`,
    isolateHelp: "リポジトリの別コピーで、新しいブランチを使って作業します。マージするまで、Claude の作業は元のフォルダーに影響しません。",
    worktreeTitle: (branch: string, base: string, path: string) => `別のワークツリーのブランチ ${branch}（${base} から作成）で作業します: ${path}`,
    worktreeChip: "ワークツリー",
    worktreeToggle: "ワークツリー",
    searchBranches: "ブランチを検索…",
    noBranchMatch: "一致するブランチはありません。",
    noOtherBranch: "ほかのブランチはありません。",
    branchSwitched: "ブランチ · ",
    send: "送信",
    stop: "停止",
    stopping: "停止中…",
    attach: "ファイルを添付",
    attachDialog: "ファイルや画像を添付",
    dictate: "音声入力",
    noDictation: "このシステムの WebView は音声入力に対応していません",
    placeholder: "必要なことを入力 · @ でファイル、/ でコマンド",
    messageLabel: "Claude へのメッセージ",
    projectFiles: "プロジェクトのファイル",
    claudeCommands: "Claude Code のコマンド",
    attachments: "添付ファイル",
    dropHere: "ドロップして添付",
    folder: "フォルダー",
    file: "ファイル",
    items: (count: number) => `${count} 個の項目`,
    pastedText: "貼り付けたテキスト",
    lines: (count: number) => `${count} 行`,
    asText: "テキストとして貼り付け",
    seePicture: (name: string) => `${name} を表示`,
    openFile: (name: string) => `${name} を開く`,
    pastedPicture: "貼り付けた画像",
    pastedFile: "貼り付けたファイル",
    converted: (from: string, to: string) => `${from} から ${to} に変換`,
    reduced: (width: number, height: number) => `${width}×${height} に縮小`,
    missing: (name: string) => `${name} は存在しません`,
    unreadable: (name: string) => `${name} を読み取れませんでした`,
    tooBig: (name: string, most: number) => `${name} は ${most} MB を超えています · プロジェクト外のファイルはこのサイズまで添付できます`,
    isProject: (name: string) => `${name} はプロジェクトフォルダーです · Claude はすでにその中で作業しています`,
    tooManyPictures: (most: number) => `画像は 1 メッセージにつき ${most} 枚までです · 残りは添付されませんでした`,
    tooManyFiles: (most: number) => `添付ファイルは 1 メッセージにつき ${most} 個までです · 残りは添付されませんでした`,
    stageFailed: (name: string, reason: string) => `${name} を添付できませんでした: ${reason}`,
  },
  zh: {
    chooseFolderTitle: "选择工作文件夹",
    chooseFolder: "选择文件夹…",
    uncommitted: (count: number) => `${count} 个未提交的文件`,
    detached: (branch: string) => `HEAD 已分离于 ${branch}`,
    isolateHelp: "在仓库的独立副本和新分支上工作：合并之前，Claude 的任何操作都不会影响你的文件夹。",
    worktreeTitle: (branch: string, base: string, path: string) => `在独立的工作树中工作，分支 ${branch}（从 ${base} 创建）：${path}`,
    worktreeChip: "工作树",
    worktreeToggle: "工作树",
    searchBranches: "搜索分支…",
    noBranchMatch: "没有匹配的分支。",
    noOtherBranch: "没有其他分支。",
    branchSwitched: "分支 · ",
    send: "发送",
    stop: "停止",
    stopping: "正在停止…",
    attach: "附加文件",
    attachDialog: "附加文件或图片",
    dictate: "语音输入",
    noDictation: "此系统的 WebView 不支持语音输入",
    placeholder: "说出你的需求 · @ 引用文件，/ 使用命令",
    messageLabel: "发给 Claude 的消息",
    projectFiles: "项目文件",
    claudeCommands: "Claude Code 命令",
    attachments: "附件",
    dropHere: "松开即可附加",
    folder: "文件夹",
    file: "文件",
    items: (count: number) => `${count} 项`,
    pastedText: "粘贴的文本",
    lines: (count: number) => `${count} 行`,
    asText: "作为文本粘贴",
    seePicture: (name: string) => `查看 ${name}`,
    openFile: (name: string) => `打开 ${name}`,
    pastedPicture: "粘贴的图片",
    pastedFile: "粘贴的文件",
    converted: (from: string, to: string) => `已从 ${from} 转换为 ${to}`,
    reduced: (width: number, height: number) => `已缩小至 ${width}×${height}`,
    missing: (name: string) => `${name} 不存在`,
    unreadable: (name: string) => `无法读取 ${name}`,
    tooBig: (name: string, most: number) => `${name} 超过 ${most} MB · 项目外的文件最大可附加 ${most} MB`,
    isProject: (name: string) => `${name} 就是项目文件夹 · Claude 已在其中工作`,
    tooManyPictures: (most: number) => `每条消息最多 ${most} 张图片 · 其余未附加`,
    tooManyFiles: (most: number) => `每条消息最多 ${most} 个附件 · 其余未附加`,
    stageFailed: (name: string, reason: string) => `无法附加 ${name}：${reason}`,
  },
});
