import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    models: "Models",
    signingIn: "Waiting for sign-in…",
    connect: "Connect Claude Code…",
    newer: (version: string) => `A new version is available: v${version}`,
    update: "Update Claude Code…",
    refreshing: "Refreshing…",
    refresh: "Refresh models",
    done: "Done",
    edit: "Edit models…",
    finding: "Finding models…",
    allHidden: "All hidden",
    noModels: "No models yet",
    older: "Earlier",
    trustTitle: "Do you trust this project?",
    trustGo: "Trust and turn on",
    trustSaid: "With No checks, Claude edits files, runs commands and uses the network in this folder without asking you:",
    trustKept: "Sens will remember that you trust it and won’t ask again here.",
    permissions: "Permissions",
    modes: {
      default: "Ask",
      acceptEdits: "Accept edits",
      auto: "Auto",
      plan: "Plan",
      bypassPermissions: "No checks",
    },
    modesSaid: {
      default: "Asks before editing files or running commands.",
      acceptEdits: "Edits without asking; asks before running commands.",
      auto: "A classifier approves or blocks each action for you.",
      plan: "Explores and proposes a plan without changing anything.",
      bypassPermissions: "Does everything without asking: edits files, runs commands and uses the network. Only in trusted projects.",
    },
    thinking: "Thinking",
    thinkAlways: "This model always thinks",
    thinkOn: "Thinks before answering. Click to turn it off.",
    thinkOff: "Answers without thinking. Click to turn it on.",
    effort: "Effort",
    effortIs: (level: string) => `Effort: ${level}`,
    effortHelp: "How much the model reasons before answering. More effort takes longer and uses more, but gets hard problems right more often.",
    faster: "Faster",
    smarter: "Smarter",
    efforts: { low: "Low", medium: "Medium", high: "High", xhigh: "Extra", max: "Max" },
  },
  es: {
    models: "Modelos",
    signingIn: "Esperando al inicio de sesión…",
    connect: "Conectar Claude Code…",
    newer: (version: string) => `Hay una versión nueva: v${version}`,
    update: "Actualizar Claude Code…",
    refreshing: "Actualizando…",
    refresh: "Actualizar modelos",
    done: "Listo",
    edit: "Editar modelos…",
    finding: "Buscando modelos…",
    allHidden: "Todos ocultos",
    noModels: "Sin modelos todavía",
    older: "Anteriores",
    trustTitle: "¿Confías en este proyecto?",
    trustGo: "Confiar y activar",
    trustSaid: "Sin control, Claude edita ficheros, ejecuta comandos y usa la red sin pedirte permiso en esta carpeta:",
    trustKept: "Sens recordará que confías en ella y no volverá a preguntarte aquí.",
    permissions: "Permisos",
    modes: {
      default: "Preguntar",
      acceptEdits: "Aceptar ediciones",
      auto: "Automático",
      plan: "Planificar",
      bypassPermissions: "Sin control",
    },
    modesSaid: {
      default: "Pide permiso antes de editar ficheros o ejecutar comandos.",
      acceptEdits: "Edita sin preguntar; pide permiso para los comandos.",
      auto: "Un clasificador aprueba o bloquea cada acción por ti.",
      plan: "Explora y propone un plan sin tocar nada.",
      bypassPermissions: "Lo hace todo sin pedir permiso: edita, ejecuta comandos y usa la red. Solo en proyectos de confianza.",
    },
    thinking: "Razonamiento",
    thinkAlways: "Este modelo razona siempre",
    thinkOn: "Razona antes de responder. Pulsa para desactivarlo.",
    thinkOff: "Responde sin razonar. Pulsa para activarlo.",
    effort: "Esfuerzo",
    effortIs: (level: string) => `Esfuerzo ${level}`,
    effortHelp: "Cuánto razona el modelo antes de responder. Más esfuerzo tarda más y gasta más, pero acierta más en lo difícil.",
    faster: "Más rápido",
    smarter: "Más inteligente",
    efforts: { low: "Bajo", medium: "Medio", high: "Alto", xhigh: "Extra", max: "Max" },
  },
  fr: {
    models: "Modèles",
    signingIn: "En attente de la connexion…",
    connect: "Connecter Claude Code…",
    newer: (version: string) => `Une nouvelle version est disponible : v${version}`,
    update: "Mettre à jour Claude Code…",
    refreshing: "Actualisation…",
    refresh: "Actualiser les modèles",
    done: "Terminé",
    edit: "Modifier les modèles…",
    finding: "Recherche des modèles…",
    allHidden: "Tous masqués",
    noModels: "Aucun modèle pour l’instant",
    older: "Précédents",
    trustTitle: "Faites-vous confiance à ce projet ?",
    trustGo: "Faire confiance et activer",
    trustSaid: "En mode Sans contrôle, Claude modifie des fichiers, exécute des commandes et utilise le réseau dans ce dossier sans vous demander l’autorisation :",
    trustKept: "Sens se souviendra que vous lui faites confiance et ne vous le redemandera plus ici.",
    permissions: "Autorisations",
    modes: {
      default: "Demander",
      acceptEdits: "Accepter les modifications",
      auto: "Automatique",
      plan: "Planifier",
      bypassPermissions: "Sans contrôle",
    },
    modesSaid: {
      default: "Demande l’autorisation avant de modifier des fichiers ou d’exécuter des commandes.",
      acceptEdits: "Modifie sans demander ; demande l’autorisation pour les commandes.",
      auto: "Un classifieur approuve ou bloque chaque action à votre place.",
      plan: "Explore et propose un plan sans rien modifier.",
      bypassPermissions: "Fait tout sans demander : modifie des fichiers, exécute des commandes et utilise le réseau. Uniquement dans les projets de confiance.",
    },
    thinking: "Réflexion",
    thinkAlways: "Ce modèle réfléchit toujours",
    thinkOn: "Réfléchit avant de répondre. Cliquez pour désactiver.",
    thinkOff: "Répond sans réfléchir. Cliquez pour activer.",
    effort: "Effort",
    effortIs: (level: string) => `Effort : ${level}`,
    effortHelp: "Le temps de réflexion du modèle avant de répondre. Plus d’effort prend plus de temps et consomme davantage, mais réussit mieux les tâches difficiles.",
    faster: "Plus rapide",
    smarter: "Plus intelligent",
    efforts: { low: "Faible", medium: "Moyen", high: "Élevé", xhigh: "Extra", max: "Max" },
  },
  de: {
    models: "Modelle",
    signingIn: "Wartet auf die Anmeldung…",
    connect: "Claude Code verbinden…",
    newer: (version: string) => `Eine neue Version ist verfügbar: v${version}`,
    update: "Claude Code aktualisieren…",
    refreshing: "Wird aktualisiert…",
    refresh: "Modelle aktualisieren",
    done: "Fertig",
    edit: "Modelle bearbeiten…",
    finding: "Modelle werden gesucht…",
    allHidden: "Alle ausgeblendet",
    noModels: "Noch keine Modelle",
    older: "Ältere",
    trustTitle: "Vertraust du diesem Projekt?",
    trustGo: "Vertrauen und aktivieren",
    trustSaid: "Ohne Kontrolle bearbeitet Claude in diesem Ordner Dateien, führt Befehle aus und nutzt das Netzwerk, ohne dich zu fragen:",
    trustKept: "Sens merkt sich, dass du diesem Ordner vertraust, und fragt hier nicht mehr nach.",
    permissions: "Berechtigungen",
    modes: {
      default: "Nachfragen",
      acceptEdits: "Änderungen annehmen",
      auto: "Automatisch",
      plan: "Planen",
      bypassPermissions: "Ohne Kontrolle",
    },
    modesSaid: {
      default: "Fragt nach, bevor Dateien bearbeitet oder Befehle ausgeführt werden.",
      acceptEdits: "Bearbeitet ohne Nachfrage; fragt bei Befehlen nach.",
      auto: "Ein Klassifikator erlaubt oder blockiert jede Aktion für dich.",
      plan: "Erkundet und schlägt einen Plan vor, ohne etwas zu ändern.",
      bypassPermissions: "Macht alles ohne Nachfrage: bearbeitet Dateien, führt Befehle aus und nutzt das Netzwerk. Nur in vertrauenswürdigen Projekten.",
    },
    thinking: "Denken",
    thinkAlways: "Dieses Modell denkt immer nach",
    thinkOn: "Denkt vor der Antwort nach. Klicke zum Ausschalten.",
    thinkOff: "Antwortet ohne nachzudenken. Klicke zum Einschalten.",
    effort: "Aufwand",
    effortIs: (level: string) => `Aufwand: ${level}`,
    effortHelp: "Wie viel das Modell vor der Antwort nachdenkt. Mehr Aufwand dauert länger und verbraucht mehr, liegt bei Schwierigem aber öfter richtig.",
    faster: "Schneller",
    smarter: "Klüger",
    efforts: { low: "Niedrig", medium: "Mittel", high: "Hoch", xhigh: "Extra", max: "Max" },
  },
  ja: {
    models: "モデル",
    signingIn: "サインインを待っています…",
    connect: "Claude Code を接続…",
    newer: (version: string) => `新しいバージョンがあります: v${version}`,
    update: "Claude Code をアップデート…",
    refreshing: "更新中…",
    refresh: "モデルを更新",
    done: "完了",
    edit: "モデルを編集…",
    finding: "モデルを探しています…",
    allHidden: "すべて非表示",
    noModels: "まだモデルがありません",
    older: "以前のモデル",
    trustTitle: "このプロジェクトを信頼しますか？",
    trustGo: "信頼して有効にする",
    trustSaid: "確認なしでは、Claude はこのフォルダーで許可を求めずにファイルを編集し、コマンドを実行し、ネットワークを使います:",
    trustKept: "Sens はこの信頼を記憶し、ここでは再び確認しません。",
    permissions: "権限",
    modes: {
      default: "確認する",
      acceptEdits: "編集を許可",
      auto: "自動",
      plan: "計画",
      bypassPermissions: "確認なし",
    },
    modesSaid: {
      default: "ファイルの編集やコマンドの実行の前に許可を求めます。",
      acceptEdits: "編集は確認なしで行い、コマンドの実行前には許可を求めます。",
      auto: "分類器がアクションごとに承認またはブロックします。",
      plan: "何も変更せずに調べて、計画を提案します。",
      bypassPermissions: "許可を求めずにすべて行います。ファイルの編集、コマンドの実行、ネットワークの使用を含みます。信頼できるプロジェクトでのみ使えます。",
    },
    thinking: "思考",
    thinkAlways: "このモデルは常に思考します",
    thinkOn: "回答の前に思考します。クリックでオフにします。",
    thinkOff: "思考せずに回答します。クリックでオンにします。",
    effort: "推論の強さ",
    effortIs: (level: string) => `推論の強さ: ${level}`,
    effortHelp: "回答の前にモデルがどれだけ推論するかです。強くするほど時間と使用量は増えますが、難しい問題で正解しやすくなります。",
    faster: "速さ重視",
    smarter: "賢さ重視",
    efforts: { low: "低", medium: "中", high: "高", xhigh: "超高", max: "最大" },
  },
  zh: {
    models: "模型",
    signingIn: "正在等待登录…",
    connect: "连接 Claude Code…",
    newer: (version: string) => `有新版本：v${version}`,
    update: "更新 Claude Code…",
    refreshing: "正在刷新…",
    refresh: "刷新模型",
    done: "完成",
    edit: "编辑模型…",
    finding: "正在查找模型…",
    allHidden: "全部已隐藏",
    noModels: "暂无模型",
    older: "更早的模型",
    trustTitle: "你信任这个项目吗？",
    trustGo: "信任并启用",
    trustSaid: "在无需确认模式下，Claude 会在此文件夹中编辑文件、运行命令并使用网络，不会征求你的许可：",
    trustKept: "Sens 会记住你信任这个文件夹，在这里不会再问。",
    permissions: "权限",
    modes: {
      default: "询问",
      acceptEdits: "接受编辑",
      auto: "自动",
      plan: "规划",
      bypassPermissions: "无需确认",
    },
    modesSaid: {
      default: "编辑文件或运行命令前先征求许可。",
      acceptEdits: "直接编辑，运行命令前征求许可。",
      auto: "由分类器替你批准或阻止每个操作。",
      plan: "只探索并提出计划，不做任何更改。",
      bypassPermissions: "无需许可即可执行一切：编辑文件、运行命令和使用网络。仅限受信任的项目。",
    },
    thinking: "思考",
    thinkAlways: "此模型始终会思考",
    thinkOn: "回答前先思考。点击关闭。",
    thinkOff: "直接回答，不思考。点击开启。",
    effort: "推理强度",
    effortIs: (level: string) => `推理强度：${level}`,
    effortHelp: "模型在回答前推理的程度。强度越高，耗时和用量越多，但处理难题更准确。",
    faster: "更快",
    smarter: "更聪明",
    efforts: { low: "低", medium: "中", high: "高", xhigh: "超高", max: "最高" },
  },
});
