import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    title: "Settings",
    lead: "Your profile, how Sens looks and speaks, and who it works with.",
    closeHint: "Close (Esc)",
    closeSettings: "Close settings",
    sections: "Settings sections",
    section: { general: "General", look: "Appearance", language: "Language", providers: "Providers" },
    now: "Now",
    accentNote: "The color marks what Sens is doing: the cut, Send, the step in progress, effort at its highest.",
    systemNote: "System follows the light or dark mode of Windows.",
    languageNote: "Sens switches to this language right away. Claude replies in whatever language you write in.",
    name: "Name",
    save: "Save",
    saved: "Saved.",
    welcome: "Welcome",
    welcomeNote: "Your name, Claude Code and what you bring from Claude Code and other apps.",
    welcomeAgain: "See it again",
    importClaudeCode: "Import from Claude Code",
    updates: "Updates",
    devBuild: "development build: it checks but doesn’t install",
    viewVersion: (version: string) => `View Sens ${version}`,
    checkUpdates: "Check for updates",
    whatsNew: "See what’s new",
    notices: "Notifications",
    noticesSwitch: "Notify me when Claude finishes or needs you while Sens is in the background",
    checkAtStart: "Check when Sens opens",
    providersLead: "Who Sens works with. Sens never sees your credentials: each tool handles its own sign-in.",
    checking: "Checking…",
    moreProviders: "More providers soon.",
    weight: "about 230 MB",
    missing: (weight: string) =>
      `Sens uses Claude Code, Anthropic’s agent. When you connect, Sens downloads it from Anthropic (${weight}) and installs it just for your user, with no administrator rights.`,
    installNow: "Install now",
    checkAgain: "Check again",
    newer: (version: string) => `There’s a new version of Claude Code: v${version}. The newest models only show up with it.`,
    updateClaudeCode: "Update Claude Code",
    signsIn: "How it signs in",
    waiting: "Waiting for you to finish…",
    installsFirst: (weight: string) => `Sens installs Claude Code from Anthropic (${weight}).`,
    browserOpens: (site: string) => `Your browser opens at ${site}.`,
    authorize: "You authorize Claude Code and it gives you a code.",
    paste: "If asked, paste it into the Claude Code window. Sens notices on its own.",
    codeNote: "Claude Code handles the code and your session; Sens never sees them.",
    signOut: "Sign out",
    check: "Check",
    keySaved: (hint: string) => `Saved key: ${hint}`,
    removeKey: "Remove key",
    newKey: "Paste a new key to replace it",
    apiKey: "API key",
    saveKey: "Save key",
    keyNote: "It’s stored encrypted with your Windows user and never shown again.",
    keyInstalls: (weight: string) => `When you save it, Sens also installs Claude Code from Anthropic (${weight}).`,
    stage: { downloading: "Downloading Claude Code…", verifying: "Checking the download…", installing: "Installing Claude Code…", updating: "Updating Claude Code…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${percent}% of ${total} MB`,
    signInClaude: "Sign in with Claude",
    signInConsole: "Sign in with the Console",
    subscription: "Claude subscription",
    subscriptionSaid: "Pro or Max. You sign in in the browser with your Claude account.",
    console: "Anthropic Console",
    consoleSaid: "Pay as you go. You sign in with your Console account.",
    apiKeySaid: "You paste a key from the Console. It’s billed by usage and takes priority over the subscription.",
    notInstalled: "Claude Code isn’t on this computer",
    signedOut: "Not signed in",
    withKey: "Connected with an API key",
    usesSource: (source: string) => `Claude Code uses ${source}`,
    connected: "Connected",
    plan: (plan: string) => (plan ? `${plan} subscription` : "Subscription"),
    noPlan: "no Pro or Max plan",
  },
  es: {
    title: "Ajustes",
    lead: "Tu perfil, cómo se ve y habla Sens, y con quién trabaja.",
    closeHint: "Cerrar (Esc)",
    closeSettings: "Cerrar ajustes",
    sections: "Secciones de ajustes",
    section: { general: "General", look: "Apariencia", language: "Idioma", providers: "Proveedores" },
    now: "Ahora",
    accentNote: "El color marca lo que Sens está haciendo: el corte, enviar, el paso en curso, el esfuerzo al máximo.",
    systemNote: "Sistema sigue el modo claro u oscuro de Windows.",
    languageNote: "Sens cambia a este idioma al momento. Claude te responde en el idioma en que le escribas.",
    name: "Nombre",
    save: "Guardar",
    saved: "Guardado.",
    welcome: "Bienvenida",
    welcomeNote: "Tu nombre, Claude Code y lo que traes de Claude Code y de otras apps.",
    welcomeAgain: "Volver a verla",
    importClaudeCode: "Importar de Claude Code",
    updates: "Actualizaciones",
    devBuild: "build de desarrollo: comprueba pero no instala",
    viewVersion: (version: string) => `Ver Sens ${version}`,
    checkUpdates: "Buscar actualizaciones",
    whatsNew: "Ver novedades",
    notices: "Avisos",
    noticesSwitch: "Avisar cuando Claude termina o te necesita y Sens no está delante",
    checkAtStart: "Buscar al abrir Sens",
    providersLead: "Con quién trabaja Sens. Sens nunca ve tus credenciales: el inicio de sesión lo hace cada herramienta.",
    checking: "Comprobando…",
    moreProviders: "Más proveedores, pronto.",
    weight: "unos 230 MB",
    missing: (weight: string) =>
      `Sens usa Claude Code, el agente de Anthropic. Al conectar, Sens lo descarga de Anthropic (${weight}) y lo instala solo para tu usuario, sin permisos de administrador.`,
    installNow: "Instalar ahora",
    checkAgain: "Comprobar otra vez",
    newer: (version: string) => `Hay una versión nueva de Claude Code: v${version}. Los modelos más recientes solo aparecen con ella.`,
    updateClaudeCode: "Actualizar Claude Code",
    signsIn: "Cómo entra",
    waiting: "Esperando a que termines…",
    installsFirst: (weight: string) => `Sens instala Claude Code desde Anthropic (${weight}).`,
    browserOpens: (site: string) => `Se abre tu navegador en ${site}.`,
    authorize: "Autorizas a Claude Code y te da un código.",
    paste: "Si te lo pide, pégalo en la ventana de Claude Code. Sens se entera solo.",
    codeNote: "El código y tu sesión los maneja Claude Code; Sens nunca los ve.",
    signOut: "Cerrar sesión",
    check: "Comprobar",
    keySaved: (hint: string) => `Clave guardada: ${hint}`,
    removeKey: "Quitar clave",
    newKey: "Pega una clave nueva para cambiarla",
    apiKey: "Clave de API",
    saveKey: "Guardar clave",
    keyNote: "Se guarda cifrada con tu usuario de Windows y nunca se vuelve a mostrar.",
    keyInstalls: (weight: string) => `Al guardarla, Sens instala también Claude Code desde Anthropic (${weight}).`,
    stage: { downloading: "Descargando Claude Code…", verifying: "Comprobando la descarga…", installing: "Instalando Claude Code…", updating: "Actualizando Claude Code…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${percent} % de ${total} MB`,
    signInClaude: "Iniciar sesión con Claude",
    signInConsole: "Iniciar sesión con la Consola",
    subscription: "Suscripción de Claude",
    subscriptionSaid: "Pro o Max. Inicias sesión en el navegador con tu cuenta de Claude.",
    console: "Consola de Anthropic",
    consoleSaid: "Facturación por uso. Inicias sesión con tu cuenta de la Consola.",
    apiKeySaid: "Pegas una clave de la Consola. Se factura por uso y tiene prioridad sobre la suscripción.",
    notInstalled: "Falta Claude Code en este ordenador",
    signedOut: "Sin sesión",
    withKey: "Conectado con clave de API",
    usesSource: (source: string) => `Claude Code usa ${source}`,
    connected: "Conectado",
    plan: (plan: string) => (plan ? `Suscripción ${plan}` : "Suscripción"),
    noPlan: "sin plan Pro ni Max",
  },
  fr: {
    title: "Paramètres",
    lead: "Votre profil, l’apparence et la langue de Sens, et ceux avec qui il travaille.",
    closeHint: "Fermer (Échap)",
    closeSettings: "Fermer les paramètres",
    sections: "Sections des paramètres",
    section: { general: "Général", look: "Apparence", language: "Langue", providers: "Fournisseurs" },
    now: "Actuellement",
    accentNote: "La couleur signale ce que fait Sens : la découpe, l’envoi, l’étape en cours, l’effort au maximum.",
    systemNote: "Système suit le mode clair ou sombre de Windows.",
    languageNote: "Sens passe immédiatement à cette langue. Claude vous répond dans la langue dans laquelle vous écrivez.",
    name: "Nom",
    save: "Enregistrer",
    saved: "Enregistré.",
    welcome: "Bienvenue",
    welcomeNote: "Votre nom, Claude Code et ce que vous apportez de Claude Code et d’autres apps.",
    welcomeAgain: "La revoir",
    importClaudeCode: "Importer depuis Claude Code",
    updates: "Mises à jour",
    devBuild: "version de développement : elle vérifie sans installer",
    viewVersion: (version: string) => `Voir Sens ${version}`,
    checkUpdates: "Rechercher des mises à jour",
    whatsNew: "Voir les nouveautés",
    notices: "Notifications",
    noticesSwitch: "Prévenir quand Claude termine ou a besoin de vous et que Sens n’est pas au premier plan",
    checkAtStart: "Rechercher à l’ouverture de Sens",
    providersLead: "Ceux avec qui Sens travaille. Sens ne voit jamais vos identifiants : chaque outil gère sa propre connexion.",
    checking: "Vérification…",
    moreProviders: "D’autres fournisseurs bientôt.",
    weight: "environ 230 Mo",
    missing: (weight: string) =>
      `Sens utilise Claude Code, l’agent d’Anthropic. À la connexion, Sens le télécharge depuis Anthropic (${weight}) et l’installe uniquement pour votre utilisateur, sans droits d’administrateur.`,
    installNow: "Installer maintenant",
    checkAgain: "Vérifier à nouveau",
    newer: (version: string) => `Une nouvelle version de Claude Code est disponible : v${version}. Les modèles les plus récents n’apparaissent qu’avec elle.`,
    updateClaudeCode: "Mettre à jour Claude Code",
    signsIn: "Mode de connexion",
    waiting: "En attente de votre connexion…",
    installsFirst: (weight: string) => `Sens installe Claude Code depuis Anthropic (${weight}).`,
    browserOpens: (site: string) => `Votre navigateur s’ouvre sur ${site}.`,
    authorize: "Vous autorisez Claude Code, qui vous donne un code.",
    paste: "Si on vous le demande, collez-le dans la fenêtre de Claude Code. Sens s’en aperçoit tout seul.",
    codeNote: "Claude Code gère le code et votre session ; Sens ne les voit jamais.",
    signOut: "Se déconnecter",
    check: "Vérifier",
    keySaved: (hint: string) => `Clé enregistrée : ${hint}`,
    removeKey: "Retirer la clé",
    newKey: "Collez une nouvelle clé pour la remplacer",
    apiKey: "Clé API",
    saveKey: "Enregistrer la clé",
    keyNote: "Elle est chiffrée avec votre utilisateur Windows et n’est plus jamais affichée.",
    keyInstalls: (weight: string) => `À l’enregistrement, Sens installe aussi Claude Code depuis Anthropic (${weight}).`,
    stage: { downloading: "Téléchargement de Claude Code…", verifying: "Vérification du téléchargement…", installing: "Installation de Claude Code…", updating: "Mise à jour de Claude Code…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${percent} % de ${total} Mo`,
    signInClaude: "Se connecter avec Claude",
    signInConsole: "Se connecter avec la Console",
    subscription: "Abonnement Claude",
    subscriptionSaid: "Pro ou Max. Vous vous connectez dans le navigateur avec votre compte Claude.",
    console: "Console Anthropic",
    consoleSaid: "Facturation à l’usage. Vous vous connectez avec votre compte Console.",
    apiKeySaid: "Vous collez une clé de la Console. Elle est facturée à l’usage et prime sur l’abonnement.",
    notInstalled: "Claude Code n’est pas installé sur cet ordinateur",
    signedOut: "Non connecté",
    withKey: "Connecté avec une clé API",
    usesSource: (source: string) => `Claude Code utilise ${source}`,
    connected: "Connecté",
    plan: (plan: string) => (plan ? `Abonnement ${plan}` : "Abonnement"),
    noPlan: "sans forfait Pro ni Max",
  },
  de: {
    title: "Einstellungen",
    lead: "Dein Profil, wie Sens aussieht und spricht und mit wem es arbeitet.",
    closeHint: "Schließen (Esc)",
    closeSettings: "Einstellungen schließen",
    sections: "Bereiche der Einstellungen",
    section: { general: "Allgemein", look: "Darstellung", language: "Sprache", providers: "Anbieter" },
    now: "Aktuell",
    accentNote: "Die Farbe zeigt, was Sens gerade tut: den Schnitt, Senden, den laufenden Schritt, den höchsten Aufwand.",
    systemNote: "System folgt dem hellen oder dunklen Modus von Windows.",
    languageNote: "Sens wechselt sofort in diese Sprache. Claude antwortet in der Sprache, in der du schreibst.",
    name: "Name",
    save: "Speichern",
    saved: "Gespeichert.",
    welcome: "Willkommen",
    welcomeNote: "Dein Name, Claude Code und was du aus Claude Code und anderen Apps mitbringst.",
    welcomeAgain: "Erneut ansehen",
    importClaudeCode: "Aus Claude Code importieren",
    updates: "Updates",
    devBuild: "Entwicklungsversion: prüft, installiert aber nicht",
    viewVersion: (version: string) => `Sens ${version} ansehen`,
    checkUpdates: "Nach Updates suchen",
    whatsNew: "Neuigkeiten ansehen",
    notices: "Benachrichtigungen",
    noticesSwitch: "Benachrichtigen, wenn Claude fertig ist oder dich braucht und Sens nicht im Vordergrund ist",
    checkAtStart: "Beim Öffnen von Sens suchen",
    providersLead: "Mit wem Sens arbeitet. Sens sieht deine Zugangsdaten nie: Die Anmeldung übernimmt jedes Werkzeug selbst.",
    checking: "Wird geprüft…",
    moreProviders: "Weitere Anbieter folgen bald.",
    weight: "etwa 230 MB",
    missing: (weight: string) =>
      `Sens nutzt Claude Code, den Agenten von Anthropic. Beim Verbinden lädt Sens ihn von Anthropic herunter (${weight}) und installiert ihn nur für deinen Benutzer, ohne Administratorrechte.`,
    installNow: "Jetzt installieren",
    checkAgain: "Erneut prüfen",
    newer: (version: string) => `Es gibt eine neue Version von Claude Code: v${version}. Die neuesten Modelle erscheinen nur damit.`,
    updateClaudeCode: "Claude Code aktualisieren",
    signsIn: "Anmeldung",
    waiting: "Wartet, bis du fertig bist…",
    installsFirst: (weight: string) => `Sens installiert Claude Code von Anthropic (${weight}).`,
    browserOpens: (site: string) => `Dein Browser öffnet ${site}.`,
    authorize: "Du autorisierst Claude Code und bekommst einen Code.",
    paste: "Falls danach gefragt wird, füge ihn im Fenster von Claude Code ein. Sens merkt es von selbst.",
    codeNote: "Code und Sitzung verwaltet Claude Code; Sens sieht sie nie.",
    signOut: "Abmelden",
    check: "Prüfen",
    keySaved: (hint: string) => `Gespeicherter Schlüssel: ${hint}`,
    removeKey: "Schlüssel entfernen",
    newKey: "Neuen Schlüssel einfügen, um ihn zu ersetzen",
    apiKey: "API-Schlüssel",
    saveKey: "Schlüssel speichern",
    keyNote: "Er wird mit deinem Windows-Benutzer verschlüsselt gespeichert und nie wieder angezeigt.",
    keyInstalls: (weight: string) => `Beim Speichern installiert Sens auch Claude Code von Anthropic (${weight}).`,
    stage: { downloading: "Claude Code wird heruntergeladen…", verifying: "Download wird geprüft…", installing: "Claude Code wird installiert…", updating: "Claude Code wird aktualisiert…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${percent} % von ${total} MB`,
    signInClaude: "Mit Claude anmelden",
    signInConsole: "Mit der Console anmelden",
    subscription: "Claude-Abo",
    subscriptionSaid: "Pro oder Max. Du meldest dich im Browser mit deinem Claude-Konto an.",
    console: "Anthropic Console",
    consoleSaid: "Abrechnung nach Nutzung. Du meldest dich mit deinem Console-Konto an.",
    apiKeySaid: "Du fügst einen Schlüssel aus der Console ein. Abgerechnet wird nach Nutzung, und er hat Vorrang vor dem Abo.",
    notInstalled: "Claude Code fehlt auf diesem Computer",
    signedOut: "Nicht angemeldet",
    withKey: "Mit API-Schlüssel verbunden",
    usesSource: (source: string) => `Claude Code nutzt ${source}`,
    connected: "Verbunden",
    plan: (plan: string) => (plan ? `${plan}-Abo` : "Abo"),
    noPlan: "ohne Pro- oder Max-Tarif",
  },
  ja: {
    title: "設定",
    lead: "プロフィール、Sens の見た目と言語、連携先を設定します。",
    closeHint: "閉じる（Esc）",
    closeSettings: "設定を閉じる",
    sections: "設定のセクション",
    section: { general: "一般", look: "外観", language: "言語", providers: "プロバイダー" },
    now: "現在",
    accentNote: "カラーは Sens の動作を示します。切れ込み、送信ボタン、実行中のステップ、最大に設定した推論の強さに使われます。",
    systemNote: "「システム」は Windows のライト／ダークモードに合わせます。",
    languageNote: "Sens の表示はすぐにこの言語に切り替わります。Claude は入力された言語で返信します。",
    name: "名前",
    save: "保存",
    saved: "保存しました。",
    welcome: "ようこそ",
    welcomeNote: "名前、Claude Code、そして Claude Code やほかのアプリから引き継ぐもの。",
    welcomeAgain: "もう一度見る",
    importClaudeCode: "Claude Code からインポート",
    updates: "アップデート",
    devBuild: "開発ビルド: 確認のみでインストールはしません",
    viewVersion: (version: string) => `Sens ${version} を見る`,
    checkUpdates: "アップデートを確認",
    whatsNew: "新機能を見る",
    notices: "通知",
    noticesSwitch: "Sens がバックグラウンドにあるとき、Claude の完了時や対応が必要なときに通知する",
    checkAtStart: "Sens の起動時に確認する",
    providersLead: "Sens の連携先です。Sens が認証情報を見ることはありません。サインインは各ツールが行います。",
    checking: "確認中…",
    moreProviders: "ほかのプロバイダーにも近日対応します。",
    weight: "約 230 MB",
    missing: (weight: string) =>
      `Sens は Anthropic のエージェント Claude Code を使います。接続すると、Sens が Anthropic から Claude Code をダウンロードし（${weight}）、管理者権限なしで現在のユーザーにのみインストールします。`,
    installNow: "今すぐインストール",
    checkAgain: "もう一度確認",
    newer: (version: string) => `Claude Code の新しいバージョン v${version} があります。最新のモデルはこのバージョンでのみ表示されます。`,
    updateClaudeCode: "Claude Code をアップデート",
    signsIn: "サインイン方法",
    waiting: "完了を待っています…",
    installsFirst: (weight: string) => `Sens が Anthropic から Claude Code をインストールします（${weight}）。`,
    browserOpens: (site: string) => `ブラウザーで ${site} が開きます。`,
    authorize: "Claude Code を承認すると、認証コードが表示されます。",
    paste: "求められたら、Claude Code のウィンドウに貼り付けてください。Sens が自動で検知します。",
    codeNote: "認証コードとセッションは Claude Code が管理します。Sens がそれらを見ることはありません。",
    signOut: "サインアウト",
    check: "確認",
    keySaved: (hint: string) => `保存済みのキー: ${hint}`,
    removeKey: "キーを削除",
    newKey: "新しいキーを貼り付けて置き換え",
    apiKey: "API キー",
    saveKey: "キーを保存",
    keyNote: "Windows のユーザーで暗号化して保存され、二度と表示されません。",
    keyInstalls: (weight: string) => `保存すると、Sens が Anthropic から Claude Code もインストールします（${weight}）。`,
    stage: { downloading: "Claude Code をダウンロードしています…", verifying: "ダウンロードを確認しています…", installing: "Claude Code をインストールしています…", updating: "Claude Code をアップデートしています…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${total} MB 中 ${percent}%`,
    signInClaude: "Claude でサインイン",
    signInConsole: "Console でサインイン",
    subscription: "Claude のサブスクリプション",
    subscriptionSaid: "Pro または Max。ブラウザーで Claude アカウントにサインインします。",
    console: "Anthropic Console",
    consoleSaid: "従量課金。Console のアカウントでサインインします。",
    apiKeySaid: "Console のキーを貼り付けます。従量課金で、サブスクリプションより優先されます。",
    notInstalled: "このコンピューターに Claude Code がありません",
    signedOut: "未サインイン",
    withKey: "API キーで接続済み",
    usesSource: (source: string) => `Claude Code は ${source} を使用しています`,
    connected: "接続済み",
    plan: (plan: string) => (plan ? `${plan} プラン` : "サブスクリプション"),
    noPlan: "Pro・Max プランなし",
  },
  zh: {
    title: "设置",
    lead: "你的个人资料、Sens 的外观和语言，以及它使用的提供商。",
    closeHint: "关闭（Esc）",
    closeSettings: "关闭设置",
    sections: "设置分区",
    section: { general: "通用", look: "外观", language: "语言", providers: "提供商" },
    now: "当前",
    accentNote: "颜色标示 Sens 正在做的事：切口、发送按钮、进行中的步骤、最高推理强度。",
    systemNote: "“跟随系统”会随 Windows 的浅色或深色模式切换。",
    languageNote: "Sens 会立即切换到此语言。Claude 会用你输入的语言回复。",
    name: "名字",
    save: "保存",
    saved: "已保存。",
    welcome: "欢迎",
    welcomeNote: "你的名字、Claude Code，以及从 Claude Code 和其他应用带来的内容。",
    welcomeAgain: "再看一遍",
    importClaudeCode: "从 Claude Code 导入",
    updates: "更新",
    devBuild: "开发版本：只检查，不安装",
    viewVersion: (version: string) => `查看 Sens ${version}`,
    checkUpdates: "检查更新",
    whatsNew: "查看新功能",
    notices: "通知",
    noticesSwitch: "Sens 在后台时，Claude 完成或需要你处理时通知我",
    checkAtStart: "打开 Sens 时检查",
    providersLead: "Sens 使用的提供商。Sens 从不接触你的凭据：登录由各个工具自行完成。",
    checking: "正在检查…",
    moreProviders: "更多提供商即将推出。",
    weight: "约 230 MB",
    missing: (weight: string) => `Sens 使用 Anthropic 的代理 Claude Code。连接时，Sens 会从 Anthropic 下载它（${weight}），仅为当前用户安装，无需管理员权限。`,
    installNow: "立即安装",
    checkAgain: "重新检查",
    newer: (version: string) => `Claude Code 有新版本：v${version}。最新的模型只在新版本中出现。`,
    updateClaudeCode: "更新 Claude Code",
    signsIn: "登录方式",
    waiting: "正在等待你完成…",
    installsFirst: (weight: string) => `Sens 从 Anthropic 安装 Claude Code（${weight}）。`,
    browserOpens: (site: string) => `浏览器会打开 ${site}。`,
    authorize: "你授权 Claude Code 后，会得到一个授权码。",
    paste: "如有提示，把它粘贴到 Claude Code 窗口中。Sens 会自动检测到。",
    codeNote: "授权码和你的会话由 Claude Code 处理；Sens 从不接触。",
    signOut: "退出登录",
    check: "检查",
    keySaved: (hint: string) => `已保存的密钥：${hint}`,
    removeKey: "移除密钥",
    newKey: "粘贴新密钥以替换",
    apiKey: "API 密钥",
    saveKey: "保存密钥",
    keyNote: "密钥会用你的 Windows 用户加密保存，之后不会再显示。",
    keyInstalls: (weight: string) => `保存后，Sens 还会从 Anthropic 安装 Claude Code（${weight}）。`,
    stage: { downloading: "正在下载 Claude Code…", verifying: "正在校验下载…", installing: "正在安装 Claude Code…", updating: "正在更新 Claude Code…" },
    downloaded: (stage: string, percent: number, total: number) => `${stage} ${percent}%，共 ${total} MB`,
    signInClaude: "使用 Claude 登录",
    signInConsole: "使用 Console 登录",
    subscription: "Claude 订阅",
    subscriptionSaid: "Pro 或 Max。在浏览器中用你的 Claude 账号登录。",
    console: "Anthropic Console",
    consoleSaid: "按用量计费。使用你的 Console 账号登录。",
    apiKeySaid: "粘贴来自 Console 的密钥。按用量计费，优先于订阅。",
    notInstalled: "这台电脑上没有 Claude Code",
    signedOut: "未登录",
    withKey: "已通过 API 密钥连接",
    usesSource: (source: string) => `Claude Code 使用 ${source}`,
    connected: "已连接",
    plan: (plan: string) => (plan ? `${plan} 订阅` : "订阅"),
    noPlan: "无 Pro 或 Max 套餐",
  },
});
