import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    taglines: {
      "Best for everyday, complex tasks": "Best for everyday, complex tasks",
      "Most capable for your hardest and longest-running tasks": "Most capable for your hardest and longest-running tasks",
      "Efficient for routine tasks": "Efficient for routine tasks",
      "Fastest for quick answers": "Fastest for quick answers",
    },
    missing: "Claude Code is missing",
    model: "model",
    subscription: (plan: string) => (plan ? `${plan} subscription` : "Subscription"),
    noPlan: "no Pro or Max plan",
    consoleKey: "Console API key",
    elsewhere: (source: string) => `Claude Code uses ${source}, not your subscription`,
    signedOut: "Claude Code isn’t signed in",
    percent: (value: number) => `${value}%`,
    usedFiveHour: (percent: string) => `${percent} used in 5 h`,
    usedWeek: (percent: string) => `${percent} used this week`,
    usedWeekOf: (percent: string, model: string) => `${percent} used this week (${model})`,
    usedOf: (percent: string, name: string) => `${percent} used · ${name}`,
    fiveHour: "5-hour limit",
    fiveHourOf: (model: string) => `5-hour · ${model}`,
    weekly: "Weekly · all models",
    weeklyOf: (model: string) => `Weekly · ${model}`,
    resetsIn: (span: string) => `Resets in ${span}`,
    resetsOn: (day: string, time: string) => `Resets ${day} ${time}`,
    alreadyReset: "Already reset",
    reached: "Limit reached",
    asOf: (time: string) => `As of ${time}`,
    asOfDay: (when: string) => `As of ${when}`,
    overageOn: "Using extra usage",
    overageNear: "Extra usage nearly used up",
    overageOut: "Extra usage used up",
    near: "Near a plan limit",
    over: "Plan limit reached",
    context: "Context",
    contextUsed: (percent: string) => `Context used: ${percent}`,
    contextTitle: (said: string) => `Context: ${said}`,
    contextOf: (used: string, window: string) => `${used} of ${window} tokens`,
    compactSaid: "Compacting summarizes the conversation so far to free up space. The session stays the same.",
    compactNow: "Compact now",
    session: "This session",
    tokensIn: "Tokens in",
    tokensOut: "Tokens out",
    replies: "Replies",
    working: "Time working",
    plan: "Plan usage limits",
    planOf: (plan: string) => `Plan usage limits · ${plan}`,
    pending: "Limits show after Claude’s first reply.",
  },
  es: {
    taglines: {
      "Best for everyday, complex tasks": "El mejor para el trabajo complejo de cada día",
      "Most capable for your hardest and longest-running tasks": "El más capaz para las tareas más difíciles y largas",
      "Efficient for routine tasks": "Eficiente para tareas rutinarias",
      "Fastest for quick answers": "El más rápido para respuestas cortas",
    },
    missing: "Falta Claude Code",
    model: "modelo",
    subscription: (plan: string) => `Suscripción ${plan}`.trim(),
    noPlan: "sin plan Pro ni Max",
    consoleKey: "Clave de API de la Consola",
    elsewhere: (source: string) => `Claude Code usa ${source}, no tu suscripción`,
    signedOut: "Claude Code no tiene sesión",
    percent: (value: number) => `${value} %`,
    usedFiveHour: (percent: string) => `${percent} usado en 5 h`,
    usedWeek: (percent: string) => `${percent} usado en la semana`,
    usedWeekOf: (percent: string, model: string) => `${percent} usado en la semana (${model})`,
    usedOf: (percent: string, name: string) => `${percent} usado · ${name}`,
    fiveHour: "Límite de 5 horas",
    fiveHourOf: (model: string) => `5 horas · ${model}`,
    weekly: "Semanal · todos los modelos",
    weeklyOf: (model: string) => `Semanal · ${model}`,
    resetsIn: (span: string) => `Se restablece en ${span}`,
    resetsOn: (day: string, time: string) => `Se restablece el ${day}, ${time}`,
    alreadyReset: "Ya se ha restablecido",
    reached: "Límite alcanzado",
    asOf: (time: string) => `Actualizado ${time.startsWith("1:") ? "a la" : "a las"} ${time}`,
    asOfDay: (when: string) => `Actualizado el ${when}`,
    overageOn: "Consumiendo uso extra",
    overageNear: "Uso extra casi agotado",
    overageOut: "Uso extra agotado",
    near: "Cerca de un límite del plan",
    over: "Límite del plan alcanzado",
    context: "Contexto",
    contextUsed: (percent: string) => `Contexto usado: ${percent}`,
    contextTitle: (said: string) => `Contexto: ${said}`,
    contextOf: (used: string, window: string) => `${used} de ${window} tokens`,
    compactSaid: "Compactar resume lo hablado para liberar espacio. La sesión sigue siendo la misma.",
    compactNow: "Compactar ahora",
    session: "Esta sesión",
    tokensIn: "Tokens de entrada",
    tokensOut: "Tokens de salida",
    replies: "Respuestas",
    working: "Tiempo trabajando",
    plan: "Límites de uso del plan",
    planOf: (plan: string) => `Límites de uso del plan · ${plan}`,
    pending: "Los límites aparecen tras la primera respuesta de Claude.",
  },
  fr: {
    taglines: {
      "Best for everyday, complex tasks": "Le meilleur pour les tâches complexes du quotidien",
      "Most capable for your hardest and longest-running tasks": "Le plus capable pour les tâches les plus difficiles et les plus longues",
      "Efficient for routine tasks": "Efficace pour les tâches courantes",
      "Fastest for quick answers": "Le plus rapide pour les réponses courtes",
    },
    missing: "Claude Code est introuvable",
    model: "modèle",
    subscription: (plan: string) => `Abonnement ${plan}`.trim(),
    noPlan: "sans forfait Pro ni Max",
    consoleKey: "Clé API de la Console",
    elsewhere: (source: string) => `Claude Code utilise ${source}, pas votre abonnement`,
    signedOut: "Claude Code n’est pas connecté",
    percent: (value: number) => `${value} %`,
    usedFiveHour: (percent: string) => `${percent} utilisés sur 5 h`,
    usedWeek: (percent: string) => `${percent} utilisés cette semaine`,
    usedWeekOf: (percent: string, model: string) => `${percent} utilisés cette semaine (${model})`,
    usedOf: (percent: string, name: string) => `${percent} utilisés · ${name}`,
    fiveHour: "Limite sur 5 heures",
    fiveHourOf: (model: string) => `5 heures · ${model}`,
    weekly: "Hebdomadaire · tous les modèles",
    weeklyOf: (model: string) => `Hebdomadaire · ${model}`,
    resetsIn: (span: string) => `Se réinitialise dans ${span}`,
    resetsOn: (day: string, time: string) => `Se réinitialise ${day} à ${time}`,
    alreadyReset: "Déjà réinitialisée",
    reached: "Limite atteinte",
    asOf: (time: string) => `Mis à jour à ${time}`,
    asOfDay: (when: string) => `Mis à jour le ${when}`,
    overageOn: "Usage supplémentaire en cours",
    overageNear: "Usage supplémentaire presque épuisé",
    overageOut: "Usage supplémentaire épuisé",
    near: "Limite du forfait proche",
    over: "Limite du forfait atteinte",
    context: "Contexte",
    contextUsed: (percent: string) => `Contexte utilisé : ${percent}`,
    contextTitle: (said: string) => `Contexte : ${said}`,
    contextOf: (used: string, window: string) => `${used} sur ${window} tokens`,
    compactSaid: "Compacter résume la conversation pour libérer de l’espace. La session reste la même.",
    compactNow: "Compacter maintenant",
    session: "Cette session",
    tokensIn: "Tokens en entrée",
    tokensOut: "Tokens en sortie",
    replies: "Réponses",
    working: "Temps de travail",
    plan: "Limites d’utilisation du forfait",
    planOf: (plan: string) => `Limites d’utilisation du forfait · ${plan}`,
    pending: "Les limites s’affichent après la première réponse de Claude.",
  },
  de: {
    taglines: {
      "Best for everyday, complex tasks": "Am besten für komplexe Alltagsaufgaben",
      "Most capable for your hardest and longest-running tasks": "Am leistungsfähigsten für die schwierigsten und längsten Aufgaben",
      "Efficient for routine tasks": "Effizient für Routineaufgaben",
      "Fastest for quick answers": "Am schnellsten für kurze Antworten",
    },
    missing: "Claude Code fehlt",
    model: "Modell",
    subscription: (plan: string) => (plan ? `${plan}-Abo` : "Abo"),
    noPlan: "kein Pro- oder Max-Tarif",
    consoleKey: "API-Schlüssel der Console",
    elsewhere: (source: string) => `Claude Code nutzt ${source}, nicht dein Abo`,
    signedOut: "Claude Code ist nicht angemeldet",
    percent: (value: number) => `${value} %`,
    usedFiveHour: (percent: string) => `${percent} in 5 h genutzt`,
    usedWeek: (percent: string) => `${percent} diese Woche genutzt`,
    usedWeekOf: (percent: string, model: string) => `${percent} diese Woche genutzt (${model})`,
    usedOf: (percent: string, name: string) => `${percent} genutzt · ${name}`,
    fiveHour: "5-Stunden-Limit",
    fiveHourOf: (model: string) => `5 Stunden · ${model}`,
    weekly: "Wöchentlich · alle Modelle",
    weeklyOf: (model: string) => `Wöchentlich · ${model}`,
    resetsIn: (span: string) => `Wird in ${span} zurückgesetzt`,
    resetsOn: (day: string, time: string) => `Wird am ${day} um ${time} zurückgesetzt`,
    alreadyReset: "Bereits zurückgesetzt",
    reached: "Limit erreicht",
    asOf: (time: string) => `Stand: ${time}`,
    asOfDay: (when: string) => `Stand: ${when}`,
    overageOn: "Zusatznutzung aktiv",
    overageNear: "Zusatznutzung fast aufgebraucht",
    overageOut: "Zusatznutzung aufgebraucht",
    near: "Tariflimit bald erreicht",
    over: "Tariflimit erreicht",
    context: "Kontext",
    contextUsed: (percent: string) => `Kontext belegt: ${percent}`,
    contextTitle: (said: string) => `Kontext: ${said}`,
    contextOf: (used: string, window: string) => `${used} von ${window} Tokens`,
    compactSaid: "Komprimieren fasst die bisherige Unterhaltung zusammen und schafft Platz. Die Sitzung bleibt dieselbe.",
    compactNow: "Jetzt komprimieren",
    session: "Diese Sitzung",
    tokensIn: "Eingabe-Tokens",
    tokensOut: "Ausgabe-Tokens",
    replies: "Antworten",
    working: "Arbeitszeit",
    plan: "Nutzungslimits des Tarifs",
    planOf: (plan: string) => `Nutzungslimits des Tarifs · ${plan}`,
    pending: "Die Limits erscheinen nach Claudes erster Antwort.",
  },
  ja: {
    taglines: {
      "Best for everyday, complex tasks": "日々の複雑な作業に最適",
      "Most capable for your hardest and longest-running tasks": "最高性能。難しく長時間かかる作業向け",
      "Efficient for routine tasks": "定型作業を効率よくこなす",
      "Fastest for quick answers": "最速。すばやい回答向け",
    },
    missing: "Claude Code が見つかりません",
    model: "モデル",
    subscription: (plan: string) => (plan ? `${plan} プラン` : "サブスクリプション"),
    noPlan: "Pro・Max プランなし",
    consoleKey: "Console の API キー",
    elsewhere: (source: string) => `Claude Code はサブスクリプションではなく ${source} を使っています`,
    signedOut: "Claude Code はサインインしていません",
    percent: (value: number) => `${value}%`,
    usedFiveHour: (percent: string) => `5 時間で ${percent} 使用`,
    usedWeek: (percent: string) => `今週 ${percent} 使用`,
    usedWeekOf: (percent: string, model: string) => `今週 ${percent} 使用（${model}）`,
    usedOf: (percent: string, name: string) => `${percent} 使用 · ${name}`,
    fiveHour: "5 時間の上限",
    fiveHourOf: (model: string) => `5 時間 · ${model}`,
    weekly: "週間 · すべてのモデル",
    weeklyOf: (model: string) => `週間 · ${model}`,
    resetsIn: (span: string) => `${span}後にリセット`,
    resetsOn: (day: string, time: string) => `${day}曜 ${time} にリセット`,
    alreadyReset: "リセット済み",
    reached: "上限に達しました",
    asOf: (time: string) => `${time} 時点`,
    asOfDay: (when: string) => `${when} 時点`,
    overageOn: "追加使用量を使用中",
    overageNear: "追加使用量が残りわずかです",
    overageOut: "追加使用量を使い切りました",
    near: "プランの上限が近づいています",
    over: "プランの上限に達しました",
    context: "コンテキスト",
    contextUsed: (percent: string) => `コンテキスト使用率: ${percent}`,
    contextTitle: (said: string) => `コンテキスト: ${said}`,
    contextOf: (used: string, window: string) => `${window} トークン中 ${used}`,
    compactSaid: "圧縮すると、これまでの会話を要約して空きを作ります。セッションはそのまま続きます。",
    compactNow: "今すぐ圧縮",
    session: "このセッション",
    tokensIn: "入力トークン",
    tokensOut: "出力トークン",
    replies: "返信",
    working: "作業時間",
    plan: "プランの使用量の上限",
    planOf: (plan: string) => `プランの使用量の上限 · ${plan}`,
    pending: "上限は Claude の最初の返信のあとに表示されます。",
  },
  zh: {
    taglines: {
      "Best for everyday, complex tasks": "最适合日常的复杂任务",
      "Most capable for your hardest and longest-running tasks": "最强大，适合最难、耗时最长的任务",
      "Efficient for routine tasks": "高效处理日常任务",
      "Fastest for quick answers": "最快，适合简短回答",
    },
    missing: "未找到 Claude Code",
    model: "模型",
    subscription: (plan: string) => (plan ? `${plan} 订阅` : "订阅"),
    noPlan: "无 Pro 或 Max 套餐",
    consoleKey: "Console API 密钥",
    elsewhere: (source: string) => `Claude Code 使用的是 ${source}，而不是你的订阅`,
    signedOut: "Claude Code 未登录",
    percent: (value: number) => `${value}%`,
    usedFiveHour: (percent: string) => `5 小时内已用 ${percent}`,
    usedWeek: (percent: string) => `本周已用 ${percent}`,
    usedWeekOf: (percent: string, model: string) => `本周已用 ${percent}（${model}）`,
    usedOf: (percent: string, name: string) => `已用 ${percent} · ${name}`,
    fiveHour: "5 小时限制",
    fiveHourOf: (model: string) => `5 小时 · ${model}`,
    weekly: "每周 · 所有模型",
    weeklyOf: (model: string) => `每周 · ${model}`,
    resetsIn: (span: string) => `${span}后重置`,
    resetsOn: (day: string, time: string) => `${day} ${time} 重置`,
    alreadyReset: "已重置",
    reached: "已达上限",
    asOf: (time: string) => `截至 ${time}`,
    asOfDay: (when: string) => `截至 ${when}`,
    overageOn: "正在使用额外用量",
    overageNear: "额外用量即将用完",
    overageOut: "额外用量已用完",
    near: "接近套餐限制",
    over: "已达套餐限制",
    context: "上下文",
    contextUsed: (percent: string) => `上下文已用：${percent}`,
    contextTitle: (said: string) => `上下文：${said}`,
    contextOf: (used: string, window: string) => `已用 ${used} / ${window} token`,
    compactSaid: "压缩会总结目前的对话以腾出空间，会话保持不变。",
    compactNow: "立即压缩",
    session: "本次会话",
    tokensIn: "输入 token",
    tokensOut: "输出 token",
    replies: "回复",
    working: "工作时长",
    plan: "套餐用量限制",
    planOf: (plan: string) => `套餐用量限制 · ${plan}`,
    pending: "Claude 首次回复后显示限制。",
  },
});
