import { copy } from "../../shared/i18n";

const joined = (parts: string[], comma: string, and: string) => (parts.length < 2 ? parts.join("") : `${parts.slice(0, -1).join(comma)}${and}${parts[parts.length - 1]}`);

export const t = copy({
  en: {
    dialog: "Welcome to Sens",
    skip: "Skip the welcome",
    step: (at: number, of: number) => `Step ${at} of ${of}`,
    today: "today",
    hello: "Welcome.",
    tagline: "Understand more. Read less.",
    helloNote: "In a minute we’ll make Sens yours: your name, Claude Code and what you already have.",
    start: "Start",
    askName: "What’s your name?",
    yourName: "Your name",
    nameHint: "It shows in the sidebar. You can leave it blank.",
    next: "Continue",
    notNow: "Not now",
    usesClaude: "Sens uses Claude Code.",
    usesClaudeLead: "With your own account. Your credentials and your session stay in Claude Code; Sens never sees them.",
    checkingClaude: "Checking Claude Code…",
    later: "Do it later",
    change: "Change",
    bring: "Bring what you already have.",
    scanAgain: "Search again",
    skipImport: "Continue without importing",
    lookingIn: { before: "Looking in ", after: "…" },
    nothing: "There’s nothing to bring. You’re starting fresh.",
    import: "Import",
    gone: "the folder no longer exists",
    allThere: "already in Sens",
    sessions: (count: number) => (count === 1 ? "1 session" : `${count} sessions`),
    alreadyIn: (count: number) => `${count} already in Sens`,
    claudeSessions: "Claude Code sessions",
    sessionsIn: (sessions: number, projects: number) => `${sessions === 1 ? "1 session" : `${sessions} sessions`} in ${projects === 1 ? "1 project" : `${projects} projects`}`,
    none: "Select none",
    all: "Select all",
    active: "From Claude Code, already active",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [
        skills ? (skills === 1 ? "1 skill" : `${skills} skills`) : "",
        servers ? (servers === 1 ? "1 MCP server" : `${servers} MCP servers`) : "",
        plugins ? (plugins === 1 ? "1 plugin" : `${plugins} plugins`) : "",
      ].filter(Boolean);
      const one = skills + servers + plugins === 1;
      return `${joined(parts, ", ", " and ")} already ${one ? "works" : "work"} in Sens: Claude Code loads ${one ? "it" : "them"} in every session.`;
    },
    seeNames: "See names",
    carries: (keys: string) => `carries ${keys}`,
    otherApps: "MCP servers from other apps",
    serversHint: "They’re added to Capabilities and turned on in the projects you bring.",
    whichProject: "Which project shall we start with?",
    project: "Project",
    pickLead: "Choose a project folder. You can open others whenever you like.",
    otherFolder: "Choose another folder…",
    pickTitle: "Choose the project folder",
    preparing: "Getting your space ready.",
    allSet: (first: string) => (first ? `All set, ${first}.` : "All set."),
    shortcuts: "Shortcuts",
    openFolder: "Open folder",
    sidebar: "Sidebar",
    openSens: "Open Sens",
    noName: "No name",
    unchecked: "Claude Code not checked",
    sessionWord: (count: number) => (count === 1 ? "session" : "sessions"),
    projectWord: (count: number) => (count === 1 ? "project" : "projects"),
    savingName: "Saving your name…",
    nameSaved: (name: string) => `Name saved · ${name}`,
    importing: "Importing sessions…",
    importingCount: (done: number, total: number) => `Importing sessions · ${done} of ${total}`,
    imported: (sessions: number, projects: number) =>
      `${sessions === 1 ? "1 session" : `${sessions} sessions`} imported into ${projects === 1 ? "1 project" : `${projects} projects`}`,
    addingServers: "Adding MCP servers…",
    serversAdded: (count: number) => (count === 1 ? "1 MCP server added" : `${count} MCP servers added`),
  },
  es: {
    dialog: "Bienvenida a Sens",
    skip: "Saltar la bienvenida",
    step: (at: number, of: number) => `Paso ${at} de ${of}`,
    today: "hoy",
    hello: "Te damos la bienvenida.",
    tagline: "Entiende más. Lee menos.",
    helloNote: "En un minuto dejamos Sens a tu gusto: tu nombre, Claude Code y lo que ya tienes.",
    start: "Empezar",
    askName: "¿Cómo te llamas?",
    yourName: "Tu nombre",
    nameHint: "Sale en la barra lateral. Puedes dejarlo en blanco.",
    next: "Continuar",
    notNow: "Ahora no",
    usesClaude: "Sens usa Claude Code.",
    usesClaudeLead: "Con tu propia cuenta. Tus credenciales y tu sesión se quedan en Claude Code; Sens nunca las ve.",
    checkingClaude: "Comprobando Claude Code…",
    later: "Hacerlo más tarde",
    change: "Cambiar",
    bring: "Trae lo que ya tienes.",
    scanAgain: "Buscar otra vez",
    skipImport: "Continuar sin importar",
    lookingIn: { before: "Buscando en ", after: "…" },
    nothing: "No hay nada que traer. Empiezas de cero.",
    import: "Importar",
    gone: "la carpeta ya no existe",
    allThere: "ya están en Sens",
    sessions: (count: number) => (count === 1 ? "1 sesión" : `${count} sesiones`),
    alreadyIn: (count: number) => `${count} ya en Sens`,
    claudeSessions: "Sesiones de Claude Code",
    sessionsIn: (sessions: number, projects: number) => `${sessions === 1 ? "1 sesión" : `${sessions} sesiones`} en ${projects === 1 ? "1 proyecto" : `${projects} proyectos`}`,
    none: "Ninguno",
    all: "Marcar todos",
    active: "De Claude Code, ya activo",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [
        skills ? (skills === 1 ? "1 skill" : `${skills} skills`) : "",
        servers ? (servers === 1 ? "1 servidor MCP" : `${servers} servidores MCP`) : "",
        plugins ? (plugins === 1 ? "1 plugin" : `${plugins} plugins`) : "",
      ].filter(Boolean);
      const one = skills + servers + plugins === 1;
      return `${joined(parts, ", ", " y ")} ya ${one ? "funciona" : "funcionan"} en Sens: Claude Code ${one ? "lo carga" : "los carga"} en cada sesión.`;
    },
    seeNames: "Ver nombres",
    carries: (keys: string) => `lleva ${keys}`,
    otherApps: "Servidores MCP de otras apps",
    serversHint: "Se añaden a Capacidades y se activan en los proyectos que traes.",
    whichProject: "¿Con qué proyecto empezamos?",
    project: "Proyecto",
    pickLead: "Elige la carpeta de un proyecto. Podrás abrir otros cuando quieras.",
    otherFolder: "Elegir otra carpeta…",
    pickTitle: "Elige la carpeta del proyecto",
    preparing: "Preparando tu espacio.",
    allSet: (first: string) => (first ? `Todo listo, ${first}.` : "Todo listo."),
    shortcuts: "Atajos",
    openFolder: "Abrir carpeta",
    sidebar: "Barra lateral",
    openSens: "Abrir Sens",
    noName: "Sin nombre",
    unchecked: "Claude Code sin comprobar",
    sessionWord: (count: number) => (count === 1 ? "sesión" : "sesiones"),
    projectWord: (count: number) => (count === 1 ? "proyecto" : "proyectos"),
    savingName: "Guardando tu nombre…",
    nameSaved: (name: string) => `Nombre guardado · ${name}`,
    importing: "Importando sesiones…",
    importingCount: (done: number, total: number) => `Importando sesiones · ${done} de ${total}`,
    imported: (sessions: number, projects: number) =>
      `${sessions === 1 ? "1 sesión importada" : `${sessions} sesiones importadas`} en ${projects === 1 ? "1 proyecto" : `${projects} proyectos`}`,
    addingServers: "Añadiendo servidores MCP…",
    serversAdded: (count: number) => (count === 1 ? "1 servidor MCP añadido" : `${count} servidores MCP añadidos`),
  },
  fr: {
    dialog: "Bienvenue dans Sens",
    skip: "Passer l’accueil",
    step: (at: number, of: number) => `Étape ${at} sur ${of}`,
    today: "aujourd’hui",
    hello: "Bienvenue.",
    tagline: "Comprenez mieux. Lisez moins.",
    helloNote: "En une minute, Sens est à votre goût : votre nom, Claude Code et ce que vous avez déjà.",
    start: "Commencer",
    askName: "Comment vous appelez-vous ?",
    yourName: "Votre nom",
    nameHint: "Il s’affiche dans la barre latérale. Vous pouvez le laisser vide.",
    next: "Continuer",
    notNow: "Pas maintenant",
    usesClaude: "Sens utilise Claude Code.",
    usesClaudeLead: "Avec votre propre compte. Vos identifiants et votre session restent dans Claude Code ; Sens ne les voit jamais.",
    checkingClaude: "Vérification de Claude Code…",
    later: "Plus tard",
    change: "Modifier",
    bring: "Apportez ce que vous avez déjà.",
    scanAgain: "Rechercher à nouveau",
    skipImport: "Continuer sans importer",
    lookingIn: { before: "Recherche dans ", after: "…" },
    nothing: "Rien à apporter. Vous partez de zéro.",
    import: "Importer",
    gone: "le dossier n’existe plus",
    allThere: "déjà dans Sens",
    sessions: (count: number) => (count <= 1 ? `${count} session` : `${count} sessions`),
    alreadyIn: (count: number) => `${count} déjà dans Sens`,
    claudeSessions: "Sessions de Claude Code",
    sessionsIn: (sessions: number, projects: number) => `${sessions <= 1 ? `${sessions} session` : `${sessions} sessions`} dans ${projects <= 1 ? `${projects} projet` : `${projects} projets`}`,
    none: "Tout décocher",
    all: "Tout cocher",
    active: "De Claude Code, déjà actif",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [
        skills ? (skills === 1 ? "1 skill" : `${skills} skills`) : "",
        servers ? (servers === 1 ? "1 serveur MCP" : `${servers} serveurs MCP`) : "",
        plugins ? (plugins === 1 ? "1 plugin" : `${plugins} plugins`) : "",
      ].filter(Boolean);
      const one = skills + servers + plugins === 1;
      return `${joined(parts, ", ", " et ")} ${one ? "fonctionne" : "fonctionnent"} déjà dans Sens : Claude Code ${one ? "le charge" : "les charge"} à chaque session.`;
    },
    seeNames: "Voir les noms",
    carries: (keys: string) => `utilise ${keys}`,
    otherApps: "Serveurs MCP d’autres apps",
    serversHint: "Ils sont ajoutés aux Capacités et activés dans les projets que vous apportez.",
    whichProject: "Par quel projet commençons-nous ?",
    project: "Projet",
    pickLead: "Choisissez le dossier d’un projet. Vous pourrez en ouvrir d’autres quand vous voudrez.",
    otherFolder: "Choisir un autre dossier…",
    pickTitle: "Choisissez le dossier du projet",
    preparing: "Préparation de votre espace.",
    allSet: (first: string) => (first ? `Tout est prêt, ${first}.` : "Tout est prêt."),
    shortcuts: "Raccourcis",
    openFolder: "Ouvrir un dossier",
    sidebar: "Barre latérale",
    openSens: "Ouvrir Sens",
    noName: "Sans nom",
    unchecked: "Claude Code non vérifié",
    sessionWord: (count: number) => (count <= 1 ? "session" : "sessions"),
    projectWord: (count: number) => (count <= 1 ? "projet" : "projets"),
    savingName: "Enregistrement de votre nom…",
    nameSaved: (name: string) => `Nom enregistré · ${name}`,
    importing: "Importation des sessions…",
    importingCount: (done: number, total: number) => `Importation des sessions · ${done} sur ${total}`,
    imported: (sessions: number, projects: number) =>
      `${sessions <= 1 ? `${sessions} session importée` : `${sessions} sessions importées`} dans ${projects <= 1 ? `${projects} projet` : `${projects} projets`}`,
    addingServers: "Ajout des serveurs MCP…",
    serversAdded: (count: number) => (count <= 1 ? `${count} serveur MCP ajouté` : `${count} serveurs MCP ajoutés`),
  },
  de: {
    dialog: "Willkommen bei Sens",
    skip: "Begrüßung überspringen",
    step: (at: number, of: number) => `Schritt ${at} von ${of}`,
    today: "heute",
    hello: "Willkommen.",
    tagline: "Mehr verstehen. Weniger lesen.",
    helloNote: "In einer Minute richten wir Sens für dich ein: dein Name, Claude Code und was du schon hast.",
    start: "Los geht’s",
    askName: "Wie heißt du?",
    yourName: "Dein Name",
    nameHint: "Er erscheint in der Seitenleiste. Du kannst ihn leer lassen.",
    next: "Weiter",
    notNow: "Nicht jetzt",
    usesClaude: "Sens nutzt Claude Code.",
    usesClaudeLead: "Mit deinem eigenen Konto. Zugangsdaten und Sitzung bleiben in Claude Code; Sens sieht sie nie.",
    checkingClaude: "Claude Code wird geprüft…",
    later: "Später erledigen",
    change: "Ändern",
    bring: "Bring mit, was du schon hast.",
    scanAgain: "Erneut suchen",
    skipImport: "Ohne Import weiter",
    lookingIn: { before: "Suche in ", after: "…" },
    nothing: "Es gibt nichts mitzubringen. Du fängst neu an.",
    import: "Importieren",
    gone: "der Ordner existiert nicht mehr",
    allThere: "schon in Sens",
    sessions: (count: number) => (count === 1 ? "1 Sitzung" : `${count} Sitzungen`),
    alreadyIn: (count: number) => `${count} schon in Sens`,
    claudeSessions: "Sitzungen aus Claude Code",
    sessionsIn: (sessions: number, projects: number) => `${sessions === 1 ? "1 Sitzung" : `${sessions} Sitzungen`} in ${projects === 1 ? "1 Projekt" : `${projects} Projekten`}`,
    none: "Keine auswählen",
    all: "Alle auswählen",
    active: "Aus Claude Code, schon aktiv",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [
        skills ? (skills === 1 ? "1 Skill" : `${skills} Skills`) : "",
        servers ? `${servers} MCP-Server` : "",
        plugins ? (plugins === 1 ? "1 Plugin" : `${plugins} Plugins`) : "",
      ].filter(Boolean);
      const one = skills + servers + plugins === 1;
      const it = plugins ? "es" : "ihn";
      return `${joined(parts, ", ", " und ")} ${one ? "funktioniert" : "funktionieren"} schon in Sens: Claude Code lädt ${one ? it : "sie"} in jeder Sitzung.`;
    },
    seeNames: "Namen anzeigen",
    carries: (keys: string) => `enthält ${keys}`,
    otherApps: "MCP-Server aus anderen Apps",
    serversHint: "Die Server werden zu den Fähigkeiten hinzugefügt und in den mitgebrachten Projekten aktiviert.",
    whichProject: "Mit welchem Projekt fangen wir an?",
    project: "Projekt",
    pickLead: "Wähle den Ordner eines Projekts. Andere kannst du jederzeit öffnen.",
    otherFolder: "Anderen Ordner wählen…",
    pickTitle: "Wähle den Projektordner",
    preparing: "Dein Bereich wird vorbereitet.",
    allSet: (first: string) => (first ? `Alles bereit, ${first}.` : "Alles bereit."),
    shortcuts: "Tastenkürzel",
    openFolder: "Ordner öffnen",
    sidebar: "Seitenleiste",
    openSens: "Sens öffnen",
    noName: "Kein Name",
    unchecked: "Claude Code nicht geprüft",
    sessionWord: (count: number) => (count === 1 ? "Sitzung" : "Sitzungen"),
    projectWord: (count: number) => (count === 1 ? "Projekt" : "Projekte"),
    savingName: "Dein Name wird gespeichert…",
    nameSaved: (name: string) => `Name gespeichert · ${name}`,
    importing: "Sitzungen werden importiert…",
    importingCount: (done: number, total: number) => `Sitzungen werden importiert · ${done} von ${total}`,
    imported: (sessions: number, projects: number) =>
      `${sessions === 1 ? "1 Sitzung" : `${sessions} Sitzungen`} in ${projects === 1 ? "1 Projekt" : `${projects} Projekte`} importiert`,
    addingServers: "MCP-Server werden hinzugefügt…",
    serversAdded: (count: number) => `${count} MCP-Server hinzugefügt`,
  },
  ja: {
    dialog: "Sens へようこそ",
    skip: "ようこそ画面をスキップ",
    step: (at: number, of: number) => `ステップ ${at}/${of}`,
    today: "今日",
    hello: "ようこそ。",
    tagline: "理解は深く、読むのは少なく。",
    helloNote: "1 分で Sens をあなた好みに整えます。名前、Claude Code、そしてすでにあるものを設定します。",
    start: "始める",
    askName: "お名前は？",
    yourName: "お名前",
    nameHint: "サイドバーに表示されます。空欄のままでもかまいません。",
    next: "続ける",
    notNow: "今はしない",
    usesClaude: "Sens は Claude Code を使います。",
    usesClaudeLead: "ご自身のアカウントで使います。認証情報とセッションは Claude Code の中にとどまり、Sens がそれを見ることはありません。",
    checkingClaude: "Claude Code を確認しています…",
    later: "あとで設定する",
    change: "変更",
    bring: "今あるものを引き継ぎましょう。",
    scanAgain: "もう一度探す",
    skipImport: "インポートせずに続ける",
    lookingIn: { before: "", after: " を探しています…" },
    nothing: "引き継ぐものはありません。ゼロから始めましょう。",
    import: "インポート",
    gone: "フォルダーが存在しません",
    allThere: "すでに Sens にあります",
    sessions: (count: number) => `${count} 件のセッション`,
    alreadyIn: (count: number) => `${count} 件はすでに Sens にあります`,
    claudeSessions: "Claude Code のセッション",
    sessionsIn: (sessions: number, projects: number) => `${projects} 個のプロジェクトにある ${sessions} 件のセッション`,
    none: "すべて解除",
    all: "すべて選択",
    active: "Claude Code から、すでに有効",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [skills ? `${skills} 個のスキル` : "", servers ? `${servers} 個の MCP サーバー` : "", plugins ? `${plugins} 個のプラグイン` : ""].filter(Boolean);
      return `${parts.join("、")}はすでに Sens で使えます。Claude Code が各セッションで読み込みます。`;
    },
    seeNames: "名前を表示",
    carries: (keys: string) => `${keys} を含む`,
    otherApps: "ほかのアプリの MCP サーバー",
    serversHint: "「機能」に追加され、引き継いだプロジェクトで有効になります。",
    whichProject: "どのプロジェクトから始めますか？",
    project: "プロジェクト",
    pickLead: "プロジェクトフォルダーを選んでください。ほかのプロジェクトはいつでも開けます。",
    otherFolder: "別のフォルダーを選ぶ…",
    pickTitle: "プロジェクトフォルダーを選択",
    preparing: "スペースを準備しています。",
    allSet: (first: string) => (first ? `準備ができました、${first} さん。` : "準備ができました。"),
    shortcuts: "ショートカット",
    openFolder: "フォルダーを開く",
    sidebar: "サイドバー",
    openSens: "Sens を開く",
    noName: "名前なし",
    unchecked: "Claude Code は未確認",
    sessionWord: () => "セッション",
    projectWord: () => "プロジェクト",
    savingName: "名前を保存しています…",
    nameSaved: (name: string) => `名前を保存しました · ${name}`,
    importing: "セッションをインポートしています…",
    importingCount: (done: number, total: number) => `セッションをインポートしています · ${done}/${total}`,
    imported: (sessions: number, projects: number) => `${sessions} 件のセッションを ${projects} 個のプロジェクトにインポートしました`,
    addingServers: "MCP サーバーを追加しています…",
    serversAdded: (count: number) => `${count} 個の MCP サーバーを追加しました`,
  },
  zh: {
    dialog: "欢迎使用 Sens",
    skip: "跳过欢迎页",
    step: (at: number, of: number) => `第 ${at} 步，共 ${of} 步`,
    today: "今天",
    hello: "欢迎。",
    tagline: "理解更多，阅读更少。",
    helloNote: "一分钟就能让 Sens 合你心意：你的名字、Claude Code，以及你已有的内容。",
    start: "开始",
    askName: "你叫什么名字？",
    yourName: "你的名字",
    nameHint: "它会显示在侧边栏中。可以留空。",
    next: "继续",
    notNow: "暂不",
    usesClaude: "Sens 使用 Claude Code。",
    usesClaudeLead: "使用你自己的账号。你的凭据和会话都留在 Claude Code 中，Sens 从不接触。",
    checkingClaude: "正在检查 Claude Code…",
    later: "稍后再说",
    change: "更改",
    bring: "带上你已有的内容。",
    scanAgain: "重新查找",
    skipImport: "不导入，继续",
    lookingIn: { before: "正在查找 ", after: "…" },
    nothing: "没有可导入的内容，你将从头开始。",
    import: "导入",
    gone: "文件夹已不存在",
    allThere: "已在 Sens 中",
    sessions: (count: number) => `${count} 个会话`,
    alreadyIn: (count: number) => `${count} 个已在 Sens 中`,
    claudeSessions: "Claude Code 会话",
    sessionsIn: (sessions: number, projects: number) => `${projects} 个项目中的 ${sessions} 个会话`,
    none: "全不选",
    all: "全选",
    active: "来自 Claude Code，已启用",
    works: (skills: number, servers: number, plugins: number) => {
      const parts = [skills ? `${skills} 个技能` : "", servers ? `${servers} 个 MCP 服务器` : "", plugins ? `${plugins} 个插件` : ""].filter(Boolean);
      return `${joined(parts, "、", "和 ")}已在 Sens 中生效：Claude Code 会在每个会话中加载。`;
    },
    seeNames: "查看名称",
    carries: (keys: string) => `包含 ${keys}`,
    otherApps: "其他应用的 MCP 服务器",
    serversHint: "它们会添加到“能力”中，并在你导入的项目中启用。",
    whichProject: "从哪个项目开始？",
    project: "项目",
    pickLead: "选择一个项目文件夹。之后随时可以打开其他项目。",
    otherFolder: "选择其他文件夹…",
    pickTitle: "选择项目文件夹",
    preparing: "正在准备你的空间。",
    allSet: (first: string) => (first ? `一切就绪，${first}。` : "一切就绪。"),
    shortcuts: "快捷键",
    openFolder: "打开文件夹",
    sidebar: "侧边栏",
    openSens: "打开 Sens",
    noName: "未命名",
    unchecked: "尚未检查 Claude Code",
    sessionWord: () => "会话",
    projectWord: () => "项目",
    savingName: "正在保存你的名字…",
    nameSaved: (name: string) => `已保存名字 · ${name}`,
    importing: "正在导入会话…",
    importingCount: (done: number, total: number) => `正在导入会话 · ${done}/${total}`,
    imported: (sessions: number, projects: number) => `已将 ${sessions} 个会话导入 ${projects} 个项目`,
    addingServers: "正在添加 MCP 服务器…",
    serversAdded: (count: number) => `已添加 ${count} 个 MCP 服务器`,
  },
});
