import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    empty: "Subagents and commands the model runs in the background show up here.",
    command: "Command",
    subagent: "Subagent",
    task: "Task",
    stop: "Stop",
    working: "Working…",
    tools: (count: number) => (count === 1 ? "1 tool" : `${count} tools`),
    tokens: (amount: string) => `${amount} tokens`,
    stopped: "Stopped",
    failed: "Failed",
    failedWith: (code: string) => `Failed · exit code ${code}`,
    done: "Done",
    exitCode: (code: string) => `Exit code ${code}`,
    running: (count: number) => `${count} running`,
    tasks: (count: number) => (count === 1 ? "1 task" : `${count} tasks`),
  },
  es: {
    empty: "Aquí verás los subagentes y los comandos que el modelo lance en segundo plano.",
    command: "Comando",
    subagent: "Subagente",
    task: "Tarea",
    stop: "Detener",
    working: "Trabajando…",
    tools: (count: number) => (count === 1 ? "1 herramienta" : `${count} herramientas`),
    tokens: (amount: string) => `${amount} tokens`,
    stopped: "Detenido",
    failed: "Terminó con error",
    failedWith: (code: string) => `Terminó con error · código ${code}`,
    done: "Terminado",
    exitCode: (code: string) => `Código de salida ${code}`,
    running: (count: number) => `${count} en marcha`,
    tasks: (count: number) => (count === 1 ? "1 tarea" : `${count} tareas`),
  },
  fr: {
    empty: "Les sous-agents et les commandes que le modèle exécute en arrière-plan apparaissent ici.",
    command: "Commande",
    subagent: "Sous-agent",
    task: "Tâche",
    stop: "Arrêter",
    working: "En cours…",
    tools: (count: number) => (count <= 1 ? `${count} outil` : `${count} outils`),
    tokens: (amount: string) => `${amount} tokens`,
    stopped: "Arrêté",
    failed: "Échec",
    failedWith: (code: string) => `Échec · code de sortie ${code}`,
    done: "Terminé",
    exitCode: (code: string) => `Code de sortie ${code}`,
    running: (count: number) => `${count} en cours`,
    tasks: (count: number) => (count <= 1 ? `${count} tâche` : `${count} tâches`),
  },
  de: {
    empty: "Hier siehst du die Subagenten und Befehle, die das Modell im Hintergrund ausführt.",
    command: "Befehl",
    subagent: "Subagent",
    task: "Aufgabe",
    stop: "Stoppen",
    working: "Arbeitet…",
    tools: (count: number) => (count === 1 ? "1 Werkzeug" : `${count} Werkzeuge`),
    tokens: (amount: string) => `${amount} Tokens`,
    stopped: "Gestoppt",
    failed: "Fehlgeschlagen",
    failedWith: (code: string) => `Fehlgeschlagen · Exitcode ${code}`,
    done: "Fertig",
    exitCode: (code: string) => `Exitcode ${code}`,
    running: (count: number) => `${count} aktiv`,
    tasks: (count: number) => (count === 1 ? "1 Aufgabe" : `${count} Aufgaben`),
  },
  ja: {
    empty: "モデルがバックグラウンドで実行するサブエージェントとコマンドがここに表示されます。",
    command: "コマンド",
    subagent: "サブエージェント",
    task: "タスク",
    stop: "停止",
    working: "作業中…",
    tools: (count: number) => `ツール ${count} 回`,
    tokens: (amount: string) => `${amount} トークン`,
    stopped: "停止済み",
    failed: "エラーで終了",
    failedWith: (code: string) => `エラーで終了 · 終了コード ${code}`,
    done: "完了",
    exitCode: (code: string) => `終了コード ${code}`,
    running: (count: number) => `${count} 件実行中`,
    tasks: (count: number) => `${count} 件のタスク`,
  },
  zh: {
    empty: "模型在后台运行的子代理和命令会显示在这里。",
    command: "命令",
    subagent: "子代理",
    task: "任务",
    stop: "停止",
    working: "正在处理…",
    tools: (count: number) => `${count} 次工具调用`,
    tokens: (amount: string) => `${amount} token`,
    stopped: "已停止",
    failed: "失败",
    failedWith: (code: string) => `失败 · 退出码 ${code}`,
    done: "已完成",
    exitCode: (code: string) => `退出码 ${code}`,
    running: (count: number) => `${count} 个正在运行`,
    tasks: (count: number) => `${count} 个任务`,
  },
});
