import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    stage: { downloading: "Downloading…", verifying: "Verifying the signature…", installing: "Installing: Sens will close and open again" },
    devBuild: "Development build: it checks for updates but doesn’t install them.",
    working: (count: number) => (count === 1 ? "1 session is still working and will be stopped." : `${count} sessions are still working and will be stopped.`),
    youHave: (version: string) => `You’re on ${version}`,
    noNotes: "This version has no release notes.",
    viewOnGitHub: "View on GitHub",
    later: "Later",
    updateAnyway: "Update anyway",
    updateRestart: "Update and restart",
    checking: "Checking…",
    available: (version: string) => `Sens ${version} is available.`,
    latest: "You’re on the latest version.",
  },
  es: {
    stage: { downloading: "Descargando…", verifying: "Verificando la firma…", installing: "Instalando: Sens se cerrará y volverá a abrirse" },
    devBuild: "Build de desarrollo: comprueba pero no instala.",
    working: (count: number) => (count === 1 ? "Hay 1 sesión trabajando y se detendrá." : `Hay ${count} sesiones trabajando y se detendrán.`),
    youHave: (version: string) => `Tienes la ${version}`,
    noNotes: "Esta versión no trae notas.",
    viewOnGitHub: "Ver en GitHub",
    later: "Más tarde",
    updateAnyway: "Actualizar igualmente",
    updateRestart: "Actualizar y reiniciar",
    checking: "Comprobando…",
    available: (version: string) => `Sens ${version} disponible.`,
    latest: "Estás en la última versión.",
  },
  fr: {
    stage: { downloading: "Téléchargement…", verifying: "Vérification de la signature…", installing: "Installation : Sens va se fermer puis se rouvrir" },
    devBuild: "Version de développement : elle recherche les mises à jour sans les installer.",
    working: (count: number) => (count === 1 ? "1 session est encore en cours et sera arrêtée." : `${count} sessions sont encore en cours et seront arrêtées.`),
    youHave: (version: string) => `Vous utilisez la ${version}`,
    noNotes: "Cette version n’a pas de notes de version.",
    viewOnGitHub: "Voir sur GitHub",
    later: "Plus tard",
    updateAnyway: "Mettre à jour quand même",
    updateRestart: "Mettre à jour et redémarrer",
    checking: "Vérification…",
    available: (version: string) => `Sens ${version} est disponible.`,
    latest: "Vous avez la dernière version.",
  },
  de: {
    stage: { downloading: "Wird heruntergeladen…", verifying: "Signatur wird geprüft…", installing: "Wird installiert: Sens schließt sich und startet neu" },
    devBuild: "Entwicklungsversion: sucht nach Updates, installiert sie aber nicht.",
    working: (count: number) => (count === 1 ? "1 Sitzung arbeitet noch und wird gestoppt." : `${count} Sitzungen arbeiten noch und werden gestoppt.`),
    youHave: (version: string) => `Du hast ${version}`,
    noNotes: "Diese Version hat keine Versionshinweise.",
    viewOnGitHub: "Auf GitHub ansehen",
    later: "Später",
    updateAnyway: "Trotzdem aktualisieren",
    updateRestart: "Aktualisieren und neu starten",
    checking: "Wird geprüft…",
    available: (version: string) => `Sens ${version} ist verfügbar.`,
    latest: "Du hast die neueste Version.",
  },
  ja: {
    stage: { downloading: "ダウンロード中…", verifying: "署名を検証しています…", installing: "インストール中: Sens はいったん閉じてから再び開きます" },
    devBuild: "開発ビルドです。アップデートの確認はしますが、インストールはしません。",
    working: (count: number) => `作業中のセッションが ${count} 件あり、停止されます。`,
    youHave: (version: string) => `現在のバージョン: ${version}`,
    noNotes: "このバージョンにはリリースノートがありません。",
    viewOnGitHub: "GitHub で見る",
    later: "後で",
    updateAnyway: "このままアップデート",
    updateRestart: "アップデートして再起動",
    checking: "確認中…",
    available: (version: string) => `Sens ${version} を利用できます。`,
    latest: "最新バージョンです。",
  },
  zh: {
    stage: { downloading: "正在下载…", verifying: "正在验证签名…", installing: "正在安装：Sens 将关闭并重新打开" },
    devBuild: "开发版本：会检查更新，但不会安装。",
    working: (count: number) => `有 ${count} 个会话仍在运行，将被停止。`,
    youHave: (version: string) => `当前版本：${version}`,
    noNotes: "此版本没有发布说明。",
    viewOnGitHub: "在 GitHub 上查看",
    later: "稍后",
    updateAnyway: "仍然更新",
    updateRestart: "更新并重启",
    checking: "正在检查…",
    available: (version: string) => `Sens ${version} 现已可用。`,
    latest: "已是最新版本。",
  },
});
