import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    activity: { working: "Working", waiting: "Waiting for your answer", done: "Finished" },
    view: { capabilities: "Capabilities", artifacts: "Artifacts" },
    noSessionsYet: "No sessions yet.",
    openProject: "Open project",
    newSessionIn: (name: string) => `New session in ${name}`,
    manage: (name: string) => `Manage ${name}`,
    noSessions: "No sessions.",
    messages: (count: number) => (count === 1 ? "1 message" : `${count} messages`),
    archived: "archived",
    manageSession: "Manage session",
    sessionName: "Session name",
    manageFolder: "Manage folder",
    untrust: "Stop trusting",
    openBeside: "Open side by side",
    rename: "Rename",
    archive: "Archive",
    unarchive: "Unarchive",
    confirm: "Confirm delete",
    remove: "Delete",
  },
  es: {
    activity: { working: "Trabajando", waiting: "Esperando tu respuesta", done: "Terminó" },
    view: { capabilities: "Capacidades", artifacts: "Artefactos" },
    noSessionsYet: "Todavía no hay sesiones.",
    openProject: "Abrir proyecto",
    newSessionIn: (name: string) => `Sesión nueva en ${name}`,
    manage: (name: string) => `Gestionar ${name}`,
    noSessions: "Sin sesiones.",
    messages: (count: number) => (count === 1 ? "1 mensaje" : `${count} mensajes`),
    archived: "archivada",
    manageSession: "Gestionar sesión",
    sessionName: "Nombre de la sesión",
    manageFolder: "Gestionar carpeta",
    untrust: "Dejar de confiar",
    openBeside: "Abrir al lado",
    rename: "Renombrar",
    archive: "Archivar",
    unarchive: "Desarchivar",
    confirm: "Confirmar",
    remove: "Eliminar",
  },
  fr: {
    activity: { working: "En cours", waiting: "En attente de votre réponse", done: "Terminée" },
    view: { capabilities: "Capacités", artifacts: "Artefacts" },
    noSessionsYet: "Aucune session pour l’instant.",
    openProject: "Ouvrir un projet",
    newSessionIn: (name: string) => `Nouvelle session dans ${name}`,
    manage: (name: string) => `Gérer ${name}`,
    noSessions: "Aucune session.",
    messages: (count: number) => (count <= 1 ? `${count} message` : `${count} messages`),
    archived: "archivée",
    manageSession: "Gérer la session",
    sessionName: "Nom de la session",
    manageFolder: "Gérer le dossier",
    untrust: "Ne plus faire confiance",
    openBeside: "Ouvrir à côté",
    rename: "Renommer",
    archive: "Archiver",
    unarchive: "Désarchiver",
    confirm: "Confirmer la suppression",
    remove: "Supprimer",
  },
  de: {
    activity: { working: "Arbeitet", waiting: "Wartet auf deine Antwort", done: "Fertig" },
    view: { capabilities: "Fähigkeiten", artifacts: "Artefakte" },
    noSessionsYet: "Noch keine Sitzungen.",
    openProject: "Projekt öffnen",
    newSessionIn: (name: string) => `Neue Sitzung in ${name}`,
    manage: (name: string) => `${name} verwalten`,
    noSessions: "Keine Sitzungen.",
    messages: (count: number) => (count === 1 ? "1 Nachricht" : `${count} Nachrichten`),
    archived: "archiviert",
    manageSession: "Sitzung verwalten",
    sessionName: "Name der Sitzung",
    manageFolder: "Ordner verwalten",
    untrust: "Nicht mehr vertrauen",
    openBeside: "Daneben öffnen",
    rename: "Umbenennen",
    archive: "Archivieren",
    unarchive: "Archivierung aufheben",
    confirm: "Löschen bestätigen",
    remove: "Löschen",
  },
  ja: {
    activity: { working: "作業中", waiting: "返信待ち", done: "完了" },
    view: { capabilities: "機能", artifacts: "アーティファクト" },
    noSessionsYet: "セッションはまだありません。",
    openProject: "プロジェクトを開く",
    newSessionIn: (name: string) => `${name} で新しいセッション`,
    manage: (name: string) => `${name} を管理`,
    noSessions: "セッションはありません。",
    messages: (count: number) => `${count} 件のメッセージ`,
    archived: "アーカイブ済み",
    manageSession: "セッションを管理",
    sessionName: "セッション名",
    manageFolder: "フォルダーを管理",
    untrust: "信頼を解除",
    openBeside: "横に並べて開く",
    rename: "名前を変更",
    archive: "アーカイブ",
    unarchive: "アーカイブを解除",
    confirm: "削除を確定",
    remove: "削除",
  },
  zh: {
    activity: { working: "处理中", waiting: "等待你的回复", done: "已完成" },
    view: { capabilities: "能力", artifacts: "工件" },
    noSessionsYet: "还没有会话。",
    openProject: "打开项目",
    newSessionIn: (name: string) => `在 ${name} 中新建会话`,
    manage: (name: string) => `管理 ${name}`,
    noSessions: "没有会话。",
    messages: (count: number) => `${count} 条消息`,
    archived: "已归档",
    manageSession: "管理会话",
    sessionName: "会话名称",
    manageFolder: "管理文件夹",
    untrust: "取消信任",
    openBeside: "并排打开",
    rename: "重命名",
    archive: "归档",
    unarchive: "取消归档",
    confirm: "确认删除",
    remove: "删除",
  },
});
