import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    profile: "Profile",
    settings: "Settings",
    shortcuts: "Keyboard shortcuts",
    about: "About Sens",
    noName: "No name",
    shift: "Shift",
    send: "Send",
    newLine: "New line",
    paste: "Paste a picture into the message",
    sidebar: "Show or hide the sidebar",
    openFolder: "Open folder",
    terminal: "Show or hide the terminal",
  },
  es: {
    profile: "Perfil",
    settings: "Ajustes",
    shortcuts: "Atajos de teclado",
    about: "Acerca de Sens",
    noName: "Sin nombre",
    shift: "Mayús",
    send: "Enviar",
    newLine: "Nueva línea",
    paste: "Pegar una imagen en el mensaje",
    sidebar: "Mostrar u ocultar la barra lateral",
    openFolder: "Abrir carpeta",
    terminal: "Mostrar u ocultar la terminal",
  },
  fr: {
    profile: "Profil",
    settings: "Paramètres",
    shortcuts: "Raccourcis clavier",
    about: "À propos de Sens",
    noName: "Sans nom",
    shift: "Maj",
    send: "Envoyer",
    newLine: "Nouvelle ligne",
    paste: "Coller une image dans le message",
    sidebar: "Afficher ou masquer la barre latérale",
    openFolder: "Ouvrir un dossier",
    terminal: "Afficher ou masquer le terminal",
  },
  de: {
    profile: "Profil",
    settings: "Einstellungen",
    shortcuts: "Tastenkürzel",
    about: "Über Sens",
    noName: "Kein Name",
    shift: "Umschalt",
    send: "Senden",
    newLine: "Neue Zeile",
    paste: "Bild in die Nachricht einfügen",
    sidebar: "Seitenleiste ein- oder ausblenden",
    openFolder: "Ordner öffnen",
    terminal: "Terminal ein- oder ausblenden",
  },
  ja: {
    profile: "プロフィール",
    settings: "設定",
    shortcuts: "キーボードショートカット",
    about: "Sens について",
    noName: "名前なし",
    shift: "Shift",
    send: "送信",
    newLine: "改行",
    paste: "メッセージに画像を貼り付け",
    sidebar: "サイドバーの表示・非表示",
    openFolder: "フォルダーを開く",
    terminal: "ターミナルの表示・非表示",
  },
  zh: {
    profile: "个人资料",
    settings: "设置",
    shortcuts: "键盘快捷键",
    about: "关于 Sens",
    noName: "未命名",
    shift: "Shift",
    send: "发送",
    newLine: "换行",
    paste: "在消息中粘贴图片",
    sidebar: "显示或隐藏侧边栏",
    openFolder: "打开文件夹",
    terminal: "显示或隐藏终端",
  },
});
