import { copy } from "../../shared/i18n";

export const t = copy({
  en: {
    states: { A: "New", M: "Modified", D: "Deleted", R: "Renamed" },
    noFolder: "No folder.",
    reading: "Reading changes…",
    notRepo: "This folder isn’t in a Git repository.",
    clean: "No changes since the last commit.",
    more: (count: number) => (count === 1 ? "And 1 more file." : `And ${count} more files.`),
    files: (count: number) => (count === 1 ? "1 file" : `${count} files`),
    openInFiles: "Open in Files",
    binary: "binary",
    fresh: "new",
    binaryFile: "Binary file.",
    renamedOnly: "Renamed, no content changes.",
    sameContent: "No content changes.",
  },
  es: {
    states: { A: "Nuevo", M: "Modificado", D: "Borrado", R: "Renombrado" },
    noFolder: "Sin carpeta.",
    reading: "Leyendo cambios…",
    notRepo: "Esta carpeta no está en un repositorio Git.",
    clean: "Sin cambios desde el último commit.",
    more: (count: number) => (count === 1 ? "Y 1 fichero más." : `Y ${count} ficheros más.`),
    files: (count: number) => (count === 1 ? "1 fichero" : `${count} ficheros`),
    openInFiles: "Abrir en Ficheros",
    binary: "binario",
    fresh: "nuevo",
    binaryFile: "Fichero binario.",
    renamedOnly: "Renombrado, sin cambios de contenido.",
    sameContent: "Sin cambios de contenido.",
  },
  fr: {
    states: { A: "Nouveau", M: "Modifié", D: "Supprimé", R: "Renommé" },
    noFolder: "Aucun dossier.",
    reading: "Lecture des modifications…",
    notRepo: "Ce dossier n’est pas dans un dépôt Git.",
    clean: "Aucune modification depuis le dernier commit.",
    more: (count: number) => (count <= 1 ? `Et ${count} autre fichier.` : `Et ${count} autres fichiers.`),
    files: (count: number) => (count <= 1 ? `${count} fichier` : `${count} fichiers`),
    openInFiles: "Ouvrir dans Fichiers",
    binary: "binaire",
    fresh: "nouveau",
    binaryFile: "Fichier binaire.",
    renamedOnly: "Renommé, contenu inchangé.",
    sameContent: "Contenu inchangé.",
  },
  de: {
    states: { A: "Neu", M: "Geändert", D: "Gelöscht", R: "Umbenannt" },
    noFolder: "Kein Ordner.",
    reading: "Änderungen werden gelesen…",
    notRepo: "Dieser Ordner liegt in keinem Git-Repository.",
    clean: "Keine Änderungen seit dem letzten Commit.",
    more: (count: number) => (count === 1 ? "Und 1 weitere Datei." : `Und ${count} weitere Dateien.`),
    files: (count: number) => (count === 1 ? "1 Datei" : `${count} Dateien`),
    openInFiles: "In Dateien öffnen",
    binary: "binär",
    fresh: "neu",
    binaryFile: "Binärdatei.",
    renamedOnly: "Umbenannt, Inhalt unverändert.",
    sameContent: "Inhalt unverändert.",
  },
  ja: {
    states: { A: "新規", M: "変更", D: "削除", R: "名前変更" },
    noFolder: "フォルダーがありません。",
    reading: "変更を読み込んでいます…",
    notRepo: "このフォルダーは Git リポジトリにありません。",
    clean: "前回のコミット以降の変更はありません。",
    more: (count: number) => `ほかに ${count} 個のファイルがあります。`,
    files: (count: number) => `${count} 個のファイル`,
    openInFiles: "ファイルパネルで開く",
    binary: "バイナリ",
    fresh: "新規",
    binaryFile: "バイナリファイルです。",
    renamedOnly: "名前が変更されただけで、内容は変わっていません。",
    sameContent: "内容は変わっていません。",
  },
  zh: {
    states: { A: "新增", M: "已修改", D: "已删除", R: "已重命名" },
    noFolder: "没有文件夹。",
    reading: "正在读取更改…",
    notRepo: "此文件夹不在 Git 仓库中。",
    clean: "自上次提交以来没有更改。",
    more: (count: number) => `还有 ${count} 个文件。`,
    files: (count: number) => `${count} 个文件`,
    openInFiles: "在文件面板中打开",
    binary: "二进制",
    fresh: "新增",
    binaryFile: "二进制文件。",
    renamedOnly: "仅重命名，内容未更改。",
    sameContent: "内容未更改。",
  },
});
